### ISSUE TITLE
Add to README gradle extension config

### ISSUE THREAD

**Issue by Alex009** [icerockdev/moko-resources#11]
install block must contain addition to build.gradle.kts
```
multiplatformResources {
    multiplatformResourcesPackage = "com.icerockdev.library"
}
```

**Comment by Alex009** [comment]
fixed

**Comment by tringkishorekumar** [comment]
multiplatformResources this method is not found in my build.gradle.kts, new to android sorry if its naive

**Comment by Alex009** [comment]
@tringkishorekumar you should apply plugin in project. it's described in readme. and you can see it in sample
