### ISSUE TITLE
AAPT: error: invalid color

### ISSUE THREAD

**Issue by geckogecko** [icerockdev/moko-resources#112]
Based on the sample I tried to add color support by adding `colors.xml` to `/resources/MR/colors`

```
<?xml version="1.0" encoding="utf-8"?>
<resources>
    <color name="textColor">0xFF00FFFF</color>
</resources>
```

When I build the project I receive the error: 
`/<path>/build/intermediates/packaged_res/debug/values/values.xml:3:5-48: AAPT: error: invalid color.`

This is how the generated `values.xml` that couses the error looks like:
```
<resources>
    <color name="textColor">#FF0xFF00FF</color>
</resources>
```

**Comment by Alex009** [comment]
@geckogecko hi!
for now not write 0x as in sample - https://github.com/icerockdev/moko-resources/blob/master/sample/mpp-library/src/commonMain/resources/MR/colors/colors.xml
in later releases we will automatically remove it
