### ISSUE TITLE
Add option to fill in missing string translations with base translation

### ISSUE THREAD

**Issue by dalewking** [icerockdev/moko-resources#118]
The issue here is what is the fallback behavior if a string does not have a translation. This happens for us because our translation department follows a weekly cadence of updating translations.

For Android it is not an issue. If a translation is missing it just falls back and supplies the base string. For iOS however, it does not fall back to the base string, it falls back to the actual key name. This can have some very weird behavior if for example the string represents a date format.

So I would like a way to tell moko resources to use the base translation if the translation is missing, not the string key. I would turn this on for development. We have a task that will fail release builds for missing translations

**Comment by AdrianHz** [comment]
Hello, I still encounter this issue to this day. Any updates regarding the possibility of adding a solution in the future?

**Comment by dalewking** [comment]
Somewhat related, we accidentally had an invalid escape sequence in the translations for German (it was a \") which resulted in none of the German translations making it into the app so in German every string was coming out as the key.

**Comment by colintheshots** [comment]
Languages we don't translate are also returning the string key. This is far more problematic than simply having this happen when we miss translating one or two strings. If this is easily reproducible, I think this should be considered a bug more than an enhancement.

**Comment by bravo-delta** [comment]
I'd also really appreciate if this feature could be added.

If the translation is driven by volunteers from the community, the translation for each language is never finished in time, so there are lots of new texts in each release that should at least default to the text from the base locale instead of showing the key, which no user can make any sense of.

**Comment by Alex009** [comment]
will be in 0.24.0

**Comment by alobaili** [comment]
@Alex009 I suggest updating the documentation. Specifically, point number 3 in ["iOS shows key instead of localized text"](https://github.com/icerockdev/moko-resources?tab=readme-ov-file#known-issues). It mentions that "iOS not fallback to base locale now".
