### ISSUE TITLE
Add support of Android Application gradle module

### ISSUE THREAD

**Issue by brettwillis** [icerockdev/moko-resources#119]
Hi, looks like a very useful project, I have been trying to get your project to work in my Kotlin multiplatform (Android & iOS) project. It is a single Gradle project for both apps, using Android Application plugin, not Android Library plugin.

No errors appear, but the `generateMRcommonMain` task is missing, and of course no resources are generated. The line below leads me to believe only library projects are supported. All your sample projects are library projects.

https://github.com/icerockdev/moko-resources/blob/e2750b5b03c811d1b4611b9d08c92f958cdd7a2e/plugins/resources-generator/src/main/kotlin/dev/icerock/gradle/MultiplatformResourcesPlugin.kt#L46

Why - can you not also support Android Application projects? Or please have some warning documentation to make this clear for people in the future?

**Comment by Alex009** [comment]
hello! sorry for late reply. 
yes, for now we support only libraries, but i think we can add support of app modules later.

also can you describe why your multiplatform code enabled in application module, not separated library?

**Comment by brettwillis** [comment]
Thanks.

> also can you describe why your multiplatform code enabled in application module, not separated library?

I only have a single app per platform (1x Android, 1x iOS), not multiple apps per platform, so a library module is not required. The application module itself is multiplatform and I don't need an extra library module.

**Comment by Alex009** [comment]
will be released in 0.14.0
