### ISSUE TITLE
String resource formatting fails when using multiple arguments

### ISSUE THREAD

**Issue by RezMike** [icerockdev/moko-resources#121]
This code fails with "MissingFormatArgumentException: Format specifier '%s'"
```
<string name="formatted_string">Some string %s to %s</string>
```
```
val str = MR.strings.formatted_string.format(string1, string2)
```
When I change the last line to this, no error appears:
```
val str = StringDesc.ResourceFormatted(MR.strings.formatted_string, string1, string2)
```

**Comment by Alex009** [comment]
we should add star here - https://github.com/icerockdev/moko-resources/blob/master/resources/src/commonMain/kotlin/dev/icerock/moko/resources/StringResource.kt#L12
