### ISSUE TITLE
StringDesc generation proposal 

### ISSUE THREAD

**Issue by nrobi144** [icerockdev/moko-resources#122]
Currently in order to use the moko strings on the iOS side too, one needs to wrap or make `StringDesc` resources with the `MR` resource ids. 
On my project, what I did is create a common `Strings`, which has only this purpose. I was wondering if we could generate them automatically after the `MR.strings.xy` generation. So for example, it'd be nice if we would get something like this in the common:

```
class Strings {
    val appName = StringDesc.Resource(MR.strings.app_name)
    fun getMyPluralFormattedDesc(quantity: Int) = StringDesc.PluralFormatted(MR.plurals.my_plural, quantity, quantity)  
}
``` 

Let me know if it doesn't make sense on your end or if it has technical barriers

**Comment by Alex009** [comment]
hi @nrobi144 !
i don't think that we need generate desc class.
you can just use extensions, like:
```
MR.strings.app_name.desc()
```
https://github.com/icerockdev/moko-resources/blob/master/resources/src/commonMain/kotlin/dev/icerock/moko/resources/desc/StringDesc.kt#L22

it's solve your issue?

**Comment by nrobi144** [comment]
Wow, completely missed that one.

`ResourcesResourceStringDesc(stringRes: MR.strings().app_name).localized()` on the iOS side does the job, now I've got some refactoring to do 😅
