### ISSUE TITLE
How to use with Kotlin DSL (build.gradle.kts)

### ISSUE THREAD

**Issue by ln-12** [icerockdev/moko-resources#125]
I know that I have to add 
```
multiplatformResources {
    multiplatformResourcesPackage = "com.jetbrains.handson.kmm.shared" // required
    iosBaseLocalizationRegion = "en" // optional, default "en"
    multiplatformResourcesSourceSet = "commonClientMain"  // optional, default "commonMain"
}
```
to the build.gradle file. But how do I have to adjust the code to use the new Kotlin DSL (build.gradle.kts). Now I only get the `Required value was null.` error.

**Comment by Alex009** [comment]
@ln-12 you can see in sample here in repo - we use kotlin dsl.
required value is `multiplatformResourcesPackage`. here we will improve information about error #123 
run please build with `--stacktrace` flag, maybe problem not with resources

**Comment by ln-12** [comment]
I put it inside the `kotlin {}` braces and now it works.
