### ISSUE TITLE
macOS target support

### ISSUE THREAD

**Issue by nrobi144** [icerockdev/moko-resources#127]
Are there any plans to support desktop and macOS targets?

**Comment by Alex009** [comment]
as i answer in slack - for this have no plans. but i can help external contributors with consultations how implement it.
in exchange for pull request with this changes :)

here small sample - https://github.com/icerockdev/moko-parcelize/compare/develop...%236-macos-support

**Comment by Alex009** [comment]
@nrobi144 in new [mobile-multiplatform gradle plugin release](https://github.com/icerockdev/mobile-multiplatform-gradle-plugin/releases/tag/release%2F0.9.0) was added support of all apple family frameworks, in moko-graphics and moko-parcelize releases it was used:
https://github.com/icerockdev/moko-graphics/pull/11/files
https://github.com/icerockdev/moko-parcelize/pull/9/files

so in resources it should be used too.

for resources will be required this: 
https://github.com/icerockdev/moko-graphics/blob/master/buildSrc/src/main/kotlin/Deps.kt#L43 
to correctly export dependency into macos framework here:
https://github.com/icerockdev/moko-graphics/blob/master/sample/mpp-library/build.gradle.kts#L21
you should use apple-framework plugin
https://github.com/icerockdev/moko-graphics/blob/master/buildSrc/src/main/kotlin/Deps.kt#L29

also moko-graphics and moko-parcelize already available on bintray (version 0.5.0 both).
