### ISSUE TITLE
Retrieving strings in iOS

### ISSUE THREAD

**Issue by ln-12** [icerockdev/moko-resources#128]
After checking out the android side, I now want to use this library under iOS. In the readme you state that I have to write something like 
```
fun getMyString(): StringDesc {
  return StringDesc.Resource(MR.strings.my_string)
}
```
for each single string I define to call this method from iOS. Is there a more convenient way? It feels like a lot of duplication if I need to write everything as method. In swift I would like to have a more generic approach so that I could write something like
```
let myString = someGenericMethod(MR.strings.app_name).localized()
print(myString)
```

Is that possible?

**Comment by Alex009** [comment]
hello @ln-12 !
you can use extension `desc()`:
`MR.strings.app_name.desc().localized()`
or implement simple swift (or in kotlin) extension:
```
extension StringResource {
    func localized() -> String {
        return NSLocalizedString(resourceId, bundle: bundle, comment: "")
    }
}
```
and call:
```
MR.strings.app_name.localized()
```

**Comment by ln-12** [comment]
Thanks for the fast reply! Looks great :)
