### ISSUE TITLE
Unresolved references in IDE

### ISSUE THREAD

**Issue by hlnstepanova** [icerockdev/moko-resources#132]
Hi, I  have difficulties using the library and would appreciate any help.

First of all, I have strings.xml in commonMain/resources/MR/base 
```
<resources>
    <string name="error">Unexpected error</string>
</resources>
```
When I wan to use them in a shared loginModel from package de.comp.projkmm.shared.models like this

```
 suspend fun logout(): StringDesc? {
        try {
            ktorApi.logout()
            settings.putLong(EXPIRATION_TIME_KEY, 0)
            settings.putString(ACCESS_TOKEN_KEY, "")
        } catch (e: Exception) {
            log.i { e.toString() }
            return StringDesc.Resource(MR.strings.logout_failed)
        }
        return null
    }
```

MR is unresolved and first I have to import the generated class to use the strings
`import de.comp.projkmm.shared.resources.MR`
 Is it the correct way or am I doing something wrong? In the sample app there is no need to import MR separately, so I think I'm doing it wrong

Then I would also like to use strings from shared library in Android or iOS UI items. For example, in every error dialog (both in Android and iOS apps) I want to set the title to "Unexpected error". Following the sample, I tried creating Testing.kt in commonMain like this:

```
package de.comp.projkmm.shared

import dev.icerock.moko.resources.desc.Resource
import dev.icerock.moko.resources.desc.StringDesc

@Suppress("MagicNumber")
object Testing {
    fun getErrorString(): StringDesc {
        return StringDesc.Resource(MR.strings.error)
    }

}
```

I expected to be able to get string when building a dialog in a LoginFragment in androidApp just by calling Testing.getErrorString(), like this:

```
import de.enveto.revkmm.shared.Testing

...
...
...

 loginViewModel.errorLiveData.observe(viewLifecycleOwner, Observer { error ->
            error?.let {
                val dialogBuilder = AlertDialog.Builder(activity!!)
                val alert = dialogBuilder.setMessage(it.toString(activity!!))
                    .setCancelable(false)
                    .setPositiveButton(getString(R.string.ok)) { dialog, _ ->
                        dialog.dismiss()

                    }
                    .create()

                alert.setTitle(Testing.getErrorString().toString(activity!!))
                alert.show()
            }

        })
```

But Android Studio shows "unresolved reference: Testing"
Surprisingly, when I run the app, everything works.

Moreover, I get unresolved references for other classes from shared folder, like my models or entities. Before starting to use the library, IDE had no remarks about those.

So my question is basically am I doing everything right (especially with all the imports) and is there anything else I can do to stop the IDE from not recognising things?

**Comment by Alex009** [comment]
hi @hlnstepanova !
can you show logs from run `./gradlew build` ? i think something wrong at configuration stage and it will be showed in log.
or maybe you can give reproducer project? if project is opensource i can check it and send PR with fixes

**Comment by hlnstepanova** [comment]
Hi @Alex009 
Here is the result from build. Saw it before, but didn't pay much attention, as Build Output said "Build successful"

FAILURE: Build failed with an exception.

* What went wrong:
Could not determine the dependencies of task ':shared:compileKotlinMetadata'.
> Couldn't resolve metadata artifact for ModuleDependencyIdentifier(groupId=dev.icerock.moko, moduleId=parcelize) in configuration ':shared:iosCompileKlibraries'


Unfortunately I cannot share the source code, but let me know if I get any other info

**Comment by Alex009** [comment]
please add this dependencies:
```
// temporary fix of https://youtrack.jetbrains.com/issue/KT-41083
commonMainImplementation("dev.icerock.moko:parcelize:0.4.0")
commonMainImplementation("dev.icerock.moko:graphics:0.4.0")
```

**Comment by hlnstepanova** [comment]
Now it builds, thanks!
