### ISSUE TITLE
copyFrameworkResourcesToApp task failed if kotlin framework depends on cocoapods

### ISSUE THREAD

**Issue by ln-12** [icerockdev/moko-resources#135]
I already contacted the Kotlin team [here](https://youtrack.jetbrains.com/issue/KT-35608#focus=Comments-27-4577651.0-0) and [here](https://youtrack.jetbrains.com/issue/KT-43873) about the problem and they told me to ask here.

I am using the [KaMPKit template](https://github.com/touchlab/KaMPKit) to add SQLCipher to my project which already uses moko-resources. Before adding the custom cocoapods plugin, everything worked fine and I could get the resources under iOS. Now KaMPKit uses the cocoapods plugin fork by Touchlab (see [here](https://github.com/touchlab/KaMPKit/blob/master/docs/IOS_PROJ_INTEGRATION.md)). With these changes, I can't make it work again. Either the project does not build at all because it can't find the SQLCiper headers or it crahes at runtime as the bundle is not found.

Could you please have a look at my [example project](https://github.com/ln-12/moko-resources-issue-99) so see if I miss any configuration step? Or this this an issue which the guys over at touchlab should fix? Thanks in advance!

**Comment by Alex009** [comment]
hi, @ln-12 !
in your example used `static` framework. so you should add into xcode project additional build phase - https://github.com/icerockdev/moko-resources#static-kotlin-frameworks-support
sample here - https://github.com/icerockdev/moko-resources/blob/0d9cdb81ea3b96da1fde9c40c9efdb2490c84fae/sample/ios-app/TestProj.xcodeproj/project.pbxproj#L279 (sample target testhierarhical)

**Comment by ln-12** [comment]
Hey, I know that I have to add the build phase. When I add it in the XCode project, like you mentioned, the build is going to fail (see the latest commit in my example project). That's why I thought it might be added in the `shared`podspec file, but that doesn't help. The problem is not that I can't get moko resources running - standalone works fine. The problem is getting it to work with the cocoapods plugin mentioned above.

![image](https://user-images.githubusercontent.com/36760115/102761124-c4175f00-4376-11eb-80bf-3a97d9995949.png)

**Comment by Alex009** [comment]
now i see problem. 
here fix - https://github.com/ln-12/moko-resources-issue-99/pull/2/files
problem is that in 
```
"$SRCROOT/../gradlew" -p "$SRCROOT/../" :yourframeworkproject:copyFrameworkResourcesToApp \
    -Pmoko.resources.PLATFORM_NAME=$PLATFORM_NAME \
    -Pmoko.resources.CONFIGURATION=$CONFIGURATION \
    -Pmoko.resources.BUILT_PRODUCTS_DIR=$BUILT_PRODUCTS_DIR \
    -Pmoko.resources.CONTENTS_FOLDER_PATH=$CONTENTS_FOLDER_PATH
```
`copyFrameworkResourcesToApp` task depends on `linkFramework` task, but for `link` with cocoapods we should pass extra properties.
so script should be:
```
"$SRCROOT/../gradlew" -p "$SRCROOT/../" :shared:copyFrameworkResourcesToApp \
    -Pmoko.resources.PLATFORM_NAME=$PLATFORM_NAME \
    -Pmoko.resources.CONFIGURATION=$CONFIGURATION \
    -Pmoko.resources.BUILT_PRODUCTS_DIR=$BUILT_PRODUCTS_DIR \
    -Pmoko.resources.CONTENTS_FOLDER_PATH=$CONTENTS_FOLDER_PATH\
    -Pkotlin.native.cocoapods.target=$KOTLIN_TARGET \
    -Pkotlin.native.cocoapods.configuration=$CONFIGURATION \
    -Pkotlin.native.cocoapods.cflags="$OTHER_CFLAGS" \
    -Pkotlin.native.cocoapods.paths.headers="$HEADER_SEARCH_PATHS" \
    -Pkotlin.native.cocoapods.paths.frameworks="$FRAMEWORK_SEARCH_PATHS"
```
and we should add build setting `KOTLIN_TARGET` which depends on ios compiler sdk:
```
'KOTLIN_TARGET[sdk=iphonesimulator*]' => 'ios_x64'
'KOTLIN_TARGET[sdk=iphoneos*]' => 'ios_arm'
```

**Comment by ln-12** [comment]
Nice, thank you very much for your effort!

**Comment by Alex009** [comment]
added to readme in 0.14.0
