### ISSUE TITLE
gradle - Always-Run Tasks

### ISSUE THREAD

**Issue by tieskedh** [icerockdev/moko-resources#150]
_First of all, thanks for this library!_
_I'm using it with a surrounding module with manual expect-actual declarations for JVM-desktop_
_(I don't have enough knowledge to contribute yet)_

_I don't know if it's a real issue (as task-execution time is very low), but because it wasn't mentioned yet:_

NOTICE: 
**The tasks created by this library are always-run tasks and don't allow incremental execution, see also:
https://docs.gradle.org/current/userguide/more_about_tasks.html#sec:up_to_date_checks**

**Comment by Alex009** [comment]
good point, thx. in future we add up-to-date checks

**Comment by Alex009** [comment]
and it will be very helpful if you add issue about JVM support with your implemented `actual` declarations. with this it will be easier for us to add JVM support to the library
