### ISSUE TITLE
Add JVM target

### ISSUE THREAD

**Issue by nrobi144** [icerockdev/moko-resources#151]
Having a JVM target also would make it possible to easily port applications to Desktop also with shared localization.

AFAIK the setup should be fairly similar to the Android one, but I'll dig into it

**Comment by nrobi144** [comment]
@Alex009 I'll try to play around with this. Did you already try targetting `jvm` or the original plan for the repo was mainly mobile platforms?

**Comment by Alex009** [comment]
@nrobi144 we, with you, already add into project macos target :) so here not only mobile platforms. and jvm target will be very interesting for `Compose for Desktop` users. 
now generator for android generates all for android-resources system. but in jvm it's not same. so i think here will be some significant differences... for example resources will be get from `ClassLoader.getResources(String name)`, not by some `R` file :)

if you have any questions related to the device of the library and plug-in - ask, I will help
