### ISSUE TITLE
VectorDrawable

### ISSUE THREAD

**Issue by cl3m** [icerockdev/moko-resources#155]
Thank you for this great library!

I have two suggestions for the drawables:

First, you should add the xml extension support with would allow to share VectorDrawable in android and iOS (with the library https://github.com/uber/cyborg)

Second, you should allow the images in the android structure instead of @2x @3x etc. The rest are android file format and it would be more consistent. Moreover that it would allow to just move android resource to kotlin multi platform resource.

**Comment by cl3m** [comment]
For backward compatibility, you can keep the images folder and allow the new folders that works the other way: 

* drawable (xml)		
* drawable-mdpi (png/jpg)	
* drawable-xxhdpi(png/jpg)	
* drawable-hdpi (png/jpg)	
* drawable-xhdpi	(png/jpg)	
* drawable-xxxhdpi(png/jpg)

**Comment by Alex009** [comment]
hi! thanks. 
vector images issue here #29 , you can move your info about cyborg to this issue. but we have no plan to implement it in near future...maybe you want do it? in this case i can support it by share own knowledge about plugin and runtime lib

about second - we have not goal "just move android resources", so maybe implement same structure later. name `drawable` will be invalid because we support only images, not xml drawables, and on iOS not exist any drawable at all.

**Comment by cl3m** [comment]
I don't know much about plugins yet so maybe not soon but I'll look into it if you don't. 

Another thing that is weird with your library is that the color are in RGBA in MR but are in ARGB in android colors.xml. That was quite confusing. Maybe you should write something about it in the readme.

**Comment by chris-hatton** [comment]
Using vector graphics directly at runtime can be desirable, especially for Multiplatform projects where image-sizing hell becomes even more prevalent.  However coercing all platforms to use Android's proprietary `VectorDrawable` XML format, doesn't feel like the right way to go.  Plain SVG is a more neutral format and has 3rd party library support on both platforms e.g. [SVGKit](https://github.com/SVGKit/SVGKit) and [AndroidSVG](https://bigbadaboom.github.io/androidsvg/).

As I understand, the reason for `VectorDrawable` to exist is to narrow-down on a sub-set of the SVG format that's guaranteed to perform better on Android.  This is something you can manage for yourself if you're in control of the SVG asset preparation.

Hence, we could achieve vector on both platforms just by using the file resources feature of MokoResources, although this is undocumented #161.

**Comment by Alex009** [comment]
will be released in 0.22.0
