### ISSUE TITLE
String are not updated for ios if string.xml is too long

### ISSUE THREAD

**Issue by mustafaozhan** [icerockdev/moko-resources#156]
Hello 👋 

I found out that if the `base/strings.xml` is too long library returns the key of the strings instead of the value, to give a clue i had around 140 lines in strings.xml (Including empty lines and comment lines)

please check this [file](https://github.com/CurrencyConverterCalculator/CCC/pull/77/commits/c03b8f83c577c3a2abd593be4da0583fc9bb8a0a), 
after i commented the line library started to work again :)

**Comment by Alex009** [comment]
i will see it on weekend

**Comment by mustafaozhan** [comment]
Sure, thanks a lot!

**Comment by Alex009** [comment]
i see that all compiles correctly and lines uncommented in master.
can you describe details of problem? it runtime or compiletime? have any error logs? reproducer?

**Comment by mustafaozhan** [comment]
Hello @Alex009 👋 

Yes i kept it in master for android (since ios is not alive yet)

Now I tested again and I am changing issue title `String key returs if string.xml is too long` to `String are not updated for ios if string.xml is too long`

So the actual issue is during run time, because I checked `build>generated>moko>iosX64>res>Base.Iproj>Localizable.strings` values are updated here.

How to reproduce ?
- Have short `strings.xml` with a test value that you pick
- run ios app, you will see your test value
- go back to `strings.xml` make file longer and change value of your test string, clean build  folder in Android Studio, clean build folder in Xcode, also remove app from ios simulator
- re-run the app from xcode
- you will see in app old string value instead of new one, while `build>generated>moko>iosX64>res>Base.Iproj>Localizable.strings` shows the updated one like how suppose to be.

**Comment by Alex009** [comment]
@mustafaozhan i think problem in some caches of xcode.
please after compilation check resources of generated framework by path `client/build/xcode-frameworks/client.framework/CCC:client.bundle/Contents/Resources/Base.lproj/Localizable.strings`. as i see all generated correct. 

after kotlin compilation of framework to path `client/build/xcode-frameworks/client.framework` xcode got this framework and use for ipa building. you can check what resources used by xcode at `PROJECT_DERIVED_DATA/Build/Products/Debug-iphonesimulator/ios.app/Frameworks/client.framework/CCC:client.bundle/Contents/Resources/Base.lproj/Localizable.strings`

on our project we have 1565 lines in strings file. so here no any problems with size of file.

**Comment by mustafaozhan** [comment]
Hello @Alex009 yes you are right! it is cached in XCode and if I quit and open it is updated. Closing this issue since it is not related to `moko-resources`

**Comment by Alex009** [comment]
i recommend you use cocoapods integration approach as in moko-template. with cocoapods xcode caches invalidates correctly.

**Comment by mustafaozhan** [comment]
Thank you @Alex009 will do that, it seems more straightforward and also I can see that other projects are adapted to cocoapods also
