### ISSUE TITLE
Moko Resources types not exposed via shared module when using 'Hierarchical' CocoaPods setup

### ISSUE THREAD

**Issue by chris-hatton** [icerockdev/moko-resources#158]
When integrating MokoResources; we verified that everything is working correctly, _except_ the ability to directly access Strings from iOS e.g. with:
```
let resource : StringResource = MR.strings().my_string
```
We found that when using the hierarchical CocoaPods setup, MokoResources types aren't being exposed via the shared module (`Cannot find type 'StringResource' in scope`).

**This is confirmed with your MokoResources sample App**, which currently **does not compile**.

Maybe a change in the behaviour of recent KMP/KMM versions has broken this?

**Comment by Alex009** [comment]
sample compiles and works correct.
```
cd sample/ios-app
pod install
open TestProj.xcworkspace
```
then run TestHierarhical target at simulator.

in console will be output:
```
mpp_hierarhical test
```
where `test` is string resource.

to direct access strings you should export dependency to header - https://kotlinlang.org/docs/reference/mpp-build-native-binaries.html#export-dependencies-to-binaries

in sample it's lines:
```
// export correct artifact to use all classes of moko-resources directly from Swift
    targets.withType(org.jetbrains.kotlin.gradle.plugin.mpp.KotlinNativeTarget::class.java).all {
        binaries.withType(org.jetbrains.kotlin.gradle.plugin.mpp.Framework::class.java).all {
            export(project(":resources"))
        }
    }
```
but you should use not `project` type of dependency:
```
targets.withType(org.jetbrains.kotlin.gradle.plugin.mpp.KotlinNativeTarget::class.java).all {
    val libType = when(preset?.name) {
      "iosArm64" -> "-iosarm64"
      "iosX64" -> "-iosx64"
      else -> ""
    }
        binaries.withType(org.jetbrains.kotlin.gradle.plugin.mpp.Framework::class.java).all {
            export("dev.icerock.moko:resources${libType}:${Versions.Libs.MultiPlatform.mokoResources}")
        }
    }
```
something like this.
