### ISSUE TITLE
Cannot access class 'dev.icerock.moko.resources.desc.StringDesc'

### ISSUE THREAD

**Issue by rmdan90** [icerockdev/moko-resources#16]
Hello,
i followed the sample project implementation of this library; but when i try to run android app i get this error.
Cannot access class 'dev.icerock.moko.resources.desc.StringDesc'. Check your module classpath for missing or conflicting dependencies.

**Comment by Alex009** [comment]
hi!
Are you trying to run the sample from the repository or implementing it in your project?
I checked the launch of the sample from the sample directory - everything starts correctly.
Can you attach a build.gradle to issue? Or upload project reproducer to github?

**Comment by rmdan90** [comment]
I'm trying to implement it in my project.



    buildscript {
    ext.kotlin_version = '1.3.61'
    ext.kotlin_native_version = '1.3.41'
    ext.ktor_version='1.2.6'
    ext.coroutines_version='1.3.2'
    ext.kotlinx_coroutines_version='1.3.2'
    ext.serialization_version = '0.14.0'
    ext.localization_version = '0.6.0'
    repositories {
        maven { url 'https://plugins.gradle.org/m2/' }
        maven { url 'https://dl.bintray.com/kotlin/kotlin-eap' }
        maven { url 'https://dl.bintray.com/jetbrains/kotlin-native-dependencies' }
        maven { url 'https://dl.bintray.com/kotlin/ktor' }
        maven { url "https://kotlin.bintray.com/kotlinx" }
        maven { url = "https://dl.bintray.com/icerockdev/plugins" }
        google()
        jcenter()
    }
    dependencies {
        classpath 'com.android.tools.build:gradle:3.5.3'
        classpath "org.jetbrains.kotlin:kotlin-gradle-plugin:$kotlin_version"
        classpath "org.jetbrains.kotlin:kotlin-native-gradle-plugin:$kotlin_native_version"
        classpath "org.jetbrains.kotlin:kotlin-serialization:$kotlin_version"
        classpath "dev.icerock.moko:resources-generator:$localization_version"
    }
 
> And the shared build.gradle

 commonMain.dependencies {
            api 'org.jetbrains.kotlin:kotlin-stdlib-common'
            implementation "io.ktor:ktor-client-core:$ktor_version"
            implementation "org.jetbrains.kotlinx:kotlinx-coroutines-core-common:$coroutines_version"
            implementation "org.jetbrains.kotlinx:kotlinx-serialization-runtime-common:$serialization_version"
            implementation "ch.qos.logback:logback-classic:1.2.3"
            implementation "io.ktor:ktor-client-logging:$ktor_version"
            implementation "dev.icerock.moko:resources:$localization_version"
 } 


` object StringUtils {

    fun getMyString(): StringDesc {
        return StringDesc.Resource(MR.strings.success)
    }

} `

Android call 

`Log.d("testLocalized", getMyString().toString(this))`

**Comment by Alex009** [comment]
You can't access to classes from dependencies of `:shared` module in your `:android-app` module if you use `implementation` configuration in `:shared` module.
Try change `implementation` to `api`.

also `kotlin-native-gradle-plugin` is deprecated, now should be used `org.jetbrains.kotlin.multiplatform` plugin - https://kotlinlang.org/docs/reference/building-mpp-with-gradle.html#setting-up-a-multiplatform-project and moko-resources gradle plugin have integration only with `org.jetbrains.kotlin.multiplatform`

**Comment by rmdan90** [comment]
it works fine now on android in both english and spanish

**Comment by rmdan90** [comment]
It works fine now on android in both English and spanish.
But on iOS simulator it always display the english message, Are there any configuration i'm missing?

**Comment by Alex009** [comment]
Can you show your MR directory structure?
And can you do small sample with reproduction of problem?

**Comment by rmdan90** [comment]
here is the structure of MR
![Screen Shot 2019-12-17 at 9 04 24 AM](https://user-images.githubusercontent.com/16512280/71017977-6f2e7200-20ac-11ea-8507-006a6bb9efcf.png)

**Comment by Alex009** [comment]
It looks correct. I'll try to reproduce the problem at home

**Comment by Alex009** [comment]
i reproduce problem. and on sample project invalid language set not always, but in 70% cases...it's strange. after fix i inform you here

**Comment by Alex009** [comment]
@DevTchernov it's strange behavior of iOS side, your attention needed

**Comment by Alex009** [comment]
@rmdan90 hi! please try to add these code into Info.plist of ios application:
```
	<key>CFBundleLocalizations</key>
	<array>
		<string>en</string>
		<string>es</string>
	</array>
```

**Comment by rmdan90** [comment]
It works like a charm now, Thank you.

**Comment by Alex009** [comment]
info added to readme
