### ISSUE TITLE
Gradle Task 'copyFrameworkResourcesToApp' Does Not Exist

### ISSUE THREAD

**Issue by ge-org** [icerockdev/moko-resources#160]
Hi,

according to the README there should be a Gradle task `copyFrameworkResourcesToApp`. However, it does not exist in my multiplatform project.

I'm using version 0.13.2 of the moko-resources plugin with the following configuration:
```kotlin
multiplatformResources {
    multiplatformResourcesPackage = "com.example.shared"
    iosBaseLocalizationRegion = "en"
}
```

This is the error I get
```
FAILURE: Build failed with an exception.

* What went wrong:
Task 'copyFrameworkResourcesToApp' not found in project ':shared'.
```

**Comment by Alex009** [comment]
hi!
this task not created if ios framework have `isStatic = false` because this logic not required for dynamic framework.
why you think that you should use this task in your case?
