### ISSUE TITLE
Provide an example of plain file resource access

### ISSUE THREAD

**Issue by chris-hatton** [icerockdev/moko-resources#161]
The library claims to handle general/raw files, but there's **no example of this usage** provided.

FYI our use case is to use SVG images with a platform-specific loader; though I'm not requesting special support for that; just an example of general file access.

**Comment by Alex009** [comment]
hi! i agree that example needed.
for now you can use sample lib:
https://github.com/icerockdev/moko-resources/blob/master/sample/mpp-library/src/commonMain/resources/MR/files/test.txt
https://github.com/icerockdev/moko-resources/blob/master/sample/mpp-library/src/commonMain/kotlin/com/icerockdev/library/Testing.kt#L107
and read file on platforms using info from FileResource:
https://github.com/icerockdev/moko-resources/blob/master/resources/src/androidMain/kotlin/dev/icerock/moko/resources/FileResource.kt#L14
https://github.com/icerockdev/moko-resources/blob/master/resources/src/appleMain/kotlin/dev/icerock/moko/resources/FileResource.kt#L19
