### ISSUE TITLE
No MultiPlatformLibraryResources.podspec in release/0.6.0 branch

### ISSUE THREAD

**Issue by An1metall** [icerockdev/moko-resources#17]
Hi!
i receive error with pod update.
> [!] Unable to find a specification for 'MultiPlatformLibraryResources'.

`pod 'MultiPlatformLibraryResources', :git => 'https://github.com/icerockdev/moko-resources.git', :tag => 'release/0.6.0'`

**Comment by Alex009** [comment]
hi! start from 0.6.0 all functions implemented in kotlin, so you not need additional cocoapod now.
