### ISSUE TITLE
Publish to mavenCentral

### ISSUE THREAD

**Issue by ln-12** [icerockdev/moko-resources#170]
Due to [this announcement](https://jfrog.com/blog/into-the-sunset-bintray-jcenter-gocenter-and-chartcenter/) it is necessary to move to mavenCentral.

**Comment by dalewking** [comment]
I assume you are going to do this for the other libraries as well (in particular moko-network). Any chance you can publish some of the slightly older versions of these on maven central as well? We want to get upgraded to the latest but for some reason upgrading to 1.4.31 has not gone well so we are stuck on slightly older versions until we get that sorted out.

**Comment by Alex009** [comment]
old versions will not be published on mavenCental. bintray will be available in readonly mode for year. 

> UPDATE: To better support the community in this migration, JFrog has extended the JCenter new package versions submission deadline through March 31st 2021.
> 
> To clarify, the JCenter repository will keep serving packages for 12 months until February 1st 2022. Only the JCenter REST API and UI will be sunsetted on May 1st 2021.
https://jfrog.com/blog/into-the-sunset-bintray-jcenter-gocenter-and-chartcenter/

**Comment by dalewking** [comment]
OK, thanks for the clarification

**Comment by dalewking** [comment]
Doesn't look like the old versions are available from BinTray. I tried upgrading to 0.13.2 (to get #121) and build fails:

      > Could not resolve dev.icerock.moko:resources:0.13.2.
         > Could not get resource 'https://dl.bintray.com/icerockdev/moko/dev/icerock/moko/resources/0.13.2/resources-0.13.2.pom'.
            > Could not GET 'https://dl.bintray.com/icerockdev/moko/dev/icerock/moko/resources/0.13.2/resources-0.13.2.pom'. Received status code 403 from server: Forbidden

**Comment by Alex009** [comment]
hi @dalewking ! i think readonly mode will be only for jCenter...so here several ways:
1. update moko to mavenCentral versions.
2. publish required version to your own maven
3. use `includeBuild` to use local copy of lib (use tag to download required version)
