### ISSUE TITLE
No reference to StringDesc in commonMain or iosMain

### ISSUE THREAD

**Issue by AndyOHart** [icerockdev/moko-resources#172]
Hi @Alex009 
The library is working fine for androidMain, however I can't reference StringDesc in commonMain or in iosMain. Not sure what is causing this. It seems I can access MR file, but nothing else.

**build.gradle.kts**

```
plugins {
kotlin(Plugins.multiplatform)
id(Plugins.androidLibrary)
kotlin(Plugins.androidExtensions)
id(Plugins.sqlDelight)
kotlin(Plugins.serialization) version Versions.SERIALIZATION_PLUGIN
id(Plugins.ktlint)
id(Plugins.multiplatformResources)
jacoco
maven
}

  kotlin {
      android()

    ios {
        binaries {
            framework {
                baseName = "sharedLib"

                val libType = when (target.preset?.name) {
                    "iosArm64" -> "-iosarm64"
                    "iosX64" -> "-iosx64"
                    else -> ""
                }
                export("dev.icerock.moko:resources$libType:${Versions.MOKO_RESOURCE_GENERATOR}")
            }
        }

    dependencies {
        commonMainApi("dev.icerock.moko:resources:0.15.0")
        commonMainApi("dev.icerock.moko:parcelize:0.5.0")
        commonMainApi("dev.icerock.moko:graphics:0.5.0")
    }

    sourceSets {
        getByName("commonMain") {
            dependencies {
                implementation(Dependencies.KRYPTO)
                implementation(Dependencies.KTOR_CLIENT_CORE)
                implementation(Dependencies.SERIALIZATION_JSON)
                implementation(Dependencies.SERIALIZATION_PROTOBUF)
                implementation(Dependencies.KOTLINX_DATETIME)
                api("dev.icerock.moko:resources:0.15.0")
//                api("dev.icerock.moko:parcelize:0.5.0")
//                api("dev.icerock.moko:graphics:0.5.0")
            }
        }
}

    tasks {
        val debugMode = "DEBUG"
        val mode = System.getenv("CONFIGURATION") ?: debugMode
        val iosArm64Framework = iosArm64().binaries.getFramework(mode)
        val iosX64Framework = iosX64().binaries.getFramework(mode)

        register("universalFramework", org.jetbrains.kotlin.gradle.tasks.FatFrameworkTask::class) {
            baseName = "sharedLib"
            destinationDir = buildDir.resolve("xcode-universal-framework")
            group = "Universal framework"
            description = "Builds a universal (fat) $mode framework"

            from(iosArm64Framework, iosX64Framework)
            dependsOn(iosArm64Framework.linkTask)
            dependsOn(iosX64Framework.linkTask)
        }

        register("universalResourcesFramework", TestFatFramework::class) {
            baseName = "sharedLib"

            val targets = mapOf(
                "iosX64" to kotlin.targets.getByName<KotlinNativeTarget>("iosX64"),
                "iosArm64" to kotlin.targets.getByName<KotlinNativeTarget>("iosArm64")
            )

            from(
                kotlin.iosArm64().binaries.getFramework("RELEASE"),
                kotlin.iosX64().binaries.getFramework("RELEASE")
            )
        }
    }

val packForXcode by tasks.creating(Sync::class) {
    group = "build"
    val mode = System.getenv("CONFIGURATION") ?: "DEBUG"
    val sdkName = System.getenv("SDK_NAME") ?: "iphonesimulator"
    val targetName = "ios" + if (sdkName.startsWith("iphoneos")) "Arm64" else "X64"
    val framework =
        kotlin.targets.getByName<KotlinNativeTarget>(targetName).binaries.getFramework(mode)
    inputs.property("mode", mode)
    dependsOn(framework.linkTask)
    val targetDir = File(buildDir, "xcode-frameworks")
    from({ framework.outputDirectory })
    into(targetDir)
}

tasks.getByName("build").dependsOn(packForXcode)
multiplatformResources {
    multiplatformResourcesPackage = "multiplatformResources"
}

open class TestFatFramework : org.jetbrains.kotlin.gradle.tasks.FatFrameworkTask() {
    @TaskAction
    protected fun copyBundle() {
        super.createFatFramework()

        frameworks.first().outputFile.listFiles()
            ?.asSequence()
            ?.filter { it.name.contains(".bundle") }
            ?.forEach { bundleFile ->
                project.copy {
                    from(bundleFile)
                    into("${fatFrameworkDir.absolutePath}/${bundleFile.name}")
                }
            }
    }
}
```

Inside **sharedLib**, is  directorys for androidMain, commonMain, iosMain etc.
Inside of commonMain I have my kotlin and resources folder.
Inside of kotlin folder I have multiplatformResources folder with a test class. I cannot access StringDesc here. I also cannot access in iosMain.

What could be going wrong?
Also, is it possible to restrict access to these resources in sharedLib, so that Android and iOS test apps cannot access the resources? Basically allow them to be only accessible inside of sharedLib by androidMain and iosMain.
Appreciate any help!

**Comment by Alex009** [comment]
hi!
can you show sample project with this problem? in our samples all works fine and i not see any problems in your build gradle

**Comment by AndyOHart** [comment]
@Alex009 Hey! Unfortunately I cannot share the project as it's an internal thing we are working on.
I see it working on other projects, downloaded a few projects that have it and are working fine, I just cannot figure out what is going wrong.
From looking at some sample projects, the package structure looks like _'commonMain/kotlin/com/example/shared'_,
and then in **build.gradle** they have **multiplatformResourcesPackage = "com.example.shared"**

Whatever way our project was setup, we just have
_'commonMain/kotlin'_ and then all our packages inside of that. I have a feeling that might be the issue?

Is there a way to make it work with that package structure? I'm not sure what our multiplatformResourcesPackage should be in our case. I could be wrong and that may not be the issue! Like I said, It works inside of androidMain, but not iosMain or commonMain.
Also is there a way to block it from working on sample apps? Would be best if they did not have access to the shared resources, we just wanted resources to be shared between the actual shared libs, and not the sample projects.
Thank you, if theres anything else I can provide that would help, let me know!

**Comment by AndyOHart** [comment]
I just took some screenshots of the package structure. Dunno if it helps or not! I do have a feeling maybe the package structure and the **multiplatformResourcesPackage** is the problem. 

<img width="320" alt="1" src="https://user-images.githubusercontent.com/3585474/111029185-22dafa80-83f3-11eb-9721-8081baad65a3.png">
<img width="513" alt="2" src="https://user-images.githubusercontent.com/3585474/111029186-240c2780-83f3-11eb-889f-ed200c3e2b41.png">
<img width="521" alt="3" src="https://user-images.githubusercontent.com/3585474/111029187-24a4be00-83f3-11eb-8d1f-187323b77da9.png">
<img width="521" alt="4" src="https://user-images.githubusercontent.com/3585474/111029188-253d5480-83f3-11eb-91d1-33bceca441a5.png">

**Comment by AndyOHart** [comment]
@Alex009 We seemed to of fixed this, the issue was we were using kotlin-gradle-plugin version 1.4.10.
We updated to 1.4.30 and we were able to access files in commonMain and iosMain.
Might be worth mentioning it on the requirements.
