### ISSUE TITLE
Formatted strings not working correctly

### ISSUE THREAD

**Issue by ln-12** [icerockdev/moko-resources#176]
In the readme [it is stated](https://github.com/icerockdev/moko-resources#example-2---formatted-localization-string) that formatted strings should use single `''` to mark placeholders like in `My format '%s'`. However, this is not working for Android (anymore?). If I start to build the project using such a string placeholder, I get the following error:
```
<path>/shared/build/intermediates/packaged_res/debug/values-de/values-de.xml: Failed to flatten XML for resource 'step_4' with error: Invalid unicode escape sequence in string
"{str}"
<path>/shared/build/intermediates/packaged_res/debug/values-de/values-de.xml: string/step_4 does not contain a valid string resource.
```
I tried to use `""` instead, which works fine under Android, but causes parsing issues under iOS. In this case the iOS would show `step_4` instead of the actual value. I had a look the Android reference [here](https://developer.android.com/guide/topics/resources/string-resource#formatting-strings), which shows that for Android, the placeholder format follows the form `%1$s`. 

Am I using is incorrectly or is an update required to work again?

**Comment by Alex009** [comment]
please compare your code with sample app. in sample used formatted strings too.
`'` not required for formatting, it was just sample string in readme

**Comment by ln-12** [comment]
I got it working now with the `%1$s` style placeholders, thanks.
