### ISSUE TITLE
XCFramework

### ISSUE THREAD

**Issue by AndyOHart** [icerockdev/moko-resources#177]
Hey @Alex009 
Do you know if it is possible to support XCFramework? It is a requirement for us to have this instead of FATFramework, and not sure if it will work.
Cheers

**Comment by Alex009** [comment]
i think xcframework should work, but for now we not have any samples with it

**Comment by AndyOHart** [comment]
@Alex009 would you know how to get it working? Seem to be having trouble copying the bundle successfully

**Comment by ln-12** [comment]
I have the same problem. I am using the [multiplatform-swiftpackage](https://github.com/ge-org/multiplatform-swiftpackage) plugin to generate the XCFramework and get the following error:
```
FAILURE: Build failed with an exception.

* What went wrong:
Task 'copyFrameworkResourcesToApp' not found in project ':shared'.
```

**Comment by AndyOHart** [comment]
@ln-12 Interesting, we are doing ourselves with a gradle task.

`        register("buildXcFrameworkWithResources") {
            dependsOn("deleteXcFramework")
            val mode = "Release"
            val frameworks = arrayOf("iosArm64", "iosX64").map {
                kotlin.targets.getByName<KotlinNativeTarget>(it).binaries.getFramework(mode)
            }

            inputs.property("mode", mode)
            dependsOn(frameworks.map { it.linkTask })
            group = "Universal framework"
            description = "Builds a universal (xc) $mode framework"

            frameworks.first().outputFile.listFiles()
                ?.asSequence()
                ?.filter { it.name.contains(".bundle") }
                ?.forEach { bundleFile ->
                    project.copy {
                        from(bundleFile)
                        into("$xcFrameworkPath/${bundleFile.name}")
                    }
                }

            doLast {
                val buildArgs: () -> List<String> = {
                    val arguments = mutableListOf("-create-xcframework")
                    frameworks.forEach {
                        arguments += "-framework"
                        arguments += "${it.outputDirectory}/${project.name}.framework"
                    }
                    arguments += "-output"
                    arguments += xcFrameworkPath
                    arguments
                }

                exec {
                    executable = "xcodebuild"
                    args = buildArgs()
                }
            }
        }`

You can see I tried to copy the bundle. It seems the bundle is there in the build folder in the xcframework but It seems to crash the app when it is accessed on the iOS side

**Comment by ln-12** [comment]
@AndyOHart Thanks for your script. The task comes from this issue: https://github.com/icerockdev/moko-resources/issues/135

Did you access the resources like described [here](https://developer.apple.com/documentation/swift_packages/bundling_resources_with_a_swift_package)?

**Comment by ln-12** [comment]
I got it working now. First, I thought the `copyFrameworkResourcesToApp` was related to your question, so I looked into the generated framework. There, I could see that all needed resources are already present, so I removed the `copyFrameworkResourcesToApp` task to get it working.

Simply follow the instructions for the [multiplatform-swiftpackage plugin](https://github.com/ge-org/multiplatform-swiftpackage) and you are good to go :)

**Comment by AndyOHart** [comment]
@ln-12 Ah I see.
The way we did it was with a buildFatFrameworkWithResources task that we had in gradle.

`        register("buildFatFrameworkWithResources", TestFatFramework::class) {
            val debugMode = "DEBUG"
            val mode = System.getenv("CONFIGURATION") ?: debugMode
            baseName = "sharedTestLib"
            destinationDir = buildDir.resolve("xcode-universal-framework")
            group = "Universal framework"
            description = "Builds a universal (fat) $mode framework"

            val targets = mapOf(
                "iosX64" to kotlin.targets.getByName<KotlinNativeTarget>("iosX64"),
                "iosArm64" to kotlin.targets.getByName<KotlinNativeTarget>("iosArm64")
            )

            from(
                kotlin.iosArm64().binaries.getFramework("RELEASE"),
                kotlin.iosX64().binaries.getFramework("RELEASE")
            )
        }`

`open class TestFatFramework : org.jetbrains.kotlin.gradle.tasks.FatFrameworkTask() {
    @TaskAction
    protected fun copyBundle() {
        super.createFatFramework()

        frameworks.forEach {
            it.outputFile.listFiles()
                ?.asSequence()
                ?.filter { it.name.contains(".bundle") }
                ?.forEach { bundleFile ->
                    project.copy {
                        from(bundleFile)
                        into("${fatFrameworkDir.absolutePath}/${bundleFile.name}")
                    }
                }
        }
    }
}`

This fat framework build correctly and we were able to run the app on iOS with no problem. Basically I had a logger in iosMain that logged a string from the shared Strings file. When fatFramework was built, it worked and logged in Xcode terminal fine, however with xcframework, it crashed saying couldn't find commonMain/MR.

**Comment by AndyOHart** [comment]
> I got it working now. First, I thought the `copyFrameworkResourcesToApp` was related to your question, so I looked into the generated framework. There, I could see that all needed resources are already present, so I removed the `copyFrameworkResourcesToApp` task to get it working.
> 
> Simply follow the instructions for the [multiplatform-swiftpackage plugin](https://github.com/ge-org/multiplatform-swiftpackage) and you are good to go :)

Oh you got it working? So right now when you use XCFramework, the resources are there and you can reference strings etc successfully from iosMain and it works? So I should probably use that library instead of our own task perhaps?

**Comment by ln-12** [comment]
Yes, I use localized strings from the package and it's super easy!

Here's a short explanation:
1. Follow the [instructions of the plugin](https://github.com/ge-org/multiplatform-swiftpackage)
2. Run `./gradlew createSwiftPackage`
3. If everything worked, you get an output like the following on the terminal: 
```
> Task :shared:createXCFramework
xcframework successfully written out to: /path/to/your/project/shared/swiftpackage/shared.xcframework
```
4. Add the framework inside XCode (you need to init a new git repo, see [here](https://forums.swift.org/t/how-to-add-local-swift-package-as-dependency/26457/4))
5. Use your shared lib as before, in my example I need to `import shared` and can use string resources like this (for the extension, see [here](https://github.com/icerockdev/moko-resources/issues/128):
```
Text(MR.strings().error.localized())
```

I hope this helps :)

**Comment by AndyOHart** [comment]
@ln-12  Appreciate that thanks! Just some questions.
I have integrated that plugin, seems to work fine.
You say to run createSwiftPackage first, but the output would be "xcframework successfully written out to: /path/to/your/project/shared/swiftpackage/shared.xcframework". Did you mean to say run createXCFramework instead of createSwiftPackage?

Also I'm not sure I follow what you mean about init a new git repo. We already have our ios app working correctly with kotlin multiplatform, previously I just ran the buildFatFramework task and the resources etc were working on ios, the problem is now it isn't with the XCFramework.
Hope this makes sense

**Comment by AndyOHart** [comment]
@ln-12 Previously in XCode we had
![image](https://user-images.githubusercontent.com/3585474/112352804-01b3bd00-8cc3-11eb-84e8-416a3dfa7843.png)

This built our fatFramework when building iOS, since we will not use fatFramework I changed it to be the xcFramework. Still seems to crash: 
"Uncaught Kotlin exception: kotlin.IllegalArgumentException: bundle with identifier commonMain.MR not found"

Really not sure whats causing the bundle to not work

**Comment by ln-12** [comment]
> @ln-12 Appreciate that thanks! Just some questions.
> I have integrated that plugin, seems to work fine.
> You say to run createSwiftPackage first, but the output would be "xcframework successfully written out to: /path/to/your/project/shared/swiftpackage/shared.xcframework". Did you mean to say run createXCFramework instead of createSwiftPackage?

No, as you can see from the readme, the task is `./gradlew createSwiftPackage`. It creates the framework and packs it into the swift package.

> Also I'm not sure I follow what you mean about init a new git repo. We already have our ios app working correctly with kotlin multiplatform, previously I just ran the buildFatFramework task and the resources etc were working on ios, the problem is now it isn't with the XCFramework.

It seems like you need to create a git repo in the root of the swift package for Xcode to work.

I removed all build scripts from Xcode which i had to add before. Be sure to add the swift package, not just the framework.

**Comment by AndyOHart** [comment]
@ln-12 Okay so I did that and I end up with the xcframework, Package.swift, and a zip file of the library.
What way are you adding the swift package? In link binary with libraries menu? That's what I was doing and clicking Add Files and selecting the swiftpackage folder that the ./gradlew createSwiftPackage created.

**Comment by ln-12** [comment]
Exactly. Regarding the path from above, I add the folder in which these file are, like `file:///path/to/your/project/shared/swiftpackage/`, into the XCode text field. `swiftpackage` contains the files you mentioned.

**Comment by AndyOHart** [comment]
So you add it via "Add Package Dependency" menu?
Doesn't seem to work for me. Yeah doesn't seem to be any references I deleted the framework before I ran the createSwiftPackage command.
Is doing the git repo really needed for a local lib? Seems strange. It's also odd because the project seems to build in XCode but crashes due to the commonMain/MR error.

Really not sure what I'm missing

**Comment by ln-12** [comment]
I don't know but without the new git repo, XCode doesn't find the package in my case.

Did you look at this? https://github.com/icerockdev/moko-resources/issues/173

**Comment by AndyOHart** [comment]
Weird, I guess I will try that approach. Yeah I saw it, sounds like a similar issue but my shared modules build.gradle has the moko resources setup fine, like I said it works with fatFramework, just not XC. It's also odd since I see the XC framework has the resources there but just seems to crash

**Comment by wlghdu97** [comment]
@AndyOHart  If you're having "bundle with identifier com.example.app.MR not found" issue with swift package, add your shared package to Build Phases -> Copy Bundle Resources.
<img width="335" alt="Screen Shot 2021-05-11 at 5 48 38 PM" src="https://user-images.githubusercontent.com/54768761/117792077-e9552d00-b285-11eb-869c-a4646be233e3.png">

**Comment by iruizmar** [comment]
Hey! 👋🏻 For now I've been able to fix this by using your trick, @wlghdu97 but I'm worried about what you say about the app store. Have you found any final solution?

**Comment by Alex009** [comment]
we have not tried yet to use xcframeworks, but now have plans to test this and add support

**Comment by Alex009** [comment]
guide how to use xcframeworks added to readme of 0.18.0 release.
problem with appstore from https://github.com/icerockdev/moko-resources/issues/177#issuecomment-838150959 was because all xcframework was added to bundle. In 0.18.0 you can use special gradle task for static frameworks inside xcframework (see readme after release)
