### ISSUE TITLE
Using common fonts in Jetpack Compose

### ISSUE THREAD

**Issue by hlnstepanova** [icerockdev/moko-resources#180]
Hi, I added some fonts to resources to common module in a project using Jetpack Compose
<img width="246" alt="image" src="https://user-images.githubusercontent.com/12126043/112483954-caecae00-8d79-11eb-85ad-6bd0e2b43ab8.png">

I see generated data in MR, but can't figure out how to use them in my Typography. I tried like this, but every option is unresolved:
<img width="415" alt="image" src="https://user-images.githubusercontent.com/12126043/112484325-20c15600-8d7a-11eb-9e2a-c4ff58d835f5.png">

Is it possible to use common fonts in Jetpack Compose? If so, what am I missing out?

**Comment by Alex009** [comment]
jvm support not implemented yet. see #159 for details

**Comment by moffpage** [comment]
On the other hand, I had no problems (yet) resolving my fonts from core module (see screenshots below):
<img width="589" alt="image" src="https://user-images.githubusercontent.com/33549573/126030020-fb1389ea-f9c3-4a2b-85a6-f62963a3bb00.png">
However, `Font(...)` factory function requires `resId` of type Int to be passed as an argument, but **FontResource**'s actual implementation in **androidMain** has private access of property `fontResourceId`:
<img width="808" alt="image" src="https://user-images.githubusercontent.com/33549573/126030087-794ba841-bfbf-4bfe-b2fb-0f246c50f516.png">
I ask IceRock team to change this property access modifier to be public instead. Thanks for your development!

**Comment by Alex009** [comment]
`fontResourceId` can be accessed starts from 0.16.2 
https://github.com/icerockdev/moko-resources/pull/221
