### ISSUE TITLE
BIN file support

### ISSUE THREAD

**Issue by AndyOHart** [icerockdev/moko-resources#182]
Hey, is it possible to support BIN files? If we need to use BIN files for something how can we work with these?
Thanks

**Comment by Alex009** [comment]
hi! you can just put any file in `commonMain/resources/files` and read it in runtime. but for reading you should implement own expect/actual function with input type `FileResource`. moko-resources gradle plugin will put your file into correct directory for ios and android, but not give implementation for reading this format
