### ISSUE TITLE
CDATA tag doesn't work as expected on iOS

### ISSUE THREAD

**Issue by romanandreyvich** [icerockdev/moko-resources#183]
I'm trying to use CDATA tag in multiplatform string resources but it doesn't work as expected on iOS platform.

Example

I have a string:
`<string name="some_key">There is a <a href="some_link">link</a></string>`

To escape html/quotes in this string I'm trying to use CDATA tag:
`<string name="some_key"><![CDATA[There is a <a href="some_link">link</a>]]></string>`

What I expect to see on both platforms (iOS & Android):
`There is a <a href=\"some_link\">link</a>`

It works well on Android. 

On iOS it looks like:
`There is a <a href="some_link">link</a>`

So all resources are broken. I expect that all quotes should be escaped, as it works on Android.

**Comment by Alex009** [comment]
not reproduced. fixed in #174
