### ISSUE TITLE
Plural formatting crashes when using `vararg` arguments.

### ISSUE THREAD

**Issue by MatyasKriz** [icerockdev/moko-resources#185]
Hey there, my colleague found a bug when using plurals in a Kotlin Native project.

To keep this short, using the `format` method from **Example 4 - plural formatted string** from README crashes:
```
MR.plurals.my_plural.format(quantity, quantity)
```

On the other hand, using a list works just fine:
```
MR.plurals.my_plural.format(quantity, listOf(quantity))
```

Just wanted to let you know, happy debugging!

**Comment by Alex009** [comment]
will be available in 0.16.0
