### ISSUE TITLE
MavenCentral 0.15.1

### ISSUE THREAD

**Issue by pfaffenrodt** [icerockdev/moko-resources#188]
Today was 0.5.1 released to mavenCentral? 

I can not find any artifacts there

**Comment by Alex009** [comment]
it's not released. see https://github.com/icerockdev/moko-resources/releases

**Comment by Alex009** [comment]
and now it released and available :)
https://github.com/icerockdev/moko-resources/releases/tag/release%2F0.15.1

**Comment by pfaffenrodt** [comment]
@Alex009 thanks

**Comment by dalewking** [comment]
Still not showing on maven central yet, but I'm sure it will be shortly

**Comment by Alex009** [comment]
@dalewking release at github was published only after showing at https://repo1.maven.org/maven2/dev/icerock/moko/ :)
