### ISSUE TITLE
dev.icerock.gradle.generator.EqualStringKeysException: Can't process keys which equals their value: "or"

### ISSUE THREAD

**Issue by DeltAagent00** [icerockdev/moko-resources#189]
`<string name="or">or</string>`

error generation

**Comment by Alex009** [comment]
This is a special protection. On iOS you can have partial localizations of specific languages with a fallback to the base localization on non-localized keys.

If in a specific Russian locale, when we request the "or" key, we receive a value corresponding to this key, then this key is not supported in the locale and must be taken with base
