### ISSUE TITLE
How to access MK strings from Layout xml file

### ISSUE THREAD

**Issue by tringkishorekumar** [icerockdev/moko-resources#201]
Hi,
I need to access MK.strings from layout xml file. I am not sure how to do that

**Comment by Alex009** [comment]
hi!

first - we have no `MK` strings :) we have `MR` class. second - access to resources from xml can be done not with `MR` but with `R`. our generator generate android resources that used in `MR` class too, so after call `generateAndroidResources` gradle task you can just call `R` resource in layouts

**Comment by Nailik** [comment]
Actually there is a better way to use the strings than with the generated R class.
In Android language switching while the App is open can be awful (different behaviors across api levels etc etc) and with moko StringDesc you just need to set StringDesc.localType.

So i searched a way how to use it in xml, here is my solution:

Create a Strings object (in android Main) to have access to the generated class and to translate it to Android Strings 

```
object Strings {
    fun getString(stringRes: StringResource, context: Context) : String {
        return StringDesc.Resource(stringRes).toString(context)
    }

    val res : MR.strings = MR.strings
}
```

Create a databinding variable

```
<variable
            name="text"
            type="com.example.Strings" />
```

set value of variable in you activity/fragment   ` binding.text = Strings`

and now you can use it as follow: `android:text="@{text.getString(text.res.my_string, context)}"`

And switching languages is also super easy, by changing localeType like so:
`StringDesc.localeType = StringDesc.LocaleType.Custom("somelanguage")` and then you have to refresh all bindings on the currently opened Fragment/Activity by calling it with the eventsDispatcher and on Android Side you make `binding.invalidateAll()`

This way you can bind the moko StringResource, use moko to change language and jeah that's it.
