### ISSUE TITLE
Internationalization just works on Android app, on iOS it keep every text in english

### ISSUE THREAD

**Issue by joavilati** [icerockdev/moko-resources#202]
Hi! I am starting to develop the ios ui on my kotlin multiplatform project. I have been using the moko resource library for strings and internationalization., on Android application works fine but on ios the app ignore the simulator settings and bind the strings in english.

build.gradle:

![image](https://user-images.githubusercontent.com/48884950/119417317-ea497e00-bccb-11eb-95ab-0ddea3be1058.png)
![image](https://user-images.githubusercontent.com/48884950/119417335-f6354000-bccb-11eb-9b24-6b2e1bee05f0.png)
![image](https://user-images.githubusercontent.com/48884950/119417385-15cc6880-bccc-11eb-848c-cd31da8368cc.png)

this is how i get the string on ios:

`LoginLabel.Companion().upperLoginLabel.localized()`

this is how i create the StringDesc on common file:

`val upperLoginLabel = getStringDesc(MR.strings.login_title_label)`

![image](https://user-images.githubusercontent.com/48884950/119411234-705fc780-bcc0-11eb-9af5-ba215e4417ed.png)

![image](https://user-images.githubusercontent.com/48884950/119410241-eb27e300-bcbe-11eb-8153-26cfa1d83a70.png)
Obs: for some reason i am failing to format the code, so to be more  understandable i inserted some screenshot, if confuse more than helps, please let me know.

**Comment by Alex009** [comment]
hi! did you setup ios project as was in readme.md?
![image](https://user-images.githubusercontent.com/5010169/119462451-f1739900-bd6a-11eb-9e4d-42e5f70b5cfd.png)

**Comment by joavilati** [comment]
Sorry for spend your time, i had seen 10 times the readme but i couldn't find this part, sorry again.
