### ISSUE TITLE
Support Kotlin's Explicit API compiler feature

### ISSUE THREAD

**Issue by moffpage** [icerockdev/moko-resources#203]
Hi! Could you please provide support for Kotlin compiler's Explicit API (strict) feature? I don't really know how could it be integrated in the way that it's gonna give a possibility to have both **internal** and _public_ objects and constants generated from the script / task, because generated code should not be edited.
Thanks for your contribution to KMM!

**Comment by Alex009** [comment]
will be available in 0.18.0
