### ISSUE TITLE
Image resources from iosMain is not available in iOS framework

### ISSUE THREAD

**Issue by romanandreyvich** [icerockdev/moko-resources#204]
I have some image resources that should be presented in my iOS app and shouldn't in android app.

The issue is: 

I add a resource to iosMain/resources/MR/images/ but it is not available in my iOS project.

Expected behaviour:
`MR.images.getImageByFileName("my_resource")` - returns my image resource from iosMain

Actual behaviour: 
`MR.images.getImageByFileName("my_resource")` - returns null

Environment:
Moko-resources 0.13.0
Kotlin 1.4.31
Android studio 4.2

**Comment by Alex009** [comment]
hi! we have not thought about such use-case, but thanks for the idea - we will implement it in the future

**Comment by krottv** [comment]
@Alex009 I have also faced this kind of use case. As a workaround I can put a file into my ios project, but it is less convenient

**Comment by Alex009** [comment]
in #575 implemented logic with support of resources in each sourceset

**Comment by ExNDY** [comment]
will be fixed in 0.24.0, please check in 0.24.0-alpha-6

**Comment by Alex009** [comment]
fixed in 0.24.0-beta-1
