### ISSUE TITLE
Issue on iOS when using regular framework (no cocoapods)

### ISSUE THREAD

**Issue by ydemartino** [icerockdev/moko-resources#209]
Hello, I am trying to use your library on a KMM project.

It is working really good on android, but I have some issue on iOS. My project is not using cocoapods, when creating a new project from the KMM plugin, I chose "Regular framework" for the iOS framework distribution option.

When I am on XCode I have almost the same issue described here: https://github.com/icerockdev/moko-resources/issues/181
Except on my side this is working fine:
```swift
MR.strings().login.desc().localized()
// Works but only display strings in the base language
```

But this isn't working:
```swift
MR.strings.login.desc().localized()
// Instance member 'login' cannot be used on type 'MR.strings'; did you mean to use a value of this type instead?
```

Here is an extract from my build.gradle.kts

```gradle
plugins {
    kotlin("multiplatform")
    kotlin("plugin.serialization")
    id("com.android.library")
    id("dev.icerock.mobile.multiplatform-resources")
}

kotlin {
   // ...
    iosTarget("ios") {
        binaries {
            framework {
                baseName = "shared"
                export(Moko.resources) // Before adding this I had the exact same issue as #181 
            }
        }
    }
    sourceSets {
        val commonMain by getting {
            dependencies {
                api(Moko.resources)
               // ...
           }
      }
  }
  // ...
}

multiplatformResources {
    multiplatformResourcesPackage = "com.test.app.shared" // I am not sure if this key has any use?
}

val packForXcode by tasks.creating(Sync::class) {
    val mode = System.getenv("CONFIGURATION") ?: "DEBUG"
    val framework = kotlin.targets.getByName<KotlinNativeTarget>("ios").binaries.getFramework(mode)
    val targetDir = File(buildDir, "xcode-frameworks")

    group = "build"
    dependsOn(framework.linkTask)
    inputs.property("mode", mode)

    from({ framework.outputDirectory })
    into(targetDir)
}

tasks.getByName("build").dependsOn(packForXcode)
```

I have correctly set the Info.plist in xcode and here is the script from the build phase:
```bash
cd "$SRCROOT/.."
./gradlew :shared:packForXCode -PXCODE_CONFIGURATION=${CONFIGURATION}
```

Can you please tell me what I am missing?
Thank you

**Comment by Alex009** [comment]
from swift side you should use `MR.strings().login.desc().localized()` construction.
`MR.strings()` - read inner object `strings` of `MR` class (access to singleton)
`login` - read property of `strings` object
`desc()` - call extension function `desc` to create `StringDesc` from `StringResource`
`localized()` - call function of getting localized string from `StringDesc`

also by default framework is static, so you should add static framework support as described in readme https://github.com/icerockdev/moko-resources#static-kotlin-frameworks-support
or change framework to dynamic in build gradle

**Comment by ydemartino** [comment]
Thanks for your answer.

It seems by default frameworks are dynamic: https://github.com/JetBrains/kotlin/blob/master/libraries/tools/kotlin-gradle-plugin/src/main/kotlin/org/jetbrains/kotlin/gradle/targets/native/NativeBinaries.kt#L271

I tried to force isStatic to false but I had the same issue.

I tried to add the `:shared:copyFrameworkResourcesToApp` build phase but it is failing because I am not using the `org.jetbrains.kotlin.native.cocoapods` plugin.

Any idea how I can make this works without the `native.cocoapods` plugin and with dynamic framework?

Thank you

**Comment by Alex009** [comment]
```
MR.strings().login.desc().localized()
// Works but only display strings in the base language
```

result of this call is string from base localization? not just key?
if yes - resources bundle correctly found. and if you got not valid language - check ios-app pList file - you should write all languages in this file as described here https://github.com/icerockdev/moko-resources#installation

**Comment by ydemartino** [comment]
I confirm
```
MR.strings().login.desc().localized()
// This is giving me the correct string from base language but not from the language of my phone
```

On the other hand, in my SwiftUI code if I try to use
```
Text(LocalizedStringKey(MR.strings().no_account_yet.resourceId))
// This is giving me the raw key "no_account_yet" instead of the base/localized one
```

Here is what my Info.plist looks like:
![Capture d’écran 2021-06-22 à 08 31 56](https://user-images.githubusercontent.com/3692818/122875266-51426d00-d334-11eb-8f33-f11125166efa.png)

And here is what my shared library looks like:
![Capture d’écran 2021-06-22 à 08 32 45](https://user-images.githubusercontent.com/3692818/122875355-6e773b80-d334-11eb-927b-4327ff97240f.png)

**Comment by Alex009** [comment]
You try read resource from invalid bundle. You should use bundle from `StringResource` class

**Comment by Alex009** [comment]
About base localization - please create small sample project on GitHub and give to us

**Comment by ydemartino** [comment]
Sorry it seems I had some cache somewhere that was giving these wrong resources.
I tried to create a small sample project but everything was working there.

I cleaned my main project and tried again and it's working now.

Thank you for your help
