### ISSUE TITLE
Access a resource by string name

### ISSUE THREAD

**Issue by krottv** [icerockdev/moko-resources#218]
That is more convenient in some cases. In Android I place my resources in assets directory where I can access them by path. Is it possible to do for multiplatform?

**Comment by Alex009** [comment]
hi!
at now we support getting by name only for images - https://github.com/icerockdev/moko-resources/blob/master/resources/src/commonMain/kotlin/dev/icerock/moko/resources/ResourceContainer.kt#L9
but you can convert this issue to feature-request and it will be implemented later (on you can implement this just like for images already done, and send pull request to us - it will be faster that wait our schedule)

**Comment by krottv** [comment]
@Alex009 
I think that It would be nice to use different approach: in shared module we can orginize our files with directories structure.

Then by the resource generator we move those files to android asset folder. 
And for IOS we generate names like folder1_folder2_folder3_filename.ext

And we also would have common function to get platform path from string.

**Comment by Alex009** [comment]
@krottv why request was closed? you found another way?

**Comment by krottv** [comment]
@Alex009 
I've implemented it here https://github.com/icerockdev/moko-resources/pull/233

**Comment by Alex009** [comment]
will be available in 0.18.0
