### ISSUE TITLE
Issue with line break and auto formatting from the IDE

### ISSUE THREAD

**Issue by ydemartino** [icerockdev/moko-resources#238]
Hello, I noticed an issue with the strings.xml file when the line goes past the 100 characters limit.

What happens, is that I type my string like this:
```
    <string name="long_string">This is a super long string that goes past the 100 characters long and it will be automatically wrapped by the IDE</string>
```

And then it gets auto formatted by the IDE like this:
```
    <string name="long_string">This is a super long string that goes past the 100 characters long
        and it will be automatically wrapped by the IDE
    </string>
```

This is working fine on standard android project, but here is the generated multiplarform_strings.xml:
```
	<string name="long_string">This is a super long string that goes past the 100 characters long\n        and it will be automatically wrapped by the IDE\n    </string>
```

It adds hard line break and my text is now split across multiple lines... I think, the transformation to multiplatform_strings.xml should not add any \n. In strings.xml if we want to add an explicit line break, we need to use \n. The generation should keep the string as it was typed.

**Comment by Alex009** [comment]
line break added because new line found :) i think this issue resolve by IDE configuration, but not plugin changes

**Comment by ydemartino** [comment]
I understand what you are saying, I think this is a shame because then, we cannot reuse raw android files with moko resources...

**Comment by Alex009** [comment]
@y9san9 here should be added new `gradle.properties` property for toggl new and old behaviour.
