### ISSUE TITLE
iosSimulatorArm64 and macOsArm64 support

### ISSUE THREAD

**Issue by TadeasKriz** [icerockdev/moko-resources#248]
With the release of Kotlin 1.5.30 we can finally target the iOS Simulator and macOS running on Apple Silicon. Do you have plans to include these targets? Thank you!

**Comment by Reedyuk** [comment]
@Alex009 - any update with this? would be good to have this as i'm thinking of using it on a big project.

**Comment by Alex009** [comment]
@Reedyuk no updates yet. you can contribute this changes.
or we will implement it somewhere in nov-dec. no time for this now

**Comment by EstevaoST** [comment]
Just passing by to say I'm also interested on this update. I will be rooting for you.

**Comment by lschiavini** [comment]
@Alex009  any news so far on this?

**Comment by Alex009** [comment]
Updates planned at start of January

**Comment by lschiavini** [comment]
> Updates planned at start of January

Is there anything we could do to help release this feature faster?

**Comment by Alex009** [comment]
Apple Silicon targets will be available in 0.18.0 release
