### ISSUE TITLE
Can't use plugin without Android Gradle Plugin (clean Compose for Desktop usage)

### ISSUE THREAD

**Issue by Alex009** [icerockdev/moko-resources#252]
![image](https://user-images.githubusercontent.com/5010169/136672524-10ac3e9c-ace2-451a-b6a4-635f73d469ad.png)

**Comment by chris-hatton** [comment]
Came here to look for this; I would love to be able to use MokoResources with my Multiplatform project which incorporates Android, iOS and Desktop (where Android and Desktop share Compose Multiplatform).  Specifically I am looking to MokoResources to provide some kind of string resource & localisation capability for Desktop part.

**Comment by vasya-polyansky** [comment]
Is there any progress on this issue? What can I do to fix it? I would like to use the resources generation in a jvm app

**Comment by r4zzz4k** [comment]
I've mentioned that you cannot avoid this issue in #260, but @vlsi corrected me and provided quite simple solution. You can avoid validation of the class if you don't access it explicitly. Citing [Chapter 5 of JVMS](https://docs.oracle.com/javase/specs/jvms/se7/html/jvms-5.html),

> If a user-defined classloader prefetches binary representations of classes and interfaces, or loads a group of related classes together, then it must reflect loading errors only at points in the program where they could have arisen without prefetching or group loading.

So if I understand everything correctly, it should be enough to move mention of `BaseExtension` to the separate class, which you access only within `withPlugin(...) { ... }` body.

**Comment by vlsi** [comment]
> So if I understand everything correctly, it should be enough to move mention of BaseExtension to the separate class, which you access only within withPlugin(...) { ... } body.

That would work indeed.
In other words, the rule of thumb is "if `BaseExtension` is an optional class, then avoid using the class in the method signatures (including private methods), in superclasses, in field types, etc"

However, it might be a good idea to split the plugin into several ones. Several plugins can be a part of the same jar if you like, and some plugins can even be "technical" (== not applied explicitly by the end-users), however, splitting plugins helps to segregate concerns.
See https://docs.gradle.org/current/userguide/designing_gradle_plugins.html#capabilities-vs-conventions re `Java Base plugin`

**Comment by Alex009** [comment]
start from 0.17.3 you can use moko-resources without android gradle plugin. but you still should use kotlin multiplatform plugin

**Comment by Alex009** [comment]
usage without kotlin multiplatform plugin will be implemented sometimes in #263

**Comment by vasya-polyansky** [comment]
> start from 0.17.3 you can use moko-resources without android gradle plugin. but you still should use kotlin multiplatform plugin

That's great, looking forward to see #263 resolved :)
