### ISSUE TITLE
copyFrameworkResourcesToApp fails if using custom Xcode configuration

### ISSUE THREAD

**Issue by brendangoldberg** [icerockdev/moko-resources#258]
As of Kotlin 1.5.31, we're now able to map custom XCode Configurations e.g. "Stage" through the native cocoapods extension i.e.
```kotlin
kotlin {
    cocoapods {
        xcodeConfigurationToNativeBuildType["Stage"] = NativeBuildType.RELEASE
    }
}
```
Attempting to build for the "Stage" configuration we run into this error:
```gradle
* What went wrong:
Execution failed for task ':Common:copyFrameworkResourcesToApp'.
> 
  framework link task with konanTarget ios_arm64, platform iphoneos and buildType stage not found!
```

I believe the issue can be found here: https://github.com/icerockdev/moko-resources/blob/master/resources-generator/src/main/kotlin/dev/icerock/gradle/generator/apple/AppleMRGenerator.kt#L235
```kotlin
if (framework.target.konanTarget == xcodeTask.konanTarget &&
            framework.buildType.getName() == xcodeTask.configuration
        ) {
            xcodeTask.dependsOn(copyTask)
        }
```
which fails to link xCodeTask to copyTask since
```
framework.buildType.getName() == xcodeTask.configuration
```
is `false` in this case (Release != Stage)

Reference material for mapping custom XCode Configurations can be found here --> https://kotlinlang.org/docs/native-cocoapods.html#install-the-cocoapods-dependency-manager-and-plugin.

**Comment by brendangoldberg** [comment]
Worth noting, here is my Build Phase script:
```sh
"$SRCROOT/../gradlew" -p "$SRCROOT/../" :Common:copyFrameworkResourcesToApp \
    -Pmoko.resources.PLATFORM_NAME=$PLATFORM_NAME \
    -Pmoko.resources.CONFIGURATION=$CONFIGURATION \
    -Pmoko.resources.BUILT_PRODUCTS_DIR=$BUILT_PRODUCTS_DIR \
    -Pmoko.resources.CONTENTS_FOLDER_PATH=$CONTENTS_FOLDER_PATH\
    -Pkotlin.native.cocoapods.platform=$PLATFORM_NAME \
    -Pkotlin.native.cocoapods.configuration=$CONFIGURATION \
    -Pkotlin.native.cocoapods.cflags="$OTHER_CFLAGS" \
    -Pkotlin.native.cocoapods.paths.headers="$HEADER_SEARCH_PATHS" \
    -Pkotlin.native.cocoapods.paths.frameworks="$FRAMEWORK_SEARCH_PATHS"
```

**Comment by nuron142** [comment]
I am also facing the same issue

**Comment by Alex009** [comment]
will be available in 0.17.4

**Comment by iruizmar** [comment]
Hey 👋🏻  @Alex009 
Sorry to necro this. I'm facing this same issue but I'm not using `Cocoapods` to consume my KMM module so I don't have access to `xcodeConfigurationToNativeBuildType`.
Can we specify the mapping somehow without depending on that?
Check this to find how I'm doing it for other stuff:
https://youtrack.jetbrains.com/issue/KT-48024/New-embedAndSignAppleFrameworkForXcode-task-does-not-work-with-XCode-UI-tests

**Comment by darronschall** [comment]
@iruizmar If you have `KOTLIN_FRAMEWORK_BUILD_TYPE ` set to "debug" or "release" in your Xcode User-Defined Settings, then change the configuration in the build phase script from this:

```
-Pmoko.resources.CONFIGURATION="$CONFIGURATION" \
```

to this:

```
-Pmoko.resources.CONFIGURATION="$KOTLIN_FRAMEWORK_BUILD_TYPE" \
```
