### ISSUE TITLE
Feature Request: MR naming possibility

### ISSUE THREAD

**Issue by iamthevoid** [icerockdev/moko-resources#267]
In multimodule project there are many MR's can be generated.

If i try to call they from swift i stuck into naming problem. Interop make `MR`, `MR_`, `MR__` ... from they

It is too bad for using in production, because it is impossible to predict what name new MR from another module will get.

For example If i use 100 strings from `MR`, 50 from `MR_` in Swift code nobody can garauntee that new module MR wont't became `MR` or `MR_` and old code breaks.

At the time it can be solved with typealiases, but looks like it should be part of library logic

**Comment by Alex009** [comment]
will be available in 0.18.0
