### ISSUE TITLE
Support Kotlin/JS

### ISSUE THREAD

**Issue by Intektor** [icerockdev/moko-resources#272]
Is there a specific reason or issue stopping support for Kotlin/JS? 
I think, especially moving forward into Multiplatform UI this library has great potential.

Otherwise I'd look into creating a pull request with Kotlin/JS support.

**Comment by Alex009** [comment]
no reasons to not support this target :) it's just should be implemented by someone. if you can - do it and create pull request

**Comment by Alex009** [comment]
will be available in 0.19.0
