### ISSUE TITLE
Use Resources in Common Composition 

### ISSUE THREAD

**Issue by ynsok** [icerockdev/moko-resources#306]
Hi, 

I have a project where all compositions are shared between platforms(android, desktop). They are kept in `commonMain` module. The problem of course is how to maintain resources(strings, dimension, colors, etc.) in one single place.  Is it possible with `moko-resources` to get resources and use them in `commonMain`

**Comment by sproctor** [comment]
I believe I'm having a similar issue. MOKO is generating files for commonMain and androidMain, but not desktopMain. I'm not sure what the solution is.

**Comment by Alex009** [comment]
moko resources already supports compose for android desktop and web. you can share resources in commonMain and use it there.
