### ISSUE TITLE
Add composable extensions

### ISSUE THREAD

**Issue by y9san9** [icerockdev/moko-resources#308]
For Compose in android we have LocaleContext and we can use it:

```kotlin
// android and jvm
@Composable
expect fun StringDesc.localized(): String

// android 
@Composable
actual fun StringDesc.localized(): String = localized(LocalContext.current)

// jvm
@Composable
expect fun StringDesc.localized(): String = localized()
```

**Comment by galdp** [comment]
@y9san9 Your looking for https://github.com/icerockdev/moko-resources/blob/master/resources-compose/src/androidMain/kotlin/dev/icerock/moko/resources/compose/StringResource.kt

**Comment by galdp** [comment]
@y9san9 well it is, just not an extension function. You could fork and provide icerockdev an PR

**Comment by y9san9** [comment]
So, as IceRock employee, I probably will do that after I finish my current task with JS platform for the library. This issue and others created by me are just reminders.

**Comment by galdp** [comment]
![game-of-thrones-shame](https://user-images.githubusercontent.com/36263516/157186351-e044d10a-82ba-49dc-bf48-d23a652e7ff7.gif)
