### ISSUE TITLE
MultiplatformResourcesPackage not used in Android

### ISSUE THREAD

**Issue by lepicekmichal** [icerockdev/moko-resources#317]
Hello,
why is _androidSetup_ inside **MultiplatformResourcesPlugin** still using manifest for getting package name? 
I am passing **multiplatformResourcesPackage** variable and want to use that so there is no need to parse my AndroidManifest.

I am trying to use [autoManifest plugin ](https://github.com/GradleUp/auto-manifest) so I can generate my manifests but moko-resources is looking for it too soon, eagerly.

Please remove parsing AndroidManifest since I am passing the package name in setup variables. Or Add another option for ignoring it.

Thank you

**Comment by Alex009** [comment]
`multiplatformResourcesPackage` is not android package - it's destination where should be generated MR class.
android package from manifest required to locate `R` android class. 
we can add setting `androidResourcesPackage` to manual setup in case when AndroidManifest can't be parsed

**Comment by lepicekmichal** [comment]
I see. Okay, please add androidResourcesPackage then.
