### ISSUE TITLE
JS file paths not relative

### ISSUE THREAD

**Issue by luca992** [icerockdev/moko-resources#326]
I'm trying the new release with JS support and I get the error:

```
Module not found: Error: Can't resolve 'files/Migrations.json' in '/...../..../app/build/js/packages/app_module/kotlin'
Did you mean './files/Migrations.json'?
Requests that should resolve in the current directory need to start with './'.
Requests that start with a name are treated as module requests and resolve within module directories (node_modules).
If changing the source code is not an option there is also a resolve options called 'preferRelative' which tries to resolve these kind of requests in the current directory too.
```

this is what the generated Migrations file resource looks like in MR for js:
```
    public actual val Migrations: FileResource = FileResource(fileUrl =
        js("require(\"files/Migrations.json\")") as String)
```
I think the fix would be pretty simple to just prepend `./` before `files/Migrations.json`

Pretty sure I can work around it with the [preverRelative](https://webpack.js.org/configuration/resolve/#resolvepreferrelative) webpack option. But this seems like a bug, or at least something that should be configurable

**Comment by Alex009** [comment]
@y9san9 check case please

**Comment by y9san9** [comment]
@luca992 could you please provide more details, since it seems to work for me without "./" and not work with "./"

That is the web example when I am adding "./" before file path
<img width="1222" alt="Снимок экрана 2022-04-05 в 02 13 42" src="https://user-images.githubusercontent.com/46930374/161647619-ad9056a6-75b5-4c95-9101-676eb682e8b7.png">

**Comment by y9san9** [comment]
Note that there is a generated webpack config, maybe for some reason it doesn't applied in your case
<img width="301" alt="Снимок экрана 2022-04-05 в 02 16 45" src="https://user-images.githubusercontent.com/46930374/161647756-2204cd19-a889-4dfa-bf0a-0005ebee980e.png">

**Comment by luca992** [comment]
> Note that there is a generated webpack config, maybe for some reason it doesn't applied in your case <img alt="Снимок экрана 2022-04-05 в 02 16 45" width="301" src="https://user-images.githubusercontent.com/46930374/161647756-2204cd19-a889-4dfa-bf0a-0005ebee980e.png">

@y9san9 yeah. That might be the problem, because I'm using a multi-module project. Where I have a compose-ui `app` front end module. But, I am using moko-resources inside a different `shared` module. So I don't think the webpack config is being applied to the app module correctly.

If you want I could probably put together an example. But, I probably can't get to it for a few days at least.

**Comment by y9san9** [comment]
So, try to apply moko-resources plugin to your js application, it should analyze dependencies and generate common webpack for them

**Comment by y9san9** [comment]
To be honest that is not obvious thing (I don't know even if that would work). We should investigate it and add a proper note to readme.

**Comment by luca992** [comment]
Got it, think I should I apply the plugin to the shared module as well, or just the main `app` module?

**Comment by y9san9** [comment]
In two places: 
- plugin applied to the shared module will generate MR objects for all platforms including JS.
- plugin applied to the main js app module will generate a proper config

**Comment by luca992** [comment]
@y9san9 I can confirm applying the plugin to my `app` module fixed the issue. Thanks for the help

**Comment by zacharee** [comment]
How can I apply the plugin to the JS module without interfering with the plugin application in the shared module? If I use the same `multiplatformResourcesPackage`, I get a conflict error.

**Comment by zacharee** [comment]
> @zacharee use a different package name or class name in the gradle config: https://github.com/icerockdev/moko-resources#installation

That gets it syncing, but then I get an error when running:

```
✖ ｢wds｣: Invalid configuration object. Webpack has been initialised using a configuration object that does not match the API schema.
 - configuration.module.rules[1].type should be one of these:
   "javascript/auto" | "javascript/dynamic" | "javascript/esm" | "json" | "webassembly/experimental"
   -> Module type to use for the module
```

It doesn't seem happy about the `type: `asset/resource'` field in `moko-resources-generated.js`.

**Comment by zacharee** [comment]
Looks like it's a Webpack 4 vs 5 issue. I had to update to Webpack 5 and then manually include the skiko processing to get around Compose using Webpack 4.

Although now the tab just loads forever so I have to figure that out.

**Comment by shama** [comment]
I'm running into the same issue as OP where it appears the generated webpack config doesn't appear to run against the code. My JS builds are erroring as they're trying to `require('localization/file.json')` so it appears during the gradle build the generated `webpack.config.d/moko-resources-generated.js` isn't ran against the JS files to use the webpack url/file loader:

<img width="647" alt="Screenshot 2023-02-07 at 10 43 49 PM" src="https://user-images.githubusercontent.com/99604/217457891-880d8539-413e-4806-ab6f-7f9612cd5b2b.png">

It is a multi-module project and I've got the generator in my project `build.gradle.kts`:
```kt
buildscript {
    dependencies {
        classpath("dev.icerock.moko:resources-generator:${libs.versions.moko.resources.get()}")
    }
}
```

and then in the `lib` module `build.gradle.kts`:
```kt
plugins {
    id("dev.icerock.mobile.multiplatform-resources")
}

multiplatformResources {
    multiplatformResourcesPackage = "ynab.slik.resources"
    multiplatformResourcesClassName = "SlikResources"
}
```

The `commonMain` source set has the dependency to `api(libs.moko.resources)`.

I am a Kotlin/Gradle noob so any help is very much appreciated. I don't know if there is additional Gradle config needed or I did something wrong. I'm also still figuring out how to debug a webpack build through Gradle.

**Comment by luca992** [comment]
@shama you mentioned you only appied the plugin to your `lib` module. Did you add it to the other module as well? as described here: https://github.com/icerockdev/moko-resources/issues/326#issuecomment-1088132070

**Comment by shama** [comment]
@luca992 Apologies, I don't fully understand https://github.com/icerockdev/moko-resources/issues/326#issuecomment-1088132070 likely because I'm new to gradle.

I have a project structure like this:
```
project/
├── build.gradle.kts
└── lib/
    ├── build.gradle.kts
    ├── src/
    │   ├── androidMain/
    │   ├── commonMain/
    │   ├── iosMain/
    │   └── jsMain/
    └── webpack.config.d/
```

At the project level `project/build.gradle.kts` I added moko here:
```kt
buildscript {
    dependencies {
        classpath("dev.icerock.moko:resources-generator:${libs.versions.moko.resources.get()}")
    }
}
```

At the module level `project/lib/build.gradle.kts` I added moko at these places:
```kt
plugins {
    kotlin("multiplatform")
    id("dev.icerock.mobile.multiplatform-resources")
}
// ...
kotlin {
    sourceSets {
        val commonMain by getting {
            dependencies {
                api(libs.moko.resources)
            }
        }
        val jsMain by getting
        // ..
    }
}
// ...
multiplatformResources {
    multiplatformResourcesPackage = "ynab.slik.resources"
    multiplatformResourcesClassName = "SlikResources"
}
```

Running `./gradlew clean lib:jsBrowserProductionLibraryDistribution` generates the `webpack.config.d/moko-resources-generated.js` config and builds the JS.

But the webpack config appears to not run against the JS as the `.json` files it references are `require('localization/...')`. I would expect the json files to be inlined if the webpack url-loader or file-loader successfully ran against those generated JS files.
