### ISSUE TITLE
Ability to add country/region-specific localizations

### ISSUE THREAD

**Issue by steviek** [icerockdev/moko-resources#329]
Is it possible to provide different strings by region? E.g. distinguishing en_US and en_GB? If so, can you add an example to the docs?

**Comment by rustamsmax** [comment]
There is an issue when specified region. I think this must be fixed in upcoming releases

**Comment by rustamsmax** [comment]
![telegram-cloud-photo-size-2-5438105058836331128-y](https://user-images.githubusercontent.com/36570577/166144877-6cec381c-168b-4a13-b1b2-324e3e637c10.jpg)

**Comment by Alex009** [comment]
hi @kevincianfarini 
you can try to implement this feature and send PR.
i think changes required in this places:
- https://github.com/icerockdev/moko-resources/blob/c59420bee59e99f6d0481226db86cdc4661c91df/resources-generator/src/main/kotlin/dev/icerock/gradle/generator/android/AndroidStringsGenerator.kt#L43
- https://github.com/icerockdev/moko-resources/blob/c59420bee59e99f6d0481226db86cdc4661c91df/resources-generator/src/main/kotlin/dev/icerock/gradle/generator/android/AndroidPluralsGenerator.kt#L43
- https://github.com/icerockdev/moko-resources/blob/c59420bee59e99f6d0481226db86cdc4661c91df/resources-generator/src/main/kotlin/dev/icerock/gradle/generator/apple/AppleStringsGenerator.kt#L38
- https://github.com/icerockdev/moko-resources/blob/c59420bee59e99f6d0481226db86cdc4661c91df/resources-generator/src/main/kotlin/dev/icerock/gradle/generator/apple/ApplePluralsGenerator.kt#L81

and maybe it's already works? as i see full directory name used as language name so if you create `MR/en-US/strings.xml` it's should create `en-US` resources

**Comment by kevincianfarini** [comment]
Done! @Alex009. Unfortunately it was a bit more complicated than that, though.

**Comment by kevincianfarini** [comment]
@Alex009 If you have some time to chat (either via email, Slack) I'd like to pick your brain on how we can proceed with #356. Android is expressing different behavior than every other platform, and I'd like to formulate a plan forward that you're happy with.

**Comment by glureau** [comment]
Not sure about the progress so I share my current workaround (a simple file renaming via gradle) if ever it can help someone.

```
task("patchMokoStringLocalizationsForAndroid") {
    afterEvaluate {
        project.tasks.forEach {
            if (it.name.endsWith("generateDebugResValues")) {
                it.finalizedBy("patchMokoStringLocalizationsForAndroid")
            }
        }
    }
    doLast {
        val resDir = File(buildDir.absolutePath + "/generated/moko/androidMain/res")
        if (resDir.exists()) { // No android resources -> nothing to do
            val regionSpecificLocalizationRegex = Regex("^values-([a-z]+)-([A-Z]+)$")
            resDir.listFiles()?.forEach {
                val matchResult = regionSpecificLocalizationRegex.find(it.name)
                if (matchResult != null) {
                    val newDirName = "values-${matchResult.groupValues[1]}-r${matchResult.groupValues[2]}"
                    it.renameTo(File(it.parent + "/$newDirName"))
                }
            }
        }
    }
}
```

**Comment by Alex009** [comment]
will be released in 0.21.0

**Comment by glureau** [comment]
@kaidotarma glad to hear, but did you get an issue with 0.21.0? On my side I was able to remove this workaround after the upgrade. (If you still have an error with higher version, you may want to open an issue for the moko team to be able to help.)

**Comment by kaidotarma** [comment]
> @kaidotarma glad to hear, but did you get an issue with 0.21.0? On my side I was able to remove this workaround after the upgrade. (If you still have an error with higher version, you may want to open an issue for the moko team to be able to help.)

You are correct! My library version was not update in all places.
Thanks for pointing this out! Now I can also remove this hack.
