### ISSUE TITLE
Value of type 'ResourcesStringResource' has no member 'desc'

### ISSUE THREAD

**Issue by matteinn** [icerockdev/moko-resources#338]
Hi there!
I'm trying to integrate the library in a KMM project and I'm facing some issues with the usage on the iOS app (integrated via "iOS framework distribution": "Regular framework").

Here's the error:
`Value of type 'ResourcesStringResource' has no member 'desc'`
<img width="867" alt="Screenshot 2022-05-07 at 03 06 34" src="https://user-images.githubusercontent.com/531755/167231883-6c197a10-91b9-40bb-89d6-547fb2c956f0.png">

I'm attaching the empty project generated by AS with the only addition of moko-resources that demonstrates the issue:
[ABC.zip](https://github.com/icerockdev/moko-resources/files/8644175/ABC.zip)

Are there any other steps needed?

If I also apply what's mentioned in https://github.com/icerockdev/moko-resources#static-kotlin-frameworks-support (which I believe it's necessary) then I get another error during that build phase:
`Task 'copyFrameworkResourcesToApp' not found in project ':shared'.`

Hence I suspect that the readme might be missing some crucial information.

Thanks in advance

**Comment by Alex009** [comment]
to use kotlin methods from swift you should add library to export.
https://kotlinlang.org/docs/multiplatform-build-native-binaries.html#export-dependencies-to-binaries

sample:
https://github.com/icerockdev/moko-resources/blob/master/sample/mpp-hierarhical/build.gradle.kts#L49

**Comment by matteinn** [comment]
Thanks, that indeed fixed the issue!

**Comment by applepeopletsai** [comment]
Hi, @matteinn 
I face the same issue
And I can't fix it by @Alex009 's  answer
Could you show me how did you fix it?
Thx.

**Comment by applepeopletsai** [comment]
WOW!!
It's working
Thank you very much
You save my day :)
