### ISSUE TITLE
Error when building my project

### ISSUE THREAD

**Issue by EgorNagaev** [icerockdev/moko-resources#341]
get the following error:
w: skipping /Users/a401-00/.gradle/caches/modules-2/files-2.1/dev.icerock.moko/mvvm-flow-iosx64/0.13.0/1913390ba07202cca04875b72ac4bb91d5e2a17b/mvvm-flow.klib. Incompatible abi version. The current default is '1.5.0', found '1.6.0'. The library produced by 1.6.10 compiler

e: Could not find "/Users/a401-00/.gradle/caches/modules-2/files-2.1/dev.icerock.moko/mvvm-flow-iosx64/0.13.0/1913390ba07202cca04875b72ac4bb91d5e2a17b/mvvm-flow.klib" in [/Users/a401-00/Downloads/bonuscocoapods-master/iosApp/Pods, /Users/a401-00/.konan/klib, /Users/a401-00/.konan/kotlin-native-prebuilt-macos-x86_64-1.5.30/klib/common, /Users/a401-00/.konan/kotlin-native-prebuilt-macos-x86_64-1.5.30/klib/platform/ios_x64]

What might be happening?

**Comment by Alex009** [comment]
to use moko-mvvm 0.13.0 you should use kotlin 1.6.10 or higher. and this repository for moko-resources, not mvvm.
