### ISSUE TITLE
Support of UTF-8 with Swift strings as arguments for formatted strings

### ISSUE THREAD

**Issue by ln-12** [icerockdev/moko-resources#344]
I am currently writing my formatted strings as `Some string %1$s` with an argument like `Hello äöü`. On Android, I use the following composable, which works fine:
```kotlin
@Composable
fun StringResource.formatted(vararg args: Any): String {
    return this.format(*args).toString(context = LocalContext.current)
}
```

On iOS I was using this helper function:
```swift
func formatted(_ args: CVarArg...) -> String {
        return String(format: self.localized(), arguments: args.map {
            if let string = $0 as? String {
                return (string as NSString).utf8String ?? ""
            } else {
                return $0
            }
        })
    }
```
This causes issues, as Swift assumes 8-bit `unsigned char` for `$s` (see [here](https://developer.apple.com/library/archive/documentation/CoreFoundation/Conceptual/CFStrings/formatSpecifiers.html)). This returns the wrong output for UTF-8 symbols like `ö`, `ä` or `ü`.

The solution I found is to use the `$@` specifier instead, which can handle Swift string objects just fine.
```swift
func formatted(_ args: CVarArg...) -> String {
        return String(format: self.localized().replacingOccurrences(of: "$s", with: "$@"), arguments: args)
    }
```

So either you want implement the use of `$@` in you library or maybe give a hint in the readme, so that other developers can find this tip.

**Comment by Alex009** [comment]
but we already use exactly `%@`
https://github.com/icerockdev/moko-resources/blob/a67e5039c5bd3f3fdc02966443a0c3e5d4dd41ed/resources/src/appleMain/kotlin/dev/icerock/moko/resources/desc/Utils.kt#L26
if you will use `StringDesc.localized` - you got correct format.

what you suggest?

**Comment by ln-12** [comment]
Ah ok, thanks for the clarification. My issue was that this method is only available in the shared code, but not from the Swift side. So I just added a generic helper function and now it works fine with your code.
```kotlin
fun formatString(resource: StringResource, args: List<Any>): String {
    return resource.format(args).localized()
}
```
Thank you! :)
