### ISSUE TITLE
Identify assets files with same name but different type in the same folder

### ISSUE THREAD

**Issue by ptvinhkhue** [icerockdev/moko-resources#350]
I have some struggle in using the assets files. 

I tried to store same name files in different folder, it works as expected. But the problem arise when I tried to put files with same name but different type in the same folder e.g. file1.png and file1.json. The result is that the generated object used duplicated file1 variable for two directories, which caused an error. 

Is this a real problem or I have just skipped some required settings or dependencies?

**Comment by Alex009** [comment]
yes, it's not supported case now...changes required

**Comment by Alex009** [comment]
fixed in 0.24.0-beta-1
