### ISSUE TITLE
webpack.config.d/moko-resources-generated.js is generated with invalid path on Windows

### ISSUE THREAD

**Issue by lupuuss** [icerockdev/moko-resources#354]
[This line](https://github.com/icerockdev/moko-resources/blob/c59420bee59e99f6d0481226db86cdc4661c91df/resources-generator/src/main/kotlin/dev/icerock/gradle/generator/js/JsMRGenerator.kt#L155) should generate path literal `"C:\\users\\example\\projects\\test"` on Windows, but it generates `"C:\users\example\projects\test"`.

**Comment by Alex009** [comment]
why should be line with escaped \?

**Comment by Alex009** [comment]
will be released in 0.21.0
