### ISSUE TITLE
Support for platform specific strings/resources

### ISSUE THREAD

**Issue by mustafaozhan** [icerockdev/moko-resources#357]
Hello 👋 

Recently I created a PR in order to split my Android only, iOS only and mutual strings from each other. It seems moko-resources doesn't support that.

The mutual one stays already inside `commonMain>resources>MR>base>strings.xml` and I created followings for the android and iOS only strings

- `androidMain>resources>MR>base>strings.xml`
- `iosMain>resources>MR>base>strings.xml`

We should be able to do this in order to not include un-used resources in the builds, in both platforms.

Related PR: https://github.com/Oztechan/CCC/pull/794

**Comment by Alex009** [comment]
fix in #575

**Comment by ExNDY** [comment]
will be fixed in 0.24.0, please check in 0.24.0-alpha-6
