### ISSUE TITLE
getIntermediateLibrary() was remove

### ISSUE THREAD

**Issue by hsedjj** [icerockdev/moko-resources#358]
When I updated my multiplatform project to kotlin 1.7.0 and try to sync cleaned project get this message ( also using multiplatformResources in feature )

```
Unable to find method ''org.gradle.api.provider.Provider org.jetbrains.kotlin.gradle.tasks.KotlinNativeLink.getIntermediateLibrary()''
'org.gradle.api.provider.Provider org.jetbrains.kotlin.gradle.tasks.KotlinNativeLink.getIntermediateLibrary()'

Gradle's dependency cache may be corrupt (this sometimes occurs after a network connection timeout.)

Re-download dependencies and sync project (requires network)

The state of a Gradle build process (daemon) may be corrupt. Stopping all Gradle daemons may solve this problem.

Stop Gradle build processes (requires restart)

Your project may be using a third-party plugin which is not compatible with the other plugins in the project or the version of Gradle requested by the project.

In the case of corrupt Gradle processes, you can also try closing the IDE and then killing all Java processes.
```

[Issue for kotlin native](https://youtrack.jetbrains.com/issue/KT-52982/Gradle-MPP-Native-getIntermediateLibrary-was-removed) with answered for problem.

**Comment by Alex009** [comment]
What version of moko resources you use?
Kotlin 1.7.0 support added in https://github.com/icerockdev/moko-resources/releases/tag/release%2F0.20.1

**Comment by LikeMyDad** [comment]
I'm using actual version of moko-res 20.1

**Comment by Alex009** [comment]
@LikeMyDad  as i see moko-resources 0.20.1 works fine with kotlin 1.7.0 
please check my sample project - https://github.com/Alex009/moko-resources-sample and compare with your config.
pay attention to version of moko-resources gradle plugin.

**Comment by Alex009** [comment]
@aleksey-ho , @LikeMyDad hi. can you create small project where this issue can be reproduced and send to me? in my project that i send [here](https://github.com/Alex009/moko-resources-sample) all ok

**Comment by aleksey-ho** [comment]
@Alex009, thanks, sure, I managed to reproduce by adding kswift to the project, [sample here](https://github.com/aleksey-ho/moko-resources-sample)
gradle build is successful, but xcode build fails

**Comment by antanas-radzevicius-tgo** [comment]
having same problem with latest kotlin and kswift version when cocoapods flag `isStatic = true`
