### ISSUE TITLE
Support localization change in runtime

### ISSUE THREAD

**Issue by DevTchernov** [icerockdev/moko-resources#36]
- Add `locale` property in StringDesc companion
- Support `System` / `Custom(locale: String)` values, implement behavior in actual classes
- Generate additional iOS localization tables (*.strings files) for custom locales

**Comment by Alex009** [comment]
https://developer.apple.com/documentation/foundation/bundle/1417694-localizedstring about localization tables info here

**Comment by Alex009** [comment]
merged
