### ISSUE TITLE
Add all targets supported by compose-jb alpha to resources-compose

### ISSUE THREAD

**Issue by luca992** [icerockdev/moko-resources#360]
iOS is my most immediate concern.
But, it would be nice to have all targets that compose-jb alpha supports added.

**Comment by chris-hatton** [comment]
My team have also hit this issue; we're trying to load a Font from a library, on all of Android, iOS and Desktop.
With current Moko API it's proving very problematic: `files`, `assets` and `fonts` approaches each have their own issues.

**Comment by Alex009** [comment]
compose multiplatform already supported from 0.22.0
