### ISSUE TITLE
UIKit view cannot handle the run time dark/light mode changes for colors

### ISSUE THREAD

**Issue by danie1ll** [icerockdev/moko-resources#368]
I saw that in order to solve this issue for SwiftUI, one has to put @Environment(\.colorScheme) var colorScheme in the View. Is there some fix for UIKit? Currently the dark/light mode changes for colors are only possible after restarting the app. However, if the colors are defined in a standard way (in Xcode), the run time change works perfectly fine

**Comment by Alex009** [comment]
will be released in 0.21.0
