### ISSUE TITLE
Multi Module setup - value of type 'MR.strings' has no member 'xy_string'

### ISSUE THREAD

**Issue by nrobi144** [icerockdev/moko-resources#379]
### Description
We have the following project structure: `common` Module -> `commonBase` Module. The `common` module is exposed to iOS only.
We recently moved a couple of strings into `commonBase`, and we're getting back `value of type 'MR.strings' has no member 'xy_string'` on iOS only (Android is running fine).

### Environment and Installation
Both `common` and `commonBase` have:
- Plugin applied - `alias(libs.plugins.moko.resources)`
- `commonBase` has `implementation(libs.moko.resources)`
- `common` has `api(libs.moko.resources)` and `export("dev.icerock.moko:resources:0.20.1")`
- `commonBase` has 
```
multiplatformResources {
    multiplatformResourcesPackage = "com.company.sharedcore"
    iosBaseLocalizationRegion = "en" // optional, default "en"
    multiplatformResourcesSourceSet = "commonMain"
}
```
- `common` has
```
multiplatformResources {
    multiplatformResourcesPackage = "com.company"
    iosBaseLocalizationRegion = "en" // optional, default "en"
    multiplatformResourcesSourceSet = "commonMain"
}
```
iOS is using the new `embedAndSignAppleFrameworkForXcode` gradle task

### Version
`0.20.1`

**Comment by Alex009** [comment]
@nrobi144 in `commonBase` you have another `MR` class. so from swift you should call `MR_` class, but first you should add your `commonBase` to `export`

**Comment by nrobi144** [comment]
@Alex009 
> but first you should add your commonBase to export 

`commonBase` is exported, but I'll try to set `multiplatformResourcesClassName`

**Comment by nrobi144** [comment]
@Alex009 adding `multiplatformResourcesClassName = "BaseMR"` to `commonBase` doesn't help

**Comment by nrobi144** [comment]
Changing the default `ClassName` with `multiplatformResourcesClassName=BaseMR` in `commonBase` fixes this
