### ISSUE TITLE
Support for generating resource code as `internal`

### ISSUE THREAD

**Issue by kevincianfarini** [icerockdev/moko-resources#380]
In a setup with a lot of gradle modules, it's helpful to limit the namespace of generated code. In my particular use case, I want to enforce that some generated string symbols are only visible within the module they're declared in. 

Other code generation libraries have similar functionality, namely Apollo Kotlin. 

```kt
apollo {
    generateAsInternal.set(true)
    ...
}
```

**Comment by Alex009** [comment]
@kevincianfarini we already have control on visibility:
```
multiplatformResources {
    multiplatformResourcesVisibility = MRVisibility.Internal // optional, default Public
}
```
