### ISSUE TITLE
Resources are not copied into build/js folder when separate JS application uses library with MOKO resources in the same project

### ISSUE THREAD

**Issue by ComBatVision** [icerockdev/moko-resources#385]
Hello,

I am developing the NASA WorldWindKotlin 3D GIS library based on the Kotlin Multi-platform stack and we are using MOKO resources to access common images from JS, JVM and Android sources.

Our project consists of the core KMP library module "worldwind" which implements MOKO-resources and two example application modules for Android and JS, which use "worldwind" module as a dependency and do not implement MOKO resources directly.

The Android version of our example application builds fine and see resources from "worldwind" common resources, but the JS version shows an error, because it does not see images in the generated build/js folder. All dependent JS libraries are there, but no resources.

I assume that your library plugin works incorrectly when resources are in the dependent module of the same project and MOKO does not generate/copy resources to the output folder of the application.

![error](https://user-images.githubusercontent.com/12487306/191293818-977c64c6-fb05-4846-a16f-b9d12a6a4e20.png)
![files](https://user-images.githubusercontent.com/12487306/191293868-54cc6915-f67d-46e3-bee2-906259c68bd1.png)

**Comment by Alex009** [comment]
https://github.com/WorldWindEarth/WorldWindKotlin/issues/1#issuecomment-1257907092 here described reason and fix.
now moko-resources gradle plugin works only with kotlin-multiplatform gradle plugin. you can't use kotlin-js/kotlin-jvm plugins for application if you want use moko-resources
