### ISSUE TITLE
How to read string inside commonMain ?

### ISSUE THREAD

**Issue by RageshAntony** [icerockdev/moko-resources#399]
I am trying to access the string value from commonMain but getting like this . (I able to use in Android and iOS , but can get string value in commonMain)

`ResourceStringDesc(stringRes=StringResource(resourceId=2131558445))`
`StringResource(resourceId=2131558445)
`
I am using this :

```
StringDesc.Resource(MR.strings.greeting).toString()
MR.strings.greeting.desc().toString()
MR.strings.greeting.toString()
```
Please assist me

**Comment by Alex009** [comment]
you can't read string from resources in common code. android require `Context` to use resources, so you should read string at UI layer.
in common code use StringDesc as abstraction

**Comment by RageshAntony** [comment]
@Alex009 

Ohh okay. But I couldn't understand how to use like this 

For example 

a common method to get username with salutation in many languages 

```
//commonMain
getGreetedName(name: String) {
      return StringDesc.Resource(MR.strings.greeting).toString() + " " + name;
}
```

**Comment by RageshAntony** [comment]
@Alex009 reply updated . Please assists

**Comment by Alex009** [comment]
MR class actuals not generated at moment of writing. call `generateMRJsMain`
