### ISSUE TITLE
stringResource is marked as an error in Android Studio (but works when compiled)

### ISSUE THREAD

**Issue by KiraResari** [icerockdev/moko-resources#401]
For some strange reason, all imports and usages of `stringResource` are marked as errors in my project using Android Studio 2021.3.1 Patch 1.

The error says: `Unresolved reference: stringResource`

However, when I run the program, it works just fine.

Also, I can see that my project knows the `dev.icerock.moko.resources.compose` package containing these files.

I have already tried explicitly adding `implementation("dev.icerock.moko:resources-compose:0.20.1")` to the Dependencies of that module, but to no avail.

Is that an IDE-related issue? Or what is going on here?

![image](https://user-images.githubusercontent.com/28697173/209550266-9b057805-5a6a-41fa-8aee-0a3e172bd241.png)

**Comment by Alex009** [comment]
at now i not see this issue. if it reproduced at latest release - please reopen issue
