### ISSUE TITLE
No strings generated in multiplatformResourcesClass

### ISSUE THREAD

**Issue by tekinalper** [icerockdev/moko-resources#412]
multiplatformResourcesClass is successfully created but not the strings. I try to call a string resource from a class in commonMain `StringDesc.Resource(OR.strings.my_string).toString()`

Am I missing something?

```
public expect object OR {
  public object strings : ResourceContainer<StringResource>

  public object plurals : ResourceContainer<PluralsResource>

  public object images : ResourceContainer<ImageResource>

  public object fonts : ResourceContainer<FontResource>

  public object files : ResourceContainer<FileResource>

  public object colors : ResourceContainer<ColorResource>

  public object assets : ResourceContainer<AssetResource>
}
```

**Comment by Alex009** [comment]
please check your resources directory content. compare with https://github.com/icerockdev/moko-resources/tree/master/sample/mpp-library/src/commonMain/resources

**Comment by tekinalper** [comment]
Thanks Aleksey, I checked and also copied the directory content but still `generateMRcommonMain` task doesn't generate the contents of the objects.

**Comment by Alex009** [comment]
@tekinalper can you configure this project https://github.com/Alex009/moko-resources-sample to reproduce your issue?

**Comment by tekinalper** [comment]
@Alex009 The configuration was the same but I was using a plugin for dependency versions, after setting full version to the dependency broke the cache I guess and generated the resources successfully.
