### ISSUE TITLE
Support multiple iOS string bundles

### ISSUE THREAD

**Issue by ptsiogas** [icerockdev/moko-resources#413]
# Description
Let's assume that I have a KMM library that contains MOKO string resources (e.g error messages) and I integrate this library into a KMM module that also uses MOKO string resources.
I have seen that the iOS framework contains both .bundle files but the actual result is that the MR class has references only from the library.

Is there a way to support multiple bundles?
In the Android client everything works fine btw.

**Comment by Alex009** [comment]
ios support both bundles.
you have MR in both modules

**Comment by ptsiogas** [comment]
And how can I declare which MR I am asking in the swift code?
Because I have tried to go with the MR.strings().some_string_id_from_bundle_a and I get an error. The only string ids I can see is those of bundle b.

**Comment by ptsiogas** [comment]
MR_ seems to work fine. Is there a similar solution in order to get the StringDesc on the KMM code too?
I would like to serve the proper StringDesc from the KMM code.

**Comment by Alex009** [comment]
add moko-resources to export and you can use StringDesc in swift. it's described in readme
