### ISSUE TITLE
resources-cinterop-pluralizedString can't be exported with -Xexport-library

### ISSUE THREAD

**Issue by TSkovsgaard** [icerockdev/moko-resources#414]
Hi I started getting this error and can't seem to find the source of it..

```
> Task :shared:linkDebugFrameworkIosArm64
w: Interop library /Users/thomas/.gradle/caches/modules-2/files-2.1/dev.icerock.moko/resources-iosarm64/0.20.1/6b42c68f8be2f10e5ff5ee92da465512e942c8e7/resources-cinterop-pluralizedString can't be exported with -Xexport-library
```

The error is for all link tasks:

```
- linkDebugFrameworkIosArm64
- linkDebugFrameworkIosX64
- linkDebugFrameworkIosFat
- linkReleaseFrameworkIosArm64
- linkReleaseFrameworkIosX64
```
except `linkReleaseFrameworkIosFat`

Project is using Cocoapods, I tried to change to regular framework and I added the export dependency as described in the readme `export("dev.icerock.moko:resources:0.20.1")`, but I ended up with the exact same error

**Comment by Alex009** [comment]
```
w: Interop library /Users/thomas/.gradle/caches/modules-2/files-2.1/dev.icerock.moko/resources-iosarm64/0.20.1/6b42c68f8be2f10e5ff5ee92da465512e942c8e7/resources-cinterop-pluralizedString can't be exported with -Xexport-library
```
is not error - it's just warning. and it's not broke build at all.

can you configure this project https://github.com/Alex009/moko-resources-sample to reproduce your issue?

**Comment by tekinalper** [comment]
@TSkovsgaard Do you also get the error below? If yes, I'll let you know what is related with this issue :)
`ld: framework not found FirebaseAuth`

**Comment by msa1422** [comment]
I believe upgrading the Gradle to v8 has turned the warning into a compilation error. I will try to share a project where the error is reproducible.

**Comment by msa1422** [comment]
Upgrading Gradle to 8.0.2 in [moko-resources-sample](https://github.com/Alex009/moko-resources-sample) throws the following error on gradle sync
```
Cannot use @TaskAction annotation on method IncrementalTask.taskAction$gradle_core() because interface org.gradle.api.tasks.incremental.IncrementalTaskInputs is not a valid parameter to an action method.
```

Will try to post another project with Gradle V8

**Comment by Alex009** [comment]
@msa1422 in 0.21.0 cinterop was removed, so it's not relevant now

**Comment by msa1422** [comment]
I have updated to 0.21.0 and things seems to be working well. Thanks a lot mate, this update helps a lot. New ColorResource simplifies the theme set up in compose also. That's a good add on as well.
