### ISSUE TITLE
Update to Kotlin 1.8.0

### ISSUE THREAD

**Issue by Wavesonics** [icerockdev/moko-resources#431]
Currently using 1.6.10 which is getting pretty long in the tooth, would probably be a good idea to update to 1.8.0 soon

**Comment by Alex009** [comment]
You can use this library with kotlin 1.8.10 in your project. Kotlin have backward compatibility. But if we publish library by 1.8.10 then consumers with old kotlin version can't use lib.
At now I not see any reasons to increase kotlin version

**Comment by Wavesonics** [comment]
ah got ya, good point

**Comment by dalewking** [comment]
I am trying to upgrade to Kotlin 1.8 and I think that you don't support the new Android source set layout (https://kotlinlang.org/docs/whatsnew18.html#kotlin-multiplatform-a-new-android-source-set-layout). Still investigating but I get errors that none of the resources are found for Android

**Comment by Alex009** [comment]
yes, new android source set layout not supported now. here issue https://github.com/icerockdev/moko-resources/issues/410
but anyone can use kotlin 1.8 with old android source set layout. i close this issue. about new android source set layout please write in https://github.com/icerockdev/moko-resources/issues/410 if got any info
