### ISSUE TITLE
Override moko resource in submodule

### ISSUE THREAD

**Issue by Murtowski** [icerockdev/moko-resources#433]
### Discussed in https://github.com/icerockdev/moko-resources/discussions/432

<div type='discussions-op-text'>

<sup>Originally posted by **Murtowski** February 27, 2023</sup>
Imagine that we have `common` KMM module that contains Moko `resources`.
That module has a class with method which returns `ColorResource.Single` e.g. `MR.colors.primary`

Then we have another `android` module which depends on module `common` (`implementation(project("common"))`)
Is it possible to override in `android` module value of `MR.colors.primary` returned by `common` module ?</div>

**Comment by Alex009** [comment]
hi!
no, it's not possible. you can override android resource, but for ios resources packed in `bundle` and each module have own bundle.
