### ISSUE TITLE
Shared file resources

### ISSUE THREAD

**Issue by Tetraquark** [icerockdev/moko-resources#44]
Implementation of a feature to share resource files or assets (e.g. config file) from same location for both platforms and for native and common code (if it's possible) is needed.

**Comment by nadafsak** [comment]
Any news on this?

**Comment by Alex009** [comment]
@nadafsak hello! 
can you see request #66 and give feedback - this implementation solve your issue or not?

**Comment by Alex009** [comment]
merged, will be available in 0.10.0
