### ISSUE TITLE
Allow for source set overrides

### ISSUE THREAD

**Issue by dgluhovic** [icerockdev/moko-resources#45]
Thanks for your work on this library, it's great.  Would you consider tweaking the gradle plugin to allow for overriding of `commonMain` as the base source set?  Along the lines of https://github.com/dgluhovic/moko-resources/commit/a19d126bad5edb7a4355f9755bd79f72ea3c056c .  This works for my purpose, would be happy to submit a PR if not too hacky.  My use case is, `commonMain` contains models, constants etc, shared with a backend jvm target not supported by MR.  Shared client code is in `commonClientMain`, would like to set this as the MR base source set.

**Comment by Alex009** [comment]
hi! submit PR please :)

**Comment by Alex009** [comment]
merged, will be in 0.9.0 release
