### ISSUE TITLE
Problems with KMM iOS Side

### ISSUE THREAD

**Issue by JustusBachmann** [icerockdev/moko-resources#451]
I set up MR as explained in the readme for iOS and Android in a kmm project. For android it works quite well, but the iOS app always displays the string key instead of the localized string.
The framework is generated by cocapods and included over pods (non-static framework).

Tried both the iOS native access and the SwiftUI access as listed in the readme:
```
                    Text(MR.strings().show_request.desc().localized())

                    let resource = MR.strings().show_request
                    Text(
                        LocalizedStringKey(resource.resourceId),
                        bundle: resource.bundle
                    )
```

could there be something that I might have forgotten to implement?

**Comment by Alex009** [comment]
check setup of xcode project - https://github.com/icerockdev/moko-resources#xcode-setup

**Comment by JustusBachmann** [comment]
This is my Info.plist:

<img width="741" alt="Bildschirm­foto 2023-03-31 um 09 17 42" src="https://user-images.githubusercontent.com/40598558/229050795-0df5c4b3-6e32-4cc4-9116-cf7b64e0e721.png">


and these are my languages in the project:
<img width="198" alt="Bildschirm­foto 2023-03-31 um 09 11 51" src="https://user-images.githubusercontent.com/40598558/229050892-780a6217-9500-4dfe-ab37-1002b12ec10b.png">

Could there be any problem with the base language?

**Comment by Alex009** [comment]
maybe something wrong with generated `.strings` resources for iOS.
try to get `Localizable.strings` file from your compiled kotlin framework (file located in *.bundle) - open this strings file in Xcode and see show Xcode some warnings with it or not

**Comment by JustusBachmann** [comment]
Thanks for your help, issue was the same as described in #642.
