### ISSUE TITLE
iOS Build Error With Gradle Plugin 8.0.0 and Kotlin 1.8.20 

### ISSUE THREAD

**Issue by Ynnck123** [icerockdev/moko-resources#461]
I set up my project with Gradle Plugin 8.0.0 and Kotlin 1.8.20. The Android app successfully builds, but the iOS app build process fails with the following error:

```
> Task :shared:compileKotlinIosSimulatorArm64 FAILED
error: Could not find "dev.icerock.moko:resources-cinterop-pluralizedString" in [/folderToMyKMMApp, /Users/myUser/.konan/klib, /Users/myUser/.konan/kotlin-native-prebuilt-macos-aarch64-1.8.20/klib/common, /Users/myUser/.konan/kotlin-native-prebuilt-macos-aarch64-1.8.20/klib/platform/ios_simulator_arm64]
error: Compilation finished with errors
```

Is the library not compatible with this setup? It says `Could not find "dev.icerock.moko:resources-cinterop-pluralizedString"`

**Comment by Alex009** [comment]
check other moko libraries that you use - please update them all to latest version. https://github.com/icerockdev/moko-mvvm/issues/230 here described details

**Comment by Ynnck123** [comment]
Thank you very much for the fast response! That was the issue. I also had moko-mvvm in my project which was still on version 0.11.0. After updating to 0.16.0 the project built successfully 🙏 

Additional info, had to slightly adapt the dependency: 
From
```
    implementation("dev.icerock.moko:mvvm:0.11.0")
```
to 

```
   implementation("dev.icerock.moko:mvvm-core:0.16.0")
```
