### ISSUE TITLE
Svg images in MR/images causing "Execution failed for task ':shared:generateMRandroidMain'"

### ISSUE THREAD

**Issue by msa1422** [icerockdev/moko-resources#466]
I am using svg images from MR/assets. But after updating Moko-Resources to 0.22.0, moving the SVG resources to MR/images, project won't compile anymore. Following error is thrown:

```
Unable to find method ''java.lang.String com.android.ide.common.vectordrawable.Svg2Vector.parseSvgToXml(java.io.File, java.io.OutputStream)''
'java.lang.String com.android.ide.common.vectordrawable.Svg2Vector.parseSvgToXml(java.io.File, java.io.OutputStream)'

Gradle's dependency cache may be corrupt (this sometimes occurs after a network connection timeout.)

Re-download dependencies and sync project (requires network)
The state of a Gradle build process (daemon) may be corrupt. Stopping all Gradle daemons may solve this problem.

Stop Gradle build processes (requires restart)
Your project may be using a third-party plugin which is not compatible with the other plugins in the project or the version of Gradle requested by the project.

In the case of corrupt Gradle processes, you can also try closing the IDE and then killing all Java processes.
```

I will try to share a sample project where this bug can be reproduced.

**Comment by Alex009** [comment]
issue with AGP 8

**Comment by msa1422** [comment]
Works with the latest AGP 8.0.1. I really appreciate your contribution.

**Comment by zacharee** [comment]
I'm running into this with AGP 8.0.2 and Moko 0.23.0.

**Comment by Alex009** [comment]
@zacharee show logs please

**Comment by zacharee** [comment]
The log is exactly the same as in the original post. There are no more details given in the build output about the cause.

Setting the AGP version to 8.0.2 in this project will reproduce: https://github.com/zacharee/ArcadyanKVD21Control/.

**Comment by msa1422** [comment]
I am using AGP 8.0.2 with Moko-Resources 0.23.0 in 3 projects. All are working fine.
