### ISSUE TITLE
Some languages are not working on Android since version 0.21.2

### ISSUE THREAD

**Issue by sdeff** [icerockdev/moko-resources#468]
Hi there,

I've noticed that after updating from version `0.20.1` to `0.21.2`, the Indonesian support (`values-in`) seems to have ceased functioning on Android. No other changes were made aside from the version update, suggesting this may be tied to the update. I already tried using `values-in-rID` which didn't help either.

Could anyone else confirm if they're experiencing the same issue? Any input would be greatly appreciated.

Thank you for your assistance.

**Comment by sdeff** [comment]
It looks like since `0.21.2` it generates a `values-id` instead of `values-in`. AFAIK this should still generate `values-in` strings to work on Android with Indonesian language set. Therefore this looks like a bug to me

**Comment by Alex009** [comment]
on JDK 11 i not see errors when generate resources.
i create `in` multiplatform resources
<img width="217" alt="image" src="https://github.com/icerockdev/moko-resources/assets/5010169/2b60130d-fd6a-4d6f-90b9-cc16da17c7b4">
and got `in` generated resoursed:
<img width="342" alt="image" src="https://github.com/icerockdev/moko-resources/assets/5010169/7d37e6b0-52d0-4b4e-a7e8-86993e4b8fae">

but on JDK 17 i see changes:
<img width="330" alt="image" src="https://github.com/icerockdev/moko-resources/assets/5010169/50e9056c-8657-4874-926a-2852f77ba3df">

**Comment by Alex009** [comment]
fix will be available in 0.23.0
