### ISSUE TITLE
Increase limit for string format (actually max 9 args)

### ISSUE THREAD

**Issue by andreabusi** [icerockdev/moko-resources#472]
I got an issue because of a limit of the `format(args_:)` method, that could handle a max of 9 parameters.

Looking the code, I found that the args are manually mapped until 9 parameters, [here is the code](https://github.com/icerockdev/moko-resources/blob/09541e6e7956b1b8faffe10a7ead5a54085c0035/resources/src/appleMain/kotlin/dev/icerock/moko/resources/desc/Utils.kt#L79) I'm referring to.

Can I create a PR to increase this limit to 20 arguments? It would be very useful for us, because we have some big strings to manage inside our app.

**Comment by Alex009** [comment]
yes, create please.
also maybe try to use spread operator? current code old, maybe current kotlin/native version supports using of spread with objc interop

**Comment by andreabusi** [comment]
Any news about the PR? Do I need to perform some changes?

**Comment by andreabusi** [comment]
> Any news about the PR? Do I need to perform some changes?

Sorry don't mind. I didn't notice that you've already added the PR to the next milestone.
