### ISSUE TITLE
Library decomposition + configuration cache support

### ISSUE THREAD

**Issue by Pschsch** [icerockdev/moko-resources#474]
Currently, library does not support configuration cache. It's really bad and unconvenient, we know. And if we want to add support for it, we need to fully rewrite resources-generator plugin to support it. Project is rather complicated now for effective refactoring. Seems that project needs decomposition. But we also need to save support of current library API. Therefore, I suggest bunch of steps for effective project refactoring:
1. Decompose resources-generator plugin and resources lib by bunch of smaller plugins and libs for every type of resource. Examples of plugin's id's:
dev.icerock.mobile.multiplatform-resources-strings for string resources
dev.icerock.mobile.multiplatform-resources-colors for color resources, etc.
What advantages will we get:
1. Significatly increased maintainability: it will be much simplier for authors and community to explore project and make changes for specific resource which it's interested. Also, large refactoring works will be mush simplier to do
2. Separated scopes of usage: every community member will get a possibility to use only types of resources which they are interested without doing unnecessary work
What disadvantages:
1. Increased diffculty of connecting generating multiple resources types to their projects
Workaround: we could save moko-resources plugin and moko-resources libs as union of all smaller plugins (by applying all small plugins inside MultiplatformResourcesPlugin) and libs (via api dependencies)
After that, it will be much simplier to add configuration cache support for every small plugin. 
If you're intersted by this idea, i could try to add support for "future" multiplatform-strings plugin

**Comment by Alex009** [comment]
fix in #575

**Comment by ExNDY** [comment]
plugin was rewrited in 0.24.0, configuration cache supported started 0.24.0-alpha-3

**Comment by Alex009** [comment]
fixed in 0.24.0-beta-1
