### ISSUE TITLE
IOS pluralizedString issue

### ISSUE THREAD

**Issue by shaxzodshox** [icerockdev/moko-resources#476]
Build is failed when I try to build the project on XCode. It is showing: 

>Task :shared:compileKotlinIosX64 FAILED
Could not find "dev.icerock.moko-resources-cinterop-pluralizedString".......

Please help if someone knows how to resolve this issue..

**Comment by Alex009** [comment]
hi. here described problem - https://github.com/icerockdev/moko-mvvm/issues/230
i think you use also some other moko libraries, or some library that depends on old moko-resources. please update libraries to versions that use moko-resources 0.21+

**Comment by shaxzodshox** [comment]
I have been trying to fix it for about 2 days already. Now it is working perfectly fine. Thank you so much and all the best of luck in your future endeavors.

@Alex009
