### ISSUE TITLE
Example of yourframeworkproject ?

### ISSUE THREAD

**Issue by iadcialim** [icerockdev/moko-resources#482]
> Please replace :yourframeworkproject to kotlin project gradle path, and set correct relative path ($SRCROOT/../ in example).

I am clueless on this. What is `kotlin project gradle path` ?
Can help give example?

**Comment by Alex009** [comment]
check samples please https://github.com/icerockdev/moko-resources/tree/master/samples/ios-static-xcframework

**Comment by iadcialim** [comment]
thanks @Alex009  that worked
