### ISSUE TITLE
can't read UIImage of dev.icerock.moko.resources.ImageResource issue

### ISSUE THREAD

**Issue by harshakiran3** [icerockdev/moko-resources#483]
Getting the following error and then the app crashes.

Uncaught Kotlin exception: kotlin.IllegalArgumentException: can't read UIImage of dev.icerock.moko.resources.ImageResource@4bc1b080

**Comment by Alex009** [comment]
this mean that this method

https://github.com/icerockdev/moko-resources/blob/15fadd5ff058a967b0980daaebc48bb76e6cf465/resources/src/iosMain/kotlin/dev/icerock/moko/resources/ImageResource.kt#L14

return null.

https://developer.apple.com/documentation/uikit/uiimage/1624154-imagenamed

as described in apple docs - nil is about no image found. what image you try to use? maybe file corrupted someway?

**Comment by harshakiran3** [comment]
I was using 
`Icon(painter = painterResource(MR.images.icon_bottomnav_home),contentDescription = screen.title)`.
It is running fine in Android but when I run on xcode, it crashes giving the error as
Uncaught Kotlin exception: kotlin.IllegalArgumentException: can't read UIImage of dev.icerock.moko.resources.ImageResource@4bc1b080

**Comment by Alex009** [comment]
can you attach this svg file? and on what iOS version you try to run?

**Comment by msasikanth** [comment]
Hi, I was having the same issue and it seems to resolved with 0.22.2 version

**Comment by Alex009** [comment]
can you create reproducer from this template? https://github.com/icerockdev/moko-compose-multiplatform-ios-android-template

**Comment by msasikanth** [comment]
Umm, I mentioned it's resolved in the latest version 😅. I have it in this project
https://github.com/msasikanth/reader

**Comment by Alex009** [comment]
oh, sorry, i read incorrectly your previous message. cool that resolved!
@harshakiran3 for your case issue resolved too, or not?

**Comment by harshakiran3** [comment]
Hey @Alex009 The issue got resolved when I did invalidate cache and restart on Android studio and then clean build folder in XCode.

**Comment by Alex009** [comment]
so i think we can close this issue
