### ISSUE TITLE
update to kotlin 1.3.70

### ISSUE THREAD

**Issue by Alex009** [icerockdev/moko-resources#49]
1.3.70 released https://blog.jetbrains.com/kotlin/2020/03/kotlin-1-3-70-released/

**Comment by NahroTo** [comment]
What needs to be done in total?

**Comment by Alex009** [comment]
hi! I plan to update all MOKO libraries at once, at the moment, only ktor-client updates to 1.3.70 are missing. I think this week this update will be released and I will release updates to the MOKO libraries.

if you need moko-resources now, then i can update it in few next days

**Comment by Alex009** [comment]
in case of moko-resources we should just change version of kotlin here - 
https://github.com/icerockdev/moko-resources/blob/dbbdb13358b2787a28de06741a8c552d4e659b72/buildSrc/src/main/kotlin/Versions.kt#L12
and here - https://github.com/icerockdev/moko-resources/blob/dbbdb13358b2787a28de06741a8c552d4e659b72/buildSrc/build.gradle.kts#L16

then build it, check that all works, update readme, create realease to deploy

**Comment by NahroTo** [comment]
We will be using moko mvvm in proruction the next coming days and we are using 1.3.70. Will it work fine or should we wait until moko mvvm is updated to 1.3.70?

**Comment by Alex009** [comment]
kotlin/native not have backward compatibility, so we should use libs compiled with same version of kotlin...wait release of moko-resources and moko-mvvm with 1.3.70. i do it today for you

**Comment by Alex009** [comment]
@NahroTo moko-resources and moko-mvvm updated to kotlin 1.3.70
