### ISSUE TITLE
Support for dimensions xml

### ISSUE THREAD

**Issue by sunildhiman90** [icerockdev/moko-resources#507]
HI team, 

i can see, moko-resources provides support for all kind of resource and assets, but not for dimensions.
So are we planning to add support for dimensions as well or is there any workaround available to use dimensions?

Thanks

**Comment by Alex009** [comment]
dimensions is android's only feature. only on android resources have many qualifiers that allows to set flex config - one dimension name have different value on different screen sizes for example. on other platforms we not have analogs.
other platforms just use pixel density to convert sizes to px. 
ios have size classes, but not so flexible and not related to resources - it used in code or constraints setup.

so i suggest you to use `expect/actual` like:
```
expect Dimensions {
    val buttonHeight: Dp
    val smallPadding: Dp
}
```
and on actual for android - use android's dimens resources. in actual for iOS - use size classes by code. in actual for desktop/web - use constants or some that will resolve your task

**Comment by sunildhiman90** [comment]
Thanx, i will try this.
