### ISSUE TITLE
moko-compose-multiplatform-ios-android-template crashes at launch

### ISSUE THREAD

**Issue by moplat** [icerockdev/moko-resources#516]
Hi,

I'd love to use your template project with Compose and moko-resources but unfortunately I can't make it run fine because the resources aren't found either on the iOS simulator nor on my real iPad both running iOS 16.4.

I downloaded this repository : https://github.com/icerockdev/moko-compose-multiplatform-ios-android-template/ 
I'm on the main branch (latest commit : 7c015ca)

You're probably very familiar with this error message that I've seen around in other issues reported : 

![Capture d’écran 2023-06-23 à 17 20 22](https://github.com/icerockdev/moko-resources/assets/14849489/60a07ed0-b9f7-4014-93a2-f45f17c48f72)

I read the README file again and again trying to find something I might have missed, with no success. I looked into other issues in order to find a fix that might have been found already, again with no success.

I tried to add a new run script in the build phases in Xcode, based on what is said in the README : 

![Capture d’écran 2023-06-23 à 17 25 40](https://github.com/icerockdev/moko-resources/assets/14849489/614f29a5-695f-4829-a97e-249f6e3a698d)

But gradle can't find this task. I'm using an "old" Macbook pro from 2018 with an intel processor and Xcode version 14.3.1. Correct me if I'm wrong, this means that my simulator's architecture is X64. So I tried to change the task name by copyResourcesDebugExecutableIosX64 but still it doesn't work.

For information, here are the tasks gradle lists :

![Capture d’écran 2023-06-23 à 17 24 02](https://github.com/icerockdev/moko-resources/assets/14849489/f64a237b-1b40-40c1-a85c-a0c28fe835b9)

Do you have any idea ? Is there something I can try to make it work ? Does anybody else had this problem ?
Thank in advance !

**Comment by Alex009** [comment]
hi! you right, template crashes. i fix it now - moko-resources version update was required. now you can check template, all compiles and run.

<img width="1512" alt="image" src="https://github.com/icerockdev/moko-resources/assets/5010169/52057789-9115-4101-999e-5fd880b7a345">
here you can see what task required to run from xcode

**Comment by moplat** [comment]
Thank you so much ! It works perfectly, I can't wait to use it in my own project now :)
I wish I had thought about upgrading the version number earlier ... I spent all day trying to understand what was going on with my configuration.

Thanks again, for your quick answer and for all the good work you share with us !

**Comment by moplat** [comment]
Quick question, why didn't you upgrade to version 0.23.0 ?

**Comment by Alex009** [comment]
@moplat just miss it :) i will update it later
