### ISSUE TITLE
Project Compiled with problems

### ISSUE THREAD

**Issue by mohammadestk** [icerockdev/moko-resources#517]
After running jsBrowserRun
following error is shown:
Compiled with problems:X

Error:

Module not found: Error: Can't resolve 'fonts/Vazirmatn-Variable.ttf' in 'C:\Android\project\build\js\packages\project-webApp\kotlin'

desktop and android app runs without error. Only in web this error will show.

**Comment by Alex009** [comment]
what kotlin and moko-resources versions you use?

**Comment by mohammadestk** [comment]
> what kotlin and moko-resources versions you use?

Kotlin: 1.8.20
Moko-resources: 0.23.0

**Comment by ExNDY** [comment]
Please try 0.24.0-beta-5 after release
