### ISSUE TITLE
Error when building my project

### ISSUE THREAD

**Issue by xrofa** [icerockdev/moko-resources#52]
I get the following error:
`> Task :SDK:compileKotlinIos FAILED
w: skipping /Users/dev/.gradle/caches/modules-2/files-2.1/dev.icerock.moko/resources-iosx64/0.9.0/b3ee2c301a8ab2048c8261ebc92c854fa7698d6d/resources.klib. The abi versions don't match. Expected '[17]', found '22'

w: The compiler versions don't match either. Expected '[]', found '1.3.70-release'

e: Could not find "/Users/dev/.gradle/caches/modules-2/files-
2.1/dev.icerock.moko/resources-iosx64/0.9.0/b3ee2c301a8ab2048c8261ebc92c854fa7698d6d/resources.klib" in [/Users/dev/development/my-project/SDK, /Users/dev/.konan/klib, /Users/dev/.konan/kotlin-native-macos-1.3.61/klib/common, /Users/dev/.konan/kotlin-native-macos-1.3.61/klib/platform/ios_x6`

What might be happening?

**Comment by Alex009** [comment]
hello!
version 0.9.0 released with kotlin 1.3.70, but you try compile with kotlin 1.3.61. To use 0.9.0 you should update your project to 1.3.70
