### ISSUE TITLE
Problem with manual theme selection after Migrating from 0.20.1 to 0.23.0

### ISSUE THREAD

**Issue by kvillnv** [icerockdev/moko-resources#522]
Hello,

I have been using mokoresource since early versions.
In 0.23.0 `ColorResource.Themed `does not exist anymore, it is causing a regression in my Jetpack compose project.

Previously when the user was selecting manually their theme, for example selecting Light theme in the app while their device is in Dark theme, we would get the `ColorResource.Themed.light `or `ColorResource.Themed.dark `depending of if `MaterialTheme.colors.isLight`
This was done in one place for the whole app.

The method was:
```
@Composable
fun getColor(res: ColorResource.Themed): Color {
    val x = if (MaterialTheme.colors.isLight) res.light else res.dark
    return Color(x.red, x.green, x.blue, x.alpha)
}
```

Now, it is impossible to select the `.light `or `.dark`, so my guess was that moko now reads automatically the MaterialTheme when using a ColorResource (instead of previously using a ColorResource.Themed), but it is not the case. So this code below does not give me the theme manually selected. 
```
@Composable
fun getColor(res: ColorResource): Color {
    return Color(res.getColor(LocalContext.current))
}
```

The colors in the xml are still the same as before, they still have a light and dark tag, but it seems they cannot be read manually as it was done with ColorResource.Themed anymore. 
example:
```
<color name="textDefault">
        <light>@color/black</light>
        <dark>@color/white</dark>
    </color>
```

Is it supposed to work with my new implementation? Maybe it is a context issue?
How should I proceed?

Thanks

**Comment by Alex009** [comment]
hello!

old version of `ColorResource.Themed` was not resource-based, not works with platform colors logic. so it was extracted to [ColorDesc.Themed](https://github.com/icerockdev/moko-resources/blob/master/resources/src/commonMain/kotlin/dev/icerock/moko/resources/desc/color/ColorDescThemed.kt)
and you can use it.
but in this case in resource you should use not `light`/`dark` but just colors and then in code create `ColorDesc.Themed` with resolved colors.

but in your case i think is better to use overriding of context when you should use not system based DARK_MODE. 
something like:
```
val resources = resources
val config = resources.configuration
config.uiMode = if (!isNightModeOn) {
    Configuration.UI_MODE_NIGHT_NO
} else {
    Configuration.UI_MODE_NIGHT_YES
}
resources.updateConfiguration(config, resources.displayMetrics)
```

**Comment by kvillnv** [comment]
Thank you!

**Comment by OskarPersson** [comment]
I'm also struggling with this in my Jetpack Compose app. I previously only relied on `isSystemInDarkTheme()` to check for the theme but I now want the user to be able to control the app theme independently from the system theme.

@Alex009  Could you provide an example on how ColorDesc.Themed should be used in a Jetpack Compose app?
