### ISSUE TITLE
Integration with a multimodule project.

### ISSUE THREAD

**Issue by untalfranfernandez** [icerockdev/moko-resources#528]
Hi, I've been trying to integrate Moko resources with a Multiplatform project I'm working on, but I haven't been able to do it so far.

Our project contains multiple Gradle modules, one of which is the one that will contain all the string resources, and there is another one, which is the one I'm using to export some of the other modules into an Apple XCFramework.

As the module doing all the linking does not have the Moko plugin being applied, I haven't found a way to export the resources; some of the `copy` Gradle tasks are absent.

Can I achieve what I'm trying to do? Is there any other setup that I could try?

**Comment by Alex009** [comment]
Just apply plugin in module that compiles into framework.

**Comment by untalfranfernandez** [comment]
Oh, yeah, that makes sense. Thank you. (Closing this)
