### ISSUE TITLE
Help to get localization to work on iOS

### ISSUE THREAD

**Issue by mediavrog** [icerockdev/moko-resources#53]
Hi, I setup the library according to the documentation in version 0.9.0 and kotlin 1.3.70.

Now on Android, everything works as expected and I can localize my strings. On iOS though, only the translation key is displayed.

> shared lib build.gradle.kts
```kotlin
kotlin {
    //select iOS target platform depending on the Xcode environment variables
    val iOSTarget: (String, KotlinNativeTarget.() -> Unit) -> KotlinNativeTarget =
        if (System.getenv("SDK_NAME")?.startsWith("iphoneos") == true)
            ::iosArm64
        else
            ::iosX64

    iOSTarget("ios") {
        binaries {
            framework {
                baseName = "MyLibShared"
                export("dev.icerock.moko:resources:${Versions.Libs.MultiPlatform.mokoResources}")
            }
        }
    }
}
...
multiplatformResources {
    multiplatformResourcesPackage = "jp.mylib.shared"
}
```

I verified the framework is correctly created and contains the localized files:
![Screen Shot 2020-04-01 at 11 59 11](https://user-images.githubusercontent.com/160785/78094731-396d8900-7410-11ea-8272-75fd48a375ce.png)

I tried a coupl of approaches to get the string:

```swift
// in swift; does not work
Localizer().getMyString().localized() // displays "my_string"
// shared code in iosMain: Localizer object: fun getMyString(): StringDesc = StringDesc.Resource(MR.strings.my_string)

// in swift; does not work; unresolved StringDesc
StringDesc.Resource(MR.strings.my_string).localize()

// in swift; this works though, so the files are loaded
NSLocalizedString("my_string", tableName: nil, bundle: Bundle(identifier: "jp.mylib.shared.MyLibShared")!, value: "", comment: "") // displays "My String!"
```

Do you have an idea on what the issue could be? Any pointer?

**Comment by Alex009** [comment]
hello! thanks for feedback!

in your case you not properly configure `export` of library. Kotlin/Native require use in `export` function platform artifact. so you should use
`export("dev.icerock.moko:resources-iosx64:${Versions.Libs.MultiPlatform.mokoResources}")` on x64 and
`export("dev.icerock.moko:resources-iosarm64:${Versions.Libs.MultiPlatform.mokoResources}")` on Arm64

**Comment by mediavrog** [comment]
Thank you for your quick reply. It worked like a charm!
