### ISSUE TITLE
SVGs failing to resolve

### ISSUE THREAD

**Issue by maxwellvogel** [icerockdev/moko-resources#532]
SVGs are being properly generated, and can be used on the iOS side.  However, building for Android fails as the SVG resources are unresolved:
`e: file:///Users/maxvogel/Dropbox/Mac/Desktop/Mtec%20Results/Repos/Results_App_Kotlin/shared/build/generated/moko/androidMain/src/com/mtecresults/resultsapp/SharedResources.kt:246:34 Unresolved reference: icon_transportation_button`
Weirdly, IDE shows them as resolving:
<img width="857" alt="Screenshot 2023-07-21 at 12 55 30 PM" src="https://github.com/icerockdev/moko-resources/assets/94268013/7bf0953b-cfe8-4da2-b4cd-135900054a69">

Seems to similar to what was described in:
https://github.com/icerockdev/moko-resources/issues/29#issuecomment-1484528343

I apologize if I am missing anything.

moko-resources v23, AGP 7.4.2, Gradle 7.5

**Comment by MarkRS-UK** [comment]
Seeing this here too, partially.  Some svgs are working and others not, although all shown resolving by the IDE.
I notice the failures are smaller files, nothing else appears different.

**Comment by tdiego95** [comment]
Same here, some pngs in my case are not working.

`/shared/build/generated/moko/androidMain/src/com/suitme/MR.kt:116:76 Unresolved reference: logo_white`

<img width="899" alt="Screenshot 2023-10-13 at 12 02 24" src="https://github.com/icerockdev/moko-resources/assets/31563910/60b136c4-54bc-4c08-b9c6-2d5bc045c3df">

**Comment by ExNDY** [comment]
will be fixed in 0.24.0, please check in 0.24.0-alpha-6

**Comment by Alex009** [comment]
should be fixed in 0.24.0-beta-1
