### ISSUE TITLE
Method too large: game/MR$images.<clinit> ()V

### ISSUE THREAD

**Issue by tujiu** [icerockdev/moko-resources#534]
I have a kotlin multiplatform project with around 4000+ images and 1000+ strings. While compiling I got this error message:
`exception: java.lang.RuntimeException: Error generating class file game/MR$images.class (compiled from [/Users/kenny/projects/compose-multiplatform-template/shared/build/generated/moko/desktopMain/src/game/MR.kt]): Method too large: game/MR$images.<clinit> ()V`

Is there a way to split MR class?

**Comment by Alex009** [comment]
hi!
separate resources to multiple gradle modules

**Comment by tujiu** [comment]
hi, 
Thanks, That works.
