### ISSUE TITLE
Not found command copyFrameworkResourcesToApp !

### ISSUE THREAD

**Issue by FelixFalkovsky** [icerockdev/moko-resources#536]
"$SRCROOT/../" :shared:copyFrameworkResourcesToApp  not found copyFrameworkResourcesToApp in shared

**Comment by Alex009** [comment]
`copyFrameworkResourcesToApp` task will be created only if you use static framework (`isStatic = true`). if framework dynamic - this task not created and not should be used

**Comment by FelixFalkovsky** [comment]
Thanks
