### ISSUE TITLE
The MR folder shared for SwiftUI.

### ISSUE THREAD

**Issue by FelixFalkovsky** [icerockdev/moko-resources#539]
The MR folder after being added should be gray but not blue, does this mean that we have not scanned it ? It should be done by a script ?

Will the previews(Canvas) work ?

<a href="https://ibb.co/9NxHrK2"><img src="https://i.ibb.co/9NxHrK2/2023-07-31-12-23-22.png" alt="2023-07-31-12-23-22" border="0"></a>

**Comment by Alex009** [comment]
MR not should be inside pods directory at all.
something in your config invalid.

preview works.

**Comment by FelixFalkovsky** [comment]
I reread the config link "Configured sample you can see in samples/kotlin-ios-app " and made the changes. Now the folder is created s Fraemworks -> shared -> Headers .

```swift 
 extraSpecAttributes["resources"]` = "'build/cocoapods/framework/shared.framework/*.bundle'"
 ```

```kotlin
framework {
            baseName = "shared"
            isStatic = true
        }
```

**Comment by FelixFalkovsky** [comment]
> MR not should be inside pods directory at all. something in your config invalid.
> 
> preview works.

That confirmed that the naitroika was done wrong. Thank you.
