### ISSUE TITLE
Wrong size of images/icons in SVG format for desktop

### ISSUE THREAD

**Issue by sawil314** [icerockdev/moko-resources#551]
Hi, 
When I paste an SVG as an Icon or Image, the icon/image is distorted on the Desktop. On Android, on the other hand, it looks as it should.

Desktop:
![desktopbutton](https://github.com/icerockdev/moko-resources/assets/79279490/0b202dbf-e1ac-4f7f-a257-d624f3e3423c)
Android:
![androidbutton](https://github.com/icerockdev/moko-resources/assets/79279490/f1bdd2a6-1c8a-4ff4-8c29-3250e751e11f)
Code:
```
fun ExampleButton(
    iconResource: ImageResource,
    onClick: () -> Unit,
) {
    Button(
        onClick,
        modifier = Modifier.size(width = 200.dp, height = 100.dp),
        colors = ButtonDefaults.buttonColors(containerColor = Color.Blue)
    ) {
        Icon(
            painterResource(iconResource),
            contentDescription = null,
            modifier = Modifier.size(48.dp)
        )
        Text(
            text ="Test",
            textAlign = TextAlign.Center,
            modifier = Modifier.align(Alignment.CenterVertically).fillMaxWidth()
        )
    }
}
```
The svg files is this one, but happens with other ones too:
https://fontawesome.com/icons/cloud?f=classic&s=solid

**Comment by ExNDY** [comment]
Should be fixed in 0.24.0
