### ISSUE TITLE
Error when kotlin.version=1.9.0 and compose.version=1.4.3

### ISSUE THREAD

**Issue by lijianqiang12** [icerockdev/moko-resources#557]
e: file:....../MR.kt:12:22 Expected object 'MR' has no actual declaration in module <shared_debug> for JVM

**Comment by daniaviladomingo** [comment]
Same for me

**Comment by akelix** [comment]
Same problem

**Comment by bcmedeiros** [comment]
Duplicated of https://github.com/icerockdev/moko-resources/issues/531

**Comment by sunildhiman90** [comment]
I also have this issue, but this solution is working for me for android: https://github.com/icerockdev/moko-resources/issues/531#issuecomment-1672799869

but i am also facing other isssues in iOS and web as well as mentioned here: https://github.com/JetBrains/compose-multiplatform/issues/3603#issuecomment-1704076320

**Comment by ExNDY** [comment]
will be fixed in 0.24.0, please check in 0.24.0-alpha-6

**Comment by Alex009** [comment]
should be fixed in 0.24.0-beta-1
