### ISSUE TITLE
Issue with MOKO Resource Library: Images Directory Not Generated for Compose Multiplatform

### ISSUE THREAD

**Issue by hodakl099** [icerockdev/moko-resources#579]
While the build process seems to work seamlessly for string resources, I am encountering an issue with the generation of the images directory.

Directory Structure:

```
-resources 
--MR 
---ar
---base
---images
----splash.png
```
Observations:

The strings resource directory is generated correctly, and I can access the string resource IDs without any issues. The images directory, however, does not seem to be generated successfully during the build process. I attempted to resolve the issue by downgrading the MOKO dependency, but this did not yield any positive results. Steps Taken:

I have meticulously followed the official MOKO documentation to ensure correct implementation. I would greatly appreciate any insights or suggestions to address this problem. Has anyone else encountered a similar issue, and if so, please help.

**Comment by Alex009** [comment]
Hi. You use invalid naming for images. Check in readme - PNG and jpg should have @Nx postfix for scale. Without postfix can be only svg

**Comment by hodakl099** [comment]
i think instead of giving run time errors, warning should be fine i guess, Anyways, Thanks!
