### ISSUE TITLE
How to use in non-KMM compose multiplatform project?

### ISSUE THREAD

**Issue by gotson** [icerockdev/moko-resources#580]
Hello,

i am interested in using this project for string localization, my project is JVM only compose-multiplatform.

I have added the following in the plugins block (Gradle Kotlin Script):

```kts
plugins {
  ...
  id("dev.icerock.mobile.multiplatform-resources") version "0.23.0"
}
```

And in my `dependencies`:

```kts
dependencies {
  ...
  implementation(compose.desktop.common)
  api("dev.icerock.moko:resources-compose:0.23.0")
  ...
```

I have added this in my `build.gradle file`:

```kts
multiplatformResources {
  multiplatformResourcesPackage = "org.gotson.komga"
  multiplatformResourcesSourceSet = "main"
}
```

However i don't see any task `generateMainMR` in my project.

I'm supposed i'm missing something, but what ?

Any help would be appreciated !

**Comment by Pschsch** [comment]
You could create kotlin multiplatform library module and add it as dependency to your pure jvm project. Did you try to achieve it this way?

**Comment by gotson** [comment]
> You could create kotlin multiplatform library module and add it as dependency to your pure jvm project. Did you try to achieve it this way?

I would prefer to avoid going such ways.

**Comment by Pschsch** [comment]
The same approach officialy used by Jetbrains in KMM apps for android and ios. So, i think, there is nothing bad use the same approach on pure JVM, i think
