### ISSUE TITLE
iOS App Crash due to ImageResource Type Mismatch - XCode 15

### ISSUE THREAD

**Issue by Dardev12** [icerockdev/moko-resources#583]
**Description:**
While running the iOS application, I encountered an error that prevents the app from functioning correctly. The error message is as follows:

`Key path value type 'shared.ImageResource' cannot be converted to contextual type 'iosLandApp.ImageResource'`

**Expected Result:**
The iOS application should run without any interruptions or crashes.

**Additional Notes:**

- The images being used are in PNG format (e.g., test@3x.png).
- The code snippet where the error occurs is:

```
Button(action: {
    selection = "Profil"
}) {
    Image(resource: \.backiconlight)
        .foregroundColor(Color.textColor)
        .font(.headline)
}
extension Image {
    init(resource: KeyPath<SharedRes.images, ImageResource>) {
        self.init(uiImage: SharedRes.images()[keyPath: resource].toUIImage()!)
    }
}
```

**Environment Details:**

_Xcode Version:_ 15
_Gradle Setup:_

- CocoaPods is used for KMM.
- In the shared module:

```
{
    framework {
        baseName = "shared"
        export("dev.icerock.moko:resources:0.23.0")
        export("dev.icerock.moko:graphics:0.9.0")
        isStatic = true
    }
    extraSpecAttributes["resources"] = "['src/commonMain/resources/**', 'src/iosMain/resources/**']"
    extraSpecAttributes["exclude_files"] = "['src/commonMain/resources/MR/**']"
}
multiplatformResources {
    multiplatformResourcesPackage = "com.dardev.land" // required
    multiplatformResourcesClassName = "SharedRes"
    disableStaticFrameworkWarning = true
}
```
In the project:
`classpath("dev.icerock.moko:resources-generator:0.23.0")`

**Comment by alaegin** [comment]
I have the same issue

**Comment by Dardev12** [comment]
Solution i have try actually but doesn't work : 
- Update Cacaopod ( Kdoctor to verify if my  KMM env is good )
- Clean & Rebuild the Kmm & IOS

```
[v] Android Studio
    Android Studio (2022.3)
    Location: /Applications/Android Studio.app
    Bundled Java: openjdk 17.0.6 2023-01-17
    Kotlin Plugin: 223-1.8.0-release-345-AS8836.35.2231.10406996
    Kotlin Multiplatform Mobile Plugin: 0.6.1(223)-18
    
[v] Xcode
    Xcode (15.0)
    Location: /Applications/Xcode.app
    
[v] Cocoapods
    ruby (ruby 2.7.6p219 (2022-04-12 revision c9c2245c0a) [arm64-darwin22])
    
    ruby gems (3.4.18)
    
    cocoapods (1.13.0)
    
    cocoapods-generate (2.2.4)
```
if this can help you @alaegin

**Comment by Dardev12** [comment]
any News on the resolution of this issue ?

**Comment by elkabelaya** [comment]
What helped me is to change 
```init(resource: KeyPath<SharedRes.images, ImageResource>) {```
to 
```init(resource: KeyPath<SharedRes.images, shared.ImageResource>) {```

**Comment by Dardev12** [comment]
I have try that solution in the past and now i understand my error , i used so many component who call KeyPath<SharedRes.images, ImageResource> and i have fix it and it Work.

Thank to you @elkabelaya ❤️

**Comment by Dardev12** [comment]
I close this issue now the problem is solve
