### ISSUE TITLE
moko-resources lib is not getting correct language (iOS only)

### ISSUE THREAD

**Issue by casaflowa** [icerockdev/moko-resources#587]
I my app I have two translations for base (en) and de.
Although my preferred language on iOS is de_DE, moko displays all text in english.
On Android on the other hand it's working fine.
Calling NSLocale.currentLocale => en_DE
Calling NSLocale.preferredLanguages().first() => "de_DE"
Is there a way to tell moko which locale to use?

PS: On iOS Simulator it's even stranger, the first call of stringResouces() works fine, on all other occurrences the key is displayed.

**Comment by JP-Labs** [comment]
How did you solve this. I have the same issue? base (en) and de.
