### ISSUE TITLE
ld: unknown options: -sdk_version

### ISSUE THREAD

**Issue by storytellerF** [icerockdev/moko-resources#588]
build samples/compose-resources-gallery failed.

full log:
> Task :macosApp:linkDebugExecutableMacosArm64
e: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ld invocation reported errors

>The /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ld command returned non-zero exit code: 1.
output:
-macosx_version_min has been renamed to -macos_version_min
ld: unknown options: -sdk_version

**Comment by storytellerF** [comment]
**kotlin-ios-app** have same error. And **ios-static-xcframework** build success.

**Comment by codlab** [comment]
The environment for kotlin needs to be bumped. Both kotlinVersion & composeVersion needs to be updated. You can find and edit the catalog version file in the gradle folder with the proper values

more information @ https://github.com/JetBrains/compose-multiplatform/releases
