### ISSUE TITLE
Support multiple strings files

### ISSUE THREAD

**Issue by mediavrog** [icerockdev/moko-resources#59]
In Android development, it is quite convenient for larger apps to separate string resources by module/logical unit. Sample would be a common `strings.xml`, and then `strings-about.xml`, `strings-settings.xml` etc.

It would be great for moko resources to support this as well, as it helps organize strings in larger apps with lots of strings.

**Comment by Alex009** [comment]
hi! thanks for request, it will be good feature

**Comment by Alex009** [comment]
merged, will be available in 0.10.0
