### ISSUE TITLE
Make converting svg to xml drawable optional

### ISSUE THREAD

**Issue by rustamsmax** [icerockdev/moko-resources#591]
Converting SVG to xml drawable is not good except icon svgs
There are SVGs with rich content witch losses it's quality when converted to xml drawable

**Comment by Alex009** [comment]
hi. as i know android not support svg without conversation - https://developer.android.com/studio/write/vector-asset-studio
you know how pass svg to android?

**Comment by rustamsmax** [comment]
For android I'm using coil svg decoder

**Comment by Alex009** [comment]
so you can just move your images to files/assets directory and use with coil svg decoder.
images folder generates android drawable, there can't be just svg

**Comment by rustamsmax** [comment]
@Alex009 But I want at the same time on iOS target use a UIImage generated in the Assets catalog with preserves-vector-representation set to true.

**Comment by rustamsmax** [comment]
Suppose using coil3 we won't need moko images any more

**Comment by OskarPersson** [comment]
I'm having the same problem as @rustamsmax Is coil3 the way to go here or is there a way to disable the conversion for Android only? @Alex009
