### ISSUE TITLE
ImageResource cannot be resolved

### ISSUE THREAD

**Issue by kostapostolakis** [icerockdev/moko-resources#592]
I used the suggested extension to get images but I get the following error.
<img width="1353" alt="Screenshot 2023-10-30 at 11 09 41 PM" src="https://github.com/icerockdev/moko-resources/assets/38695239/bd4667d1-60f1-4eff-ad6c-c331276af76e">

After searching I realized that the class ImageResource is duplicated and it is used also in SwiftUI, as you can see below.
<img width="1195" alt="Screenshot 2023-10-30 at 11 08 19 PM" src="https://github.com/icerockdev/moko-resources/assets/38695239/156d3459-13e2-461e-8e08-c858dfdea06a">

Do we have a solution to this?

**Comment by Ustimov** [comment]
If your problem is only the class name then you can prepend it with your framework name. E.g. `Shared.ImageResource`

**Comment by kostapostolakis** [comment]
Perfect! It works! Thank you!
