### ISSUE TITLE
Missed camelCase in R class

### ISSUE THREAD

**Issue by SrgGrch** [icerockdev/moko-resources#60]
When I add some resources in multiplatform resources with camel case key, e.g. testTest, when, after that, I try to access it from R class or from XML I find string testtest. So the question is why is camelCase is missing after generation and how can I fix that behavior?

**Comment by Alex009** [comment]
hello! 
recently we fix #46 and set lowercased keys for all android resources...but i see that for strings it acceptable way - we should lowercase only filebased resources.
it will be fixed

**Comment by Alex009** [comment]
start from 0.10.0 Strings and Plurals on android can have camelCase ids.
Files, Fonts, Images is filebased resources and can't have uppercased chars
