### ISSUE TITLE
`stringResource(resource: StringResource): String` doesn't work with compose multiplatform js target

### ISSUE THREAD

**Issue by ISNing** [icerockdev/moko-resources#602]
When i start js browser run, the console alerts `IrLinkageError` with message `Function 'stringResource' can not be called: No function found for symbol 'dev.icerock.moko.resources.compose/stringResource|stringResource(dev.icerock.moko.resources.StringResource;androidx.compose.runtime.Composer?;kotlin.Int){}[0]'` and leave me with blank browser view.

But desktop target and android target both work well

It‘s a simple demo like this:
```
val myString = stringResource(MR.strings.my_string)
Text(myString)
```

**Comment by ISNing** [comment]
It fixed after I run `gradle clean` to clean the project build

**Comment by sunildhiman90** [comment]
I m also getting this error now with compose 1.6.1, And its not working even after clearing build.
