### ISSUE TITLE
Document the export necessary to work on iOS in the readme

### ISSUE THREAD

**Issue by dalewking** [icerockdev/moko-resources#61]
In Issue #53 we learn that there is an extra export statement that is necessary to get this to work on iOS. After losing an entire day trying to figure out why this was not working on iOS, I think it should definitely be documented in the README

**Comment by Alex009** [comment]
hi! 
I'm sorry that you had to spend time looking for a resolution of problem.
We already document in in README - https://github.com/icerockdev/moko-resources#faq
As i see it not help you, maybe you suggest where it should be documented?

**Comment by dalewking** [comment]
At least mention it in the Installation section with a reference to the FAQ section. Most people are going to be like us and read the installation section and think that is all there is.

**Comment by dalewking** [comment]
I have applied the suggestion in the FAQ but it made no difference, I still only get the localization keys

**Comment by dalewking** [comment]
I did figure it out and get it working

**Comment by Alex009** [comment]
start from 0.10.0 `export` not required.
it was changed by #64 and #65 so we just remove requirement and will not add new info to docs
