### ISSUE TITLE
Xcode 15 : Key path value type 'shared.ImageResource' cannot be converted to contextual type : Invalid redeclaration of 'init(_:)'

### ISSUE THREAD

**Issue by burf2000** [icerockdev/moko-resources#611]
So I have been building a KMP app in xcode 14 and life has been great, I then updated OS without realising it would force me to xcode 15.  

The project no longer builds.  I have moved all the libraries to the latest etc.

The main error I am getting is
`Key path value type 'shared.ColorResource' cannot be converted to contextual type 'APP.ColorResource'`

**Comment by datnymph** [comment]
@burf2000 how exactly was this completed? I am having a similar issue.
