### ISSUE TITLE
copyFrameworkResourcesToApp on kotlin 1.9.20 invalid works with cocoapods

### ISSUE THREAD

**Issue by Alex009** [icerockdev/moko-resources#612]
At xcode 15 and kotlin 1.9.20, with cocoapods integration and `isStatic = true` for framework i see that after call `copyFrameworkResourcesToApp` will be called `podspec` task that override already valid compiled kotlin files in `build/cocoapods/framework/shared.framework` to placeholder. after this in xcode i got all red kotlin classes, just like they not exist.

**Comment by Ustimov** [comment]
Duplicate of https://github.com/icerockdev/moko-resources/issues/387

**Comment by msa1422** [comment]
@Alex009 Can you please elaborate the steps or link some article of adding the bundles directly? As a beginner in Xcode, I am unable to understand the steps via the image that you have provided.

**Comment by ExNDY** [comment]
will be fixed in 0.24.0, please check in 0.24.0-alpha-5

**Comment by Alex009** [comment]
fixed in 0.24.0-beta-1
