### ISSUE TITLE
How to custom the actool minimum-deployment-target

### ISSUE THREAD

**Issue by skytoup** [icerockdev/moko-resources#619]
https://github.com/icerockdev/moko-resources/blob/6b320c12e07e57c866d787841e8a5b41c583808d/resources-generator/src/main/kotlin/dev/icerock/gradle/generator/apple/action/PackResourcesToKLibAction.kt#L47C2-L47C2

How to change the `minimum-deployment-target` via build.gradle?

I've found that `minimum-deployment-target` with 9.0 packages a larger resource file than with higher versions, and using 16.0 in my project will reduce the size from 70MB to 19MB.

**Comment by Alex009** [comment]
fixed in 0.24.0-beta-1
