### ISSUE TITLE
Add a StringDesc type that is a wrapper transform

### ISSUE THREAD

**Issue by dalewking** [icerockdev/moko-resources#62]
I have a case where I want to return something like a StringDesc to the UI so that it only has to call localized or toString(context) but where a transformation is ran on the result. The particular case is I have a String defining a date format and the transformation I want to run is use that format as an argument to a format call. I want to define that in common code so it does not know about loacalized or toString(context) and I don't want the code that receives it to have to call the format method.

I would try to define it myself but the fact that StringDesc is sealed makes that impossible

So what I am proposing is a map extension method on StringDesc. So I envision this in the common code:

    return MR.strings.my_date_format.desc().map { myDate.format(it).desc() }

So in StringDesc you would need a new class:

    class Mapped(stringDesc: StringDesc, transform: (String) -> StringDesc) : StringDesc

You would need extension methods on StringDesc:

    fun StringDesc.map(transform: (String) -> StringDesc) = StringDesc.Mapped(this, transform)

And then the Android implementation might be:

     actual data class Mapped actual constructor(
         val stringDesc: StringDesc,
         val transform: (String) -> StringDesc
     ) : StringDesc() {
         override fun toString(context: Context) =
            stringDesc.toString(context).let(transform).toString(context)
     }

**Comment by dalewking** [comment]
As a convenience would be nice to also have:

    fun StringDesc.map(transform: (String) -> String) = StringDesc.Mapped(this, { { transform(it).desc })

**Comment by dalewking** [comment]
Another alternative is just remove sealed from StringDesc and then I can do it on my own

**Comment by Alex009** [comment]
@dalewking hello! thanks for feedback!
i will try to change `StringDesc` implementation to interface with companion object extensions like this https://github.com/icerockdev/moko-widgets/pull/234/files#diff-3cb3abd88c590c7b205f70d676e2f5a7 
it will allow extension of `StringDesc` functional

**Comment by Alex009** [comment]
@dalewking hi! check this mergerequest - #71
is this changes allow you do what you want?

**Comment by dalewking** [comment]
I think it should work for what I want

**Comment by Alex009** [comment]
merged, will be released in 0.10.0
