### ISSUE TITLE
Nested generated ttf font object

### ISSUE THREAD

**Issue by JahonovAsilbek** [icerockdev/moko-resources#630]
I put ttf fonts in resource folder. When I build, it generating separate objects for each font

```
public object fonts : ResourceContainer<FontResource> {

    public object regular {
      public val regular: FontResource
    }

  }
```
And I had to call it `fontFamily = fontFamilyResource(fontResource = MR.fonts.regular.regular)`

**Comment by Alex009** [comment]
what version you use and what name of font file you use?

**Comment by JahonovAsilbek** [comment]
> what version you use and what name of font file you use? @Alex009 

I am using "0.23.0" version and this is my fonts:

![image](https://github.com/icerockdev/moko-resources/assets/60385044/dea1150c-c5b1-4d82-9580-241a6e3dfbaa)

**Comment by Alex009** [comment]
Please check fonts block in readme
