### ISSUE TITLE
IOS side has multiple MR (MR_, MR__, etc...) in a multi-module project. 

### ISSUE THREAD

**Issue by shaxzodshox** [icerockdev/moko-resources#645]
What is the recommended way to use moko-resources in a multi-module setup? In my project I have multiple multiplatform modules (usually split by feature) and then I’m using the umbrella framework approach to integrate them into iOS as a single framework. The problem is that when I use moko-resources on more than one module I end up with multiple MR_, MR__, etc on the IOS side. What’s the recommended approach with this setup?

**Comment by Alex009** [comment]
hi.
use custom class name in each module or set visibility of generated class to internal
