### ISSUE TITLE
File generation

### ISSUE THREAD

**Issue by DeeChael** [icerockdev/moko-resources#654]
I followed the steps in README and i found it generated the MR file under build/generated/moko/{my project packages} directory, but i cant access it from my code:
![image](https://github.com/icerockdev/moko-resources/assets/63186003/5d7aa5d5-18ff-4747-8f8e-02e2375417ae)
And when reloading script, it shows: MR file generation for iOS is not supported on your system!

**Comment by Alex009** [comment]
>MR file generation for iOS is not supported on your system!

seems that you use not macOS. so for iOS part generation can't be done
