### ISSUE TITLE
Cannot generate xml drawable resources

### ISSUE THREAD

**Issue by sameershelar-paypay** [icerockdev/moko-resources#657]
I m trying to use `moko-resources` library in my KMM library. I want to use the resources inside the Compose Multiplatform code.
I was able to share the text resources successfully but when I m trying to share the xml drawable resource the class is not getting generated.

I m storing the xml resources inside the MR > images package.

Are xml drawable resources supported? Am I using it the right way?

<img width="462" alt="Screenshot 2024-03-19 at 12 50 02" src="https://github.com/icerockdev/moko-resources/assets/156782717/e9b074a3-cc7a-4492-815d-33a76cf36c92">
<img width="522" alt="Screenshot 2024-03-19 at 12 56 57" src="https://github.com/icerockdev/moko-resources/assets/156782717/d545577f-2dbf-47dd-8698-0660658faebb">

**Comment by ExNDY** [comment]
Please, read Readme: [Features](https://github.com/icerockdev/moko-resources?tab=readme-ov-file#features) they has all info about plugin

**Comment by Alex009** [comment]
xml drawables not supported. you can use compose-multiplatform-resources for xml drawables.

we use png, jpg and svg
