### ISSUE TITLE
Desktop Image Assets not generating

### ISSUE THREAD

**Issue by Ammar-Ishfaq** [icerockdev/moko-resources#662]
**Hello**, my desktop assets are not generating successfully could anyone please let me know why it's not working for the desktop (image assets)

![image](https://github.com/icerockdev/moko-resources/assets/54596139/498a39dd-26ed-4810-8fd3-2748889820ba)

The error I'm getting:
```

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':composeApp:generateMRdesktopMain'.
> For input string: "ic_resistor"
```

**Comment by ExNDY** [comment]
Please read Readme and check samples. Your file hierarchy on screen - invalid for plugin

**Comment by Ammar-Ishfaq** [comment]
I just read the document, but I didn't see the part about desktop hierarchy. Could you guide me to the section or maybe share a screenshot?

**Comment by ExNDY** [comment]
Just open any sample with jvm target, many resources had in compose-gallery sample. Why u think about hierarchy difference between any targets, i'm say when your hierarchy of resources incorrect.
<img width="249" alt="Снимок экрана 2024-04-17 в 14 17 14" src="https://github.com/icerockdev/moko-resources/assets/22731300/6a5a792c-9fab-47d9-9b0f-06b77a554d1a">
Inside resources, main directory for resources will be changed in 0.24.0, but inner hierarchy will remain

In readme for images:
https://github.com/icerockdev/moko-resources?tab=readme-ov-file#example-7---shared-images
Without drawable or any folders

**Comment by Ammar-Ishfaq** [comment]
Thank you for your response; it's really helpful in resolving this.
