### ISSUE TITLE
Display image in swift ui

### ISSUE THREAD

**Issue by the-best-is-best** [icerockdev/moko-resources#664]
import SwiftUI
import shared

extension Image {
    init(resource: KeyPath<SharedRes.images, ImageResource>) {
        self.init(uiImage: SharedRes.images()[keyPath: resource].toUIImage()!)
    }
}

Reference to member 'toUIImage' cannot be resolved without a contextual type

**Comment by ExNDY** [comment]
it problem with intersection of names. Apple has ImageResource ([https://developer.apple.com/documentation/developertoolssupport/imageresource](https://developer.apple.com/documentation/developertoolssupport/imageresource)), if you change code like this:
`
init(resource: KeyPath<SharedRes.images, MultiPlatformLibrary.ResourcesImageResource>) {
    let test = SharedRes.images()[keyPath: resource]
    self.init(uiImage: SharedRes.images()[keyPath: resource].toUIImage()!)
  }
}
`
you get correct resources type and resource.

**Comment by darronschall** [comment]
Related to #519; I'll update my sample code there as well to help prevent this in the future.
