### ISSUE TITLE
 Use with redwood

### ISSUE THREAD

**Issue by syxc** [icerockdev/moko-resources#670]
Without using Compose Multiplatform (iOS will increase the size of .ipa package by more than 20M when using it), is it possible to use String and other resources directly in the commonMain of the shared module, e.g. combining with redwood to realize UI sharing in commonMain (iOS, Android, etc.) will need to use String, Image and other resources? For example, if we combine [redwood](https://github.com/cashapp/redwood) to realize UI sharing in commonMain (iOS, Android, etc.), we will need to use String, Image and other resources.

**Comment by Alex009** [comment]
Yes you can. moko resources can be used with any UI.

Redwood sample here https://github.com/icerockdev/redwood-sample

**Comment by syxc** [comment]
> Yes you can. moko resources can be used with any UI.
> 
> Redwood sample here https://github.com/icerockdev/redwood-sample

Thanks！  
Please see this discussion https://github.com/icerockdev/moko-resources/discussions/671
