### ISSUE TITLE
Symbol "\n" doesn't work in iOs in 0.24.0-beta-1

### ISSUE THREAD

**Issue by piskunovvitaly** [icerockdev/moko-resources#673]
After upgrading moko-resources from 0.23.0 to 0.24.0-beta-1, I faced a problem that symbol "\n" doesn't work properly. It just shows in places where there should be line breaks.
![Снимок экрана 2024-04-19 в 23 21 11](https://github.com/icerockdev/moko-resources/assets/92299905/a954d893-26f1-4c88-8b3d-bb5c454dbb2b)

**Comment by ExNDY** [comment]
will be fixed in #677

**Comment by ExNDY** [comment]
will be fixed in 0.24.0-beta-2
