### ISSUE TITLE
The application is crashing on iOS due to painterResource

### ISSUE THREAD

**Issue by piskunovvitaly** [icerockdev/moko-resources#676]
After upgrading moko-resources from 0.23.0 to 0.24.0-beta-1, I faced a problem where iOS applications crash on startup due to an issue with painterResources. This problem only occurs after archiving and uploading the application to the store. Local builds are not affected. 
Small information about modules: I have one module with ui stuff, like icons, fonts and etc., with mokoResources library with visibility equals public. This module I connect to my feature modules that also contains mokoResources with visibility private and crash happens in this feature modules.

AGP: 8.1.1
kotlin: 1.9.23
Compose Multiplatform: 1.6.10-beta01
The iOS version doesn't matter. The issue reproduces on different versions.

![Снимок экрана 2024-04-20 в 14 51 45](https://github.com/icerockdev/moko-resources/assets/92299905/45e03b37-18d1-4fdf-9581-741d98ae95e9)

**Comment by Alex009** [comment]
@piskunovvitaly can you show also text of exception?

also, please check on clean builds on local.

also, please check did you add moko-resources plugin in gradle project that compile ios framework?

also, please check did you add build script in xcode build phases? (if you use static framework)

**Comment by Alex009** [comment]
and maybe you can create project reproducer?

**Comment by Alex009** [comment]
maybe related to https://github.com/icerockdev/moko-resources/issues/680

also can you check is crash only on dark theme?

**Comment by Alex009** [comment]
i think it was fixed in #674
