### ISSUE TITLE
Generate iOS resources failed due to dev.icerock.moko:parcelize

### ISSUE THREAD

**Issue by ahmedsalemelzeiny** [icerockdev/moko-resources#678]
I just upgraded to latest version which is `0.24.0-beta-1` and finished migration steps but while building the app on iOS I got the following error 

```
 Task :coreapp:compileKotlinIosSimulatorArm64 FAILED
error: Could not find "dev.icerock.moko:parcelize" in [/Users/ahmedelzeiny/Documents/Work/mh/CoreProject/iosApp/Pods, /Users/ahmedelzeiny/.konan/klib, /Users/ahmedelzeiny/.konan/kotlin-native-prebuilt-macos-aarch64-1.9.21/klib/common, /Users/ahmedelzeiny/.konan/kotlin-native-prebuilt-macos-aarch64-1.9.21/klib/platform/ios_simulator_arm64]
```

I did app cleaning and also searched for anything that uses the `parcelize` lib in the app or the library but just found the definition of it in the library toml file and I found this  [commit](https://github.com/icerockdev/moko-resources/commit/4c5449dc770063b9da27573db86ed658d8e1d463) which removes the plugin dependancies, Any suggestions?

**Comment by ahmedsalemelzeiny** [comment]
@Alex009 @ExNDY any help?

**Comment by Alex009** [comment]
0.24.0-beta-1 not use parcelize at all.

run `./gradlew :coreapp:dependencies` and find from what dependency you receive parcelize

**Comment by ahmedsalemelzeiny** [comment]
@Alex009 did that and nothing is using `dev.icerock.moko:parcelize`

**Comment by ahmedsalemelzeiny** [comment]
@Alex009 I tried again with version 0.23.0 and I didn't face this issue and also checked all my modules and noting is using `dev.icerock.moko:parcelize` and also tried to add and export it and the same issue.

Can you please check it?

**Comment by alaegin** [comment]
I have the same issue. None of my modules uses the parcelize, but the issue exists

**Comment by ExNDY** [comment]
One moment, you use moko-network? Or moko-network-errors? Or any moko libs exclude resources?

**Comment by alaegin-aiforia** [comment]
I use only moko-resources library and this issue is relevant only for the latest beta version. Latest alpha version works fine

**Comment by alaegin** [comment]
I use only moko-resources library and this issue is relevant only for the latest beta version. Latest alpha version works fine

**Comment by ExNDY** [comment]
beta has many changes under hood include compatibility with kotlin 2.0, thanks for info

**Comment by Alex009** [comment]
@alaegin @ahmedsalemelzeiny can you please run `./gradlew :shared:dependencies` (`shared` replace to gradle project name that build ios framework).
in this dependencies list we should find what library also depends on moko-resources, but uses old version.

i think issue can be just like here - https://github.com/icerockdev/moko-fields/issues/50 when Kotlin/Native write own list of dependencies in klibs

**Comment by Alex009** [comment]
if i right, as workaround can be used directly addition to gradle moko-parcelize dependency.
```
dependencies {
    iosMainImplementation("dev.icerock.moko:parcelize:0.9.0")
}
```

when all used libraries will be updated to moko-resources 0.24.0 you can remove this workaround

**Comment by Alex009** [comment]
so, we check on our project [this](https://github.com/icerockdev/moko-resources/issues/678#issuecomment-2076373530) workaround and confirm that it's works.

to not use this workaround consumer project should not use dependencies that works with moko-resources pre 0.24.0. 
in moko-resources no changes required. need to update dependent libraries to 0.24.0 resources

**Comment by Alex009** [comment]
@ExNDY we should add [this](https://github.com/icerockdev/moko-resources/issues/678#issuecomment-2076373530) workaround to release notes of 0.24.0
