### ISSUE TITLE
Color resolved with colorResource on ios is not updated when resource changes

### ISSUE THREAD

**Issue by shtolik** [icerockdev/moko-resources#681]
Hi, 
I'm updating a background of my row depending on some status (mutableStateOf), but when the view is recomposed after status changes, colorResource is not updated on ios (works fine in android). 
I believe it's becuase of remember(darkMode) in [iosMain/../ColorResource.kt](https://github.com/icerockdev/moko-resources/blob/master/resources-compose/src/iosMain/kotlin/dev/icerock/moko/resources/compose/ColorResource.kt)

```
@Composable
actual fun colorResource(resource: ColorResource): Color {
    // TODO https://github.com/icerockdev/moko-resources/issues/443
    //  recompose when appearance changed (now not works in runtime!)
    val darkMode: Boolean = isSystemInDarkTheme()
    return remember(darkMode) {
        val uiColor: UIColor = resource.getUIColor()

```

I've tested locally and it helped me just changing it to 
 `return remember(resource, darkMode) {`

Probably gonna push a PR soon

**Comment by Alex009** [comment]
please dont create duplicates. you can see in TODO comment that issue already created.
and thx for PR

**Comment by Alex009** [comment]
oh, now i understand that this issue not about change of darkMode value. it's ok that issue separated, thx

**Comment by Alex009** [comment]
will be availale in 0.24.0-beta-2
