### ISSUE TITLE
Function 'stringResource' can not be called: No function found for symbol 

### ISSUE THREAD

**Issue by sunildhiman90** [icerockdev/moko-resources#685]
When i start js browser run, the console alerts 

`IrLinkageError with message Function 'stringResource' can not be called: No function found for symbol 'dev.icerock.moko.resources.compose/stringResource|stringResource(dev.icerock.moko.resources.StringResource;androidx.compose.runtime.Composer?;kotlin.Int){}[0]' and leave me with blank browser view.`

Other platforms works fine android,  desktop and ios.

Compose UI version: 1.6.1
moko-resources: 0.23.0
Kotlin: 1.9.23

**Comment by Alex009** [comment]
@sunildhiman90 check 0.24.0 please

**Comment by sunildhiman90** [comment]
Hi @Alex009 , i tried `0.24.0-beta-1` also, There also same error, I tried everything clean build, invalidate cache and generateMRcommonMain etc., But still error persists.

**Comment by Alex009** [comment]
fixed in 0.24.0-beta-4

**Comment by sunildhiman90** [comment]
Thanx @Alex009 , When will 0.24.0-beta-4 be released?

**Comment by Alex009** [comment]
@sunildhiman90 today
