### ISSUE TITLE
0.24.0-beta-2 includes file extension in `files` and `assets` in the resource name

### ISSUE THREAD

**Issue by zacharee** [icerockdev/moko-resources#690]
This might be intended, but in 0.24.0-alpha-5 and earlier versions, resources inside `files` or `assets` with the format `name.ext` would have their references generated as `MR.[files|assets].name`.

In 0.24.0-beta-2 (and possibly beta-1), the reference is now `MR.[files|assets].name_ext`.

For example, I have `tacs.csv` and `cscs.csv` inside `files` in my project here: https://github.com/zacharee/SamloaderKotlin. On earlier versions, I would reference them with `MR.files.tacs` and `MR.files.cscs`. Now I need to use `MR.files.tacs_csv` and `MR.files.cscs_csv`.

**Comment by ExNDY** [comment]
We choose this variant because in files/assets can be:
Same.txt
Same.svg
Same.gif
Same.pdf
We can't have the same properties in code
