### ISSUE TITLE
Apostrophe incorrectly displayed on iOS

### ISSUE THREAD

**Issue by MartinStrambach** [icerockdev/moko-resources#691]
I have a following string:

`<string name="searchPrompt">Enter a friend\'s name</string>`

It is correctly displayed with 0.24.0 aplha 5, but using 0.24.0 beta 2 it displays `Enter a friend\'s name` instead of `Enter a friend's name`.
Other environments are Kotlin 1.9.23, Xcode 15.3 and iOS 17.4.

**Comment by Alex009** [comment]
In xml you should not use \' - use just '
Plugin automatically convert it to correct variant for all platforms

**Comment by MartinStrambach** [comment]
Is it something that has changed since alpha 5? We were unable to build string assets without escaping all `'` characters.
