### ISSUE TITLE
Resolving dependency configuration 'metadataCompilationApi' is not allowed as it is defined as 'canBeResolved=false'

### ISSUE THREAD

**Issue by KursX** [icerockdev/moko-resources#703]
Problem in multimodule project

Configuration cache state could not be cached: field `apiConfiguration` of `org.jetbrains.kotlin.gradle.plugin.mpp.compilationImpl.DefaultKotlinCompilationConfigurationsContainer` bean found in field `dependencyConfigurations` of `org.jetbrains.kotlin.gradle.plugin.mpp.compilationImpl.KotlinCompilationImpl$Params` bean found in field `params` of `org.jetbrains.kotlin.gradle.plugin.mpp.compilationImpl.KotlinCompilationImpl` bean found in field `$$delegate_0` of `org.jetbrains.kotlin.gradle.plugin.mpp.KotlinCommonCompilation` bean found in field `underlying` of `org.jetbrains.kotlin.gradle.utils.MutableObservableSetImpl` bean found in field `compilations` of `org.jetbrains.kotlin.gradle.plugin.sources.DefaultKotlinSourceSet` bean found in field `$kotlinSourceSet` of `dev.icerock.gradle.MultiplatformResourcesPlugin$createSourceSet$1` bean found in field `sourceSet` of `dev.icerock.gradle.generator.common.CommonMRGenerator` bean found in field `generator` of task `:strings:generateMRcommonMain` of type `dev.icerock.gradle.tasks.GenerateMultiplatformResourcesTask`: error writing value of type 'org.gradle.api.internal.artifacts.configurations.DefaultUnlockedConfiguration'
> Resolving dependency configuration 'metadataCompilationApi' is not allowed as it is defined as 'canBeResolved=false'.
  Instead, a resolvable ('canBeResolved=true') dependency configuration that extends 'metadataCompilationApi' should be resolved.

**Comment by Alex009** [comment]
Hi. Please use 0.24.0-beta-3
