### ISSUE TITLE
Suggested improvements to CopyFrameworkResourcesToAppTask

### ISSUE THREAD

**Issue by syxc** [icerockdev/moko-resources#709]
### Discussed in https://github.com/icerockdev/moko-resources/discussions/701

<div type='discussions-op-text'>

<sup>Originally posted by **syxc** May 10, 2024</sup>
`CopyFrameworkResourcesToAppTask` is not well designed, if the `baseName` of the iOS framework in the `shared` module of KMP is not the same as it is, something will go wrong, e.g.

KMP shared project `shared`

```
├── LICENSE
├── README.md
├── build.gradle.kts
├── gradle
├── gradle.properties
├── gradlew
├── gradlew.bat
├── androidApp
├── iosApp
├── shared
└── settings.gradle.kts
```

```kotlin
cocoapods {
  summary = "Some description for the Shared Module"
  homepage = "Link to the Shared Module homepage"
  version = "1.0"
  ios.deploymentTarget = "13.0"
  framework {
    baseName = "SharedKit"
    binaryOptions["bundleId"] = "com.github.app.shared"
    isStatic = true
    export(moko.resources)
    export("dev.icerock.moko:graphics:0.9.0")
  }
  podfile = project.file("../iosApp/Podfile")
}
```

You guys can go ahead and try it out, you can see this kind of problem I'm getting feedback on when Moko executes the script in Xcode.

</div>

**Comment by Alex009** [comment]
Will be released in 0.24.0-beta-5
