### ISSUE TITLE
Remove unnecessary dependency 

### ISSUE THREAD

**Issue by zt64** [icerockdev/moko-resources#718]
Hi, a problem I've noticed is that moko resources brings in material 2 dependency which is really annoying especially when my project is set to use material 3. I've narrowed it down to this one specific dependency which should be removed. I tested locally and all tests passed

https://github.com/icerockdev/moko-resources/blob/6ed5168a683347b8bb26f103e2f6f44a5f979855/resources-compose/build.gradle.kts#L55

**Comment by Alex009** [comment]
will be released in 0.24.0-beta-5
