### ISSUE TITLE
How do I get the text value on JVM?

### ISSUE THREAD

**Issue by shalva97** [icerockdev/moko-resources#721]
So suppose I don't want to target ios or android. Just JVM app.

right now I have this one StringResouce `println(MR.strings.common_name)`. what should I call? in the README it only mentions IOS and Android.

When I try to run it then it prints 
```
ResourceStringDesc(stringRes=StringResource(resourcesClassLoader=jdk.internal.loader.ClassLoaders$AppClassLoader@531d72ca, bundleName=localization/iogithubshalva97_mokoBundle, key=common.name))
```
Also tried to call .desc() but it still writes class name

**Comment by ExNDY** [comment]
You try to check samples? 
For example:
https://github.com/icerockdev/moko-resources/blob/develop/samples%2Fcompose-jvm-app%2Fcommon%2Fsrc%2FdesktopMain%2Fkotlin%2Fme%2Famikhailov%2Fcommon%2FMain.kt#L18

**Comment by shalva97** [comment]
yea that worked. the sample has only jvm() target so in commonMain it can also use jvm specific API, but mine also had macosX64(). so as I understood I have to write platform specific declarations to get String values...
