### ISSUE TITLE
Have a dumb question about a different approach to save resources directly in a Kotlin file :D

### ISSUE THREAD

**Issue by shalva97** [icerockdev/moko-resources#722]
So on different platforms resources are handled differently. On Android it needs context, on iOS there is different function call, etc.

What if instead of resources in an actual resources folder it was saved directly in a `someGeneratedKotlinCode.kt` file? meaning it will work on all possible platforms, including on Android without the need of Context.

Actually, I tried something like this by hand. Wrote 3MB JSON code in a single file like `const val rawJson = "3MB json text here..."` and it did not work, compiler throw out of memory exception. That's why I decided to try your library. but anyway it is possible to give JVM more RAM, have no tried it but seems doable. 

So what are other things that could go wrong?

**Comment by ExNDY** [comment]
That question not about library, please find forums or chats for consultation about jvm in Kotlin Multiplatform. 

P.S: save resources in code is bad ideas because release builds has optimisations and obfuscate for code.
