### ISSUE TITLE
Add dark mode variants for images

### ISSUE THREAD

**Issue by BasBuijsen** [icerockdev/moko-resources#728]
First of all i want to say that i love this project and its very valuable in my projects. It has become a standard for every kmp project i start.

I have one request for an improvement. Colors already have support for dark mode alternatives. I would also like this same capability for image resources. For example when the app is in darkmode i would want to have a white icon and when the app is in lightmode i would want to have a black version of that icon.

I would expect a file extension like `_dark` after the @1x for sizing for example. I dont really care about the syntax as long as it works :).

I would love to hear if this is possible and if other people also would like this feature.

**Comment by Alex009** [comment]
@BasBuijsen it's already implemeted in 0.24.0. try 0.24.0-beta-5

**Comment by BasBuijsen** [comment]
@Alex009 Amazing! im sorry i didnt check that before opening an issue.
