### ISSUE TITLE
Build fails if it is not running on MacOS

### ISSUE THREAD

**Issue by Skeptick** [icerockdev/moko-resources#73]
```
Execution failed for task ':mppLibrary:generateMRiosMain'.
Caused by: org.gradle.api.UncheckedIOException: java.io.IOException: Cannot run program "xcrun" (in directory "/home/.../mppLibrary/build/generated/moko/iosMain/res"): error=2, No such file or directory
```

I fix this by checking the OS, but I think it would be logical to embed something like this in the plugin :)

```kotlin
tasks.whenTaskAdded {
    if (name == "generateMRiosMain") onlyIf {
        org.gradle.internal.os.OperatingSystem.current()!!.isMacOsX
    }
}
```

**Comment by Alex009** [comment]
hi. thanks for feedback!

generation of ios resources should be triggered only when we call compilation of iOS targets...how and why you run compilation of ios not on macos host? or task was execute by some other trigger?

**Comment by Skeptick** [comment]
The task of compilation the iOS target is skipped, as expected.
```
Some Kotlin/Native targets cannot be built on this linux_x64 machine and are disabled:
    * In project ':mppLibrary':
        * target 'ios' (can be built with a macos_x64 host)
To hide this message, add 'kotlin.native.ignoreDisabledTargets=true' to the Gradle properties.
```

I don't know why the task of generating resources is launched 🤔

**Comment by Skeptick** [comment]
I removed:
```kotlin
val onPhone = System.getenv("SDK_NAME")?.startsWith("iphoneos") ?: false
if (onPhone) iosArm64("ios") else iosX64("ios")
```

And did just `ios()`. And the error is gone. I don't understand what this is due to.

**Comment by Alex009** [comment]
fix merged, will be available in next release
