### ISSUE TITLE
Cannot access 'dev.icerock.moko.resources.ResourceContainer'

### ISSUE THREAD

**Issue by Egi10** [icerockdev/moko-resources#737]
I encountered an error in my multimodule project after updating to Moko Resources version 0.24.1. The error occurs when using strings in the actual class on the iOS platform (iosMain).

```
Cannot access 'dev.icerock.moko.resources.ResourceContainer' which is a supertype of 
'id.example.common.resources.FeederRes.strings'. 
Check your module classpath for missing or conflicting dependencies
```

Project Structure:
-shared
--common
---resource
--core

Example Code:

Common (expect):
```
expect class CSVGenerate {
fun generateBody()
}
```

```
fun getMyFormatDesc(input: String): StringDesc {
    return StringDesc.ResourceFormatted(MR.strings.my_string_formatted, input)
}
```

iOS (actual):
```
actual class CSVGenerate {
actual fun generateBody() {
val string = getMyFormatDesc(input: "hello").localized()
}
}
```

Android (actual):
```
actual class CSVGenerate {
actual fun generateBody() {
val string = getMyFormatDesc("hello").toString(context = this)
}
```

Note:
This error was encountered during a rebuild in Android Studio, but the project still runs when executed on Android and iOS.

**Comment by Alex009** [comment]
hi. can you create small reproducer project?

**Comment by Egi10** [comment]
I've tried replicating the issue by creating a sample project, but the same error doesn't occur.

Previously, I was using version 0.23.0 and everything was working smoothly. When the latest version came out and I wanted to upgrade Kotlin, I tried to update. However, I encountered the error.

**Comment by Egi10** [comment]
I haven't encountered this issue before, but my project is not working properly. For now, I have downgraded to version 0.23.0 and implemented the solution from https://github.com/icerockdev/moko-resources/issues.

**Comment by Egi10** [comment]
After further investigation, I discovered that the root cause of the issue lies in the module naming convention within my project:

-shared
--common
---resources
--core

This naming structure triggers an error during the execution of `compileIosMainKotlinMetadata`. However, if I change the module name to anything other than `resources`, the error disappears.

Example project: https://github.com/Egi10/resources

cc @Alex009

**Comment by Egi10** [comment]
I'm now encountering an issue when running the app on iOS with the error: `kotlin.IllegalArgumentException: bundle with identifier ***.main not found`. I've also added a new configuration, but the problem persists : 

```
"$SRCROOT/../gradlew" -p "$SRCROOT/../" :yourframeworkproject:copy`YourFrameworkName`FrameworkResourcesToApp \
    -Pmoko.resources.BUILT_PRODUCTS_DIR="$BUILT_PRODUCTS_DIR" \
    -Pmoko.resources.CONTENTS_FOLDER_PATH="$CONTENTS_FOLDER_PATH" \
    -Pkotlin.native.cocoapods.platform="$PLATFORM_NAME" \
    -Pkotlin.native.cocoapods.archs="$ARCHS" \
    -Pkotlin.native.cocoapods.configuration="$CONFIGURATION" 
```

**Comment by Alex009** [comment]
>This naming structure triggers an error during the execution of compileIosMainKotlinMetadata. However, if I change the module name to anything other than resources, the error disappears.

i think it's kotlin bug with module names clash. https://youtrack.jetbrains.com/issue/KT-57914

**Comment by Egi10** [comment]
I added the following script to the Build Phase:

```
"$SRCROOT/../gradlew" -p "$SRCROOT/../" :shared:core:copyPodFrameworkResourcesToApp \
  -Pmoko.resources.BUILT_PRODUCTS_DIR="$BUILT_PRODUCTS_DIR" \
  -Pmoko.resources.CONTENTS_FOLDER_PATH="$CONTENTS_FOLDER_PATH" \
  -Pkotlin.native.cocoapods.platform="$PLATFORM_NAME" \
  -Pkotlin.native.cocoapods.archs="$ARCHS" \
  -Pkotlin.native.cocoapods.configuration="$CONFIGURATION"
```

However, I encountered this error at runtime when trying to access the resources.

<img width="669" alt="Screenshot 2024-07-22 at 13 33 25" src="https://github.com/user-attachments/assets/9e460da5-c711-4993-bdfb-463acebf3366">


I got the copyPodFrameworkResourcesToApp from a warning.

```
linkPodDebugFrameworkIosArm64 is found.
If you use a static framework, Xcode should have Build Phase with copyPodFrameworkResourcesToApp gradle task call. 
Please read readme on https://github.com/icerockdev/moko-resources
-
To hide this message, add 'moko.resources.disableStaticFrameworkWarning=true' to the Gradle properties.
```

**Comment by Egi10** [comment]
Issue resolved, it turned out there was a problem with my custom plugin.
