### ISSUE TITLE
Not being generated Resources String Kotlin 2.0

### ISSUE THREAD

**Issue by And-DS** [icerockdev/moko-resources#741]
I am generating String resources with Kotlin 2.0 for an app using KMM, but the SharedRes files are not being generated. Looking into the folders, they are empty. I don't know what I'm doing wrong, attaching screenshots. I am using a Mac M1 with Android Studio Koala | 2024.1.1
build.gradle project 
```
plugins {
    //trick: for the same plugin versions in all sub-modules
    alias(libs.plugins.androidApplication).apply(false)
    alias(libs.plugins.androidLibrary).apply(false)
    alias(libs.plugins.kotlinAndroid).apply(false)
    alias(libs.plugins.kotlinMultiplatform).apply(false)
    alias(libs.plugins.compose.compiler).apply(false)

}
buildscript {
    dependencies {
        classpath("dev.icerock.moko:resources-generator:0.24.1")
    }
}
```
build.gradle shared module 
```
plugins {
    alias(libs.plugins.kotlinMultiplatform)
    alias(libs.plugins.androidLibrary)
    id("dev.icerock.mobile.multiplatform-resources")

}

kotlin {
    androidTarget {
        compilations.all {
            kotlinOptions {
                jvmTarget = "1.8"
            }
        }
    }
    
    listOf(
        iosX64(),
        iosArm64(),
        iosSimulatorArm64()
    ).forEach {
        it.binaries.framework {
            baseName = "shared"
            isStatic = true
            export("dev.icerock.moko:resources:0.24.1")
            export("dev.icerock.moko:graphics:0.9.0") // toUIColor here
        }
    }

    sourceSets {

        commonMain.dependencies {
            api(libs.resource.moko)
        }
        commonTest.dependencies {
            implementation(libs.kotlin.test)
        }
    }


}

android {
    namespace = "com.alfran"
    compileSdk = 34
    defaultConfig {
        minSdk = 26
    }
    compileOptions {
        sourceCompatibility = JavaVersion.VERSION_1_8
        targetCompatibility = JavaVersion.VERSION_1_8
    }
}



multiplatformResources {
    resourcesPackage.set("com.alfran")
    resourcesClassName.set("SharedRes")
}
```
Strings resources folder 
![image](https://github.com/icerockdev/moko-resources/assets/173818046/3d27b62b-d39e-48a1-871f-ac149e9aafb7)

build generated 
![image](https://github.com/icerockdev/moko-resources/assets/173818046/a42e15f3-ed39-44ea-ae82-17d7da821048)
![image](https://github.com/icerockdev/moko-resources/assets/173818046/1b0b3fcf-161f-4b14-a62b-a5ac971197bd)

I need your help... I dont know what I doing wrong

**Comment by ExNDY** [comment]
Hi, please read readme and check samples. I don't know why u place moko-resources like on screens. 
should be:
Module/src/sourceSet/moko-resources
For example:
shared/src/commonMain/moko-resources

**Comment by And-DS** [comment]
Hi, big mistake.... thanks! close issue

**Comment by amijsul** [comment]
You guys should've written a migration guide for 0.23.0 to 0.24.0. (the old req was to put commonMain/resources/MR) I was stuck trying to figure out why the resources were not generating when I finally stumbled upon this issue.
This fixed it.

**Comment by ExNDY** [comment]
@amijsul Hm...We write guide in release: https://github.com/icerockdev/moko-resources/releases/tag/release%2F0.24.0
also have been updated all samples and readme.

**Comment by amijsul** [comment]
I did not see that, thank you for pointing it out! that guide is very helpful.

**Comment by funyin** [comment]
Thanks @ExNDY .

It will be nice to have this in the readme for people like me who are using the library for the first time. 
I also had this issue

Great work 💪🏿
