### ISSUE TITLE
Unresolved Reference: 'string'

### ISSUE THREAD

**Issue by griffinsorrentino** [icerockdev/moko-resources#744]
When using compose multiplatform `1.7.0-alpha01` an error occurs when trying to launch the Android app

`e: file:///.../composeApp/build/generated/kotlin/generateMRandroidMain/com/example/com/Res.kt:17:75 Unresolved reference 'my_string'.`

Bumping compose multiplatform back down to `1.6.11` fixes the issue, but this issue will likely persist with the upcoming `1.7.0` release

Minimal reproducer: https://github.com/griffinsorrentino/moko-resources-bug

**Comment by Elelan** [comment]
Getting the same error after upgrading compose multiplatform to `1.7.0-alpha01`.
Also using `KSP2`.

**Comment by zacharee** [comment]
It works again with `1.7.0-dev1721` and later

**Comment by Alex009** [comment]
@zacharee cool!

**Comment by griffinsorrentino** [comment]
Confirmed as fixed with `1.7.0-alpha02`
