### ISSUE TITLE
Escaping % Character Not Working on iOS in 0.24.1

### ISSUE THREAD

**Issue by zkovar** [icerockdev/moko-resources#746]
Hello 👋🏻 After updating from 0.23 to 0.24.1 (kotlin 1.9.23), I uncovered an issue that only appears on iOS. 

With the following string:

```
<string name="discount_percentage">%d\%% discount</string>
```

Running:

```
MR.strings.discount_percentage.format(5).localized()
```

renders: `5% discount` on Android
but on iOS, it renders `5\% discount`

Is this expected?

**Comment by ExNDY** [comment]
Hi, you can use percent without mirroring

**Comment by zkovar** [comment]
```
<string name="discount_percentage">%d%% discount</string>
```
Worked 😄 Thanks
