### ISSUE TITLE
Localized strings is not available on iOS if iOS-framework was compiled by Gradle FatFramework task

### ISSUE THREAD

**Issue by romanandreyvich** [icerockdev/moko-resources#75]
When I use Gradle FatFramework task, I can't see any of my localized strings on iOS side
The task I use to compile my framework:
```
val fatFramework by tasks.creating(FatFrameworkTask::class) {
    baseName = "multiplatform"

    val targets = listOf(
            kotlin.targets.getByName<KotlinNativeTarget>("iosX64"),
            kotlin.targets.getByName<KotlinNativeTarget>("iosArm64")
    )

    from(targets.map { it.binaries.getFramework("DEBUG") })
}
```

If I change it to Gradle Sync task it works as expected (I see all my strings on iOS side):
```
val syncFramework by tasks.creating(Sync::class) {
    val targetDir = File(buildDir, "frameworks")
    val mode = "DEBUG"
    val framework = kotlin.targets
            .getByName<KotlinNativeTarget>("ios")
            .binaries.getFramework(mode)
    inputs.property("mode", mode)
    dependsOn(framework.linkTask)
    from({ framework.outputDirectory })
    into(targetDir)
}

```

Kotlin 1.3.72, moko-resources 0.10.0 (had the same issue on 0.9.1)

Do you have any ideas what a cause of the issue? And am I able to fix it?

**Comment by Alex009** [comment]
hi!
reason of it is internal implementation of `FatFrameworkTask` - this task not copy resource files of frameworks. I think we should add to our gradle plugin extended FatFrameworkTask implementation, which will copy all resources too.

**Comment by Alex009** [comment]
merged, will be available in next release
