### ISSUE TITLE
Formatted strings doesn't work properly

### ISSUE THREAD

**Issue by SrgGrch** [icerockdev/moko-resources#76]
I have formatted string in my multiplatform strings that look like:

` <string name="myString">%s from %s</string>`

When I'm trying to get this string with this code:

`StringDesc.ResourceFormatted(MR.strings.myString, arg1, arg2).toString(context) `
(arg1 and arg2 are Int)

I'm getting this error:
```
 java.util.MissingFormatArgumentException: Format specifier '%s'
        at java.util.Formatter.format(Formatter.java:2522)
        at java.util.Formatter.format(Formatter.java:2458)
        at java.lang.String.format(String.java:2883)
        at android.content.res.Resources.getString(Resources.java:481)
        at dev.icerock.moko.resources.desc.ResourceFormattedStringDesc.toString(ResourceFormattedStringDesc.kt:16)
        at co.getfullstack.skill.presentation.common.ResourceProvider.getString(ResourceProvider.kt:29)
```
Also if I remove one of format argument from my string I will receive strings like this one: 
"[Ljava.lang.Object;@6b0dc06 from".

Also, I've tried some variants of string:
* `<string name="myString">%d from %d</string>` - `java.util.IllegalFormatConversionException: d != [Ljava.lang.Object;`, even if I pass Int value.
* `<string name="myString">%1$s from %2$s</string>` - `java.util.MissingFormatArgumentException: Format specifier '%2$s'` 

OS: Android
Lib version: 0.9.1, 0.10.0
Kotlin: 1.3.71

**Comment by Alex009** [comment]
Hi! 
I'm sorry that you ran into a problem, thanks for bugreport. we will debug it and fix

**Comment by Tetraquark** [comment]
Unfortunately we can't reproduce the bug. What we did:

1. In `strings.xml` add resource:

```
<string name="myString">%s from %s</string>
```

2. In a `Activity` get the string like this:

```kotlin
val str1 = StringDesc.ResourceFormatted(MR.strings.myString, "str1", "str2").toString(this)
val str2 = StringDesc.ResourceFormatted(MR.strings.myString, 10, 20).toString(this)
println("Output: $str1 | $str2")
```

3. Run Android app and got output like this:

```
Output: str1 from str2 | 10 from 20
```

@SrgGrch can you please describe in more detail the steps to reproduce this problem? Or will you be able to show an example of a project where this bug is reproduced?

**Comment by SrgGrch** [comment]
Sorry for the long reply, I realized that it was my fault, I missed "*" when passed varargs, sorry for the false alarm

**Comment by danaanne1** [comment]
Docs are wrong:
    String.format("%1$ts","2022-12-12");
breaks for java8 (on windows). Format specifier should be 's' not 'ts'
