### ISSUE TITLE
Escaped ? shows escape sequence (\?)

### ISSUE THREAD

**Issue by Syer10** [icerockdev/moko-resources#760]
Our translation software escapes `?` like `\?` for compatibility with Android string files. This seems to cause an issue with Moko as on non-android platforms it displays as `\?` instead of `?` like its meant to.

I think its an easy fix by adding 
```kt
.replace("""\?""", "?") 
```
 to this function https://github.com/icerockdev/moko-resources/blob/97434934cbdab6a07dc32bb70cb2f78d76cd3097/resources-generator/src/main/kotlin/dev/icerock/gradle/utils/StringExt.kt#L52-L56

If a release could be pushed for this fix soon that would be great. Thanks.

**Comment by Alex009** [comment]
will be released in 0.24.3
