### ISSUE TITLE
Moko-Resource crashing iOS app while accessing the resource

### ISSUE THREAD

**Issue by AliAzaz** [icerockdev/moko-resources#771]
I am working on the KMP library in which I want to share the .js file between platforms as I followed the same way of initializing dependencies according to the documentation but still, it is crashing my iOS app. 

I am generating XCFramework in Android studio from this command:
`./gradlew assembleSharedLibraryDebugXCFramework`

And then the generated XCFramework going to be used in another iOS project.

This is my gradle:
```
import org.jetbrains.kotlin.gradle.plugin.mpp.apple.XCFramework

plugins {
    alias(libs.plugins.kotlinMultiplatform)
    alias(libs.plugins.kotlinCocoapods)
    alias(libs.plugins.androidLibrary)
    id("dev.icerock.mobile.multiplatform-resources")
}

kotlin {
    //android
    androidTarget {
        compilations.all {
            kotlinOptions {
                jvmTarget = "1.8"
            }
        }
    }

    //iOS
    val iosArm64 = iosArm64()
    val iosX64 = iosX64()
    val iosSimulatorArm64 = iosSimulatorArm64()

    val xcFramework = XCFramework("SharedLibrary")
    configure(listOf(iosArm64, iosX64, iosSimulatorArm64)) {
        binaries {
            framework {
                isStatic = true
                version = "1.0"
                baseName = "SharedLibrary"
                xcFramework.add(this)
                export("dev.icerock.moko:resources:0.24.2")
                export("dev.icerock.moko:graphics:0.9.0")
            }
        }
    }

    sourceSets {
        commonMain.dependencies {
            api("dev.icerock.moko:resources:0.24.2")
        }
        commonTest.dependencies {
            implementation(libs.kotlin.test)
        }

        iosMain.dependencies {
        }

        androidMain.dependencies {
            implementation("dev.icerock.moko:resources:0.24.2")
        }
    }
}

android {
    namespace = "com.aliazaz.testkmplibrary"
    compileSdk = 34
    defaultConfig {
        minSdk = 22
    }
    compileOptions {
        sourceCompatibility = JavaVersion.VERSION_1_8
        targetCompatibility = JavaVersion.VERSION_1_8
    }
    sourceSets["main"].resources.srcDirs("src/commonMain/moko-resources/assets")
}

multiplatformResources {
    resourcesPackage.set("com.aliazaz.testkmplibrary") // required
    configureCopyXCFrameworkResources("SharedLibrary")
}

```

**Comment by AliAzaz** [comment]
@Alex009 please check.

**Comment by Alex009** [comment]
with static framework you should use custom build phase.

https://github.com/icerockdev/moko-resources?tab=readme-ov-file#creating-xcframework-with-resources

more info - https://github.com/icerockdev/moko-resources?tab=readme-ov-file#iosmacos-static-kotlin-frameworks-support

**Comment by AliAzaz** [comment]
I am new in iOS development, therefore, I am not quite sure about the static framework. But what I doing is generating the XCFramework directory and importing it into my other iOS app.

I believe this is best fitted in my case:
https://github.com/icerockdev/moko-resources?tab=readme-ov-file#creating-xcframework-with-resources

But I also don't want to use this `configureCopyXCFrameworkResources("SharedLibrary")` as after building the project it also removed all of the IntelliSense.

**Comment by AliAzaz** [comment]
I have done some around and it is working now. What I have done is add my XCFramework in Bundle Resources and it is now fetching resources.

![image](https://github.com/user-attachments/assets/dc9d3b3d-4c19-4e34-a88e-7fb6ce276bf8)
