### ISSUE TITLE
Function Enhancement Request: Can the code for automatically generating resource images support the WEBP format?

### ISSUE THREAD

**Issue by subgrand** [icerockdev/moko-resources#779]
Dear Moko development expert, how are you today！
   I've encountered a small issue and could you please help me out? Due to the reduced storage space that the WEBP format offers for the same image, we prefer to use images in WEBP format in our Android project at work. 
  When I introduced images in WEBP format into a KM project with moko version 0.24.3 and performed a "Sync project," I found that no code was generated. Could this be a problem with my code? Or does this project simply not support images in WEBP format? If it's the latter, will future versions support it?

**Comment by Alex009** [comment]
hello.
as i know webp native support exist only on android, iOS 14+, web. but we also support macos, watchos, jvm and i dont know is it possible to support webp without external dependencies on this platforms or not.
if you have experience with webp on all moko-resoruces's supported platforms please share your knowledge. if we can use webp on all supported platforms we will add this feature in future releases.

if webp can be used only on subset of platforms - we will not add this feature. or maybe somebody give some idea how give valid api for users that will clearly describe that webp supported only on subset

**Comment by subgrand** [comment]
Wow, thank you for your response.
   I have clearly understood your meaning. I think what you mentioned at the end, "or maybe somebody give some idea how to give valid API for users that will clearly describe that WebP is supported only on a subset," is a good solution for the project I'm currently working on. Since my current development task only needs to support the Android and iOS platforms。
 I have got the answer I wanted.So I'm closing this issue. 
 Thank you again for your reply. Wish you all the best！
