### ISSUE TITLE
Cannot add task 'copyResourcesDebugTestIosArm64' as a task with that name already exists.

### ISSUE THREAD

**Issue by djordjeh** [icerockdev/moko-resources#783]
Hello, I hope someone can help me to resolve this. Basically as soon I add moko plugin to my :shared module I get this error from Gradle and Im unable to proceed. I use Kotlin 2.0.0

This is part of build.gralde.kts in :shared module

```
kotlin {
listOf(
        iosX64(),
        iosArm64(),
        iosSimulatorArm64(),
    ).forEach {
        it.binaries.framework {
            baseName = "shared"
            isStatic = true
        }
    }
}
```

End the error  happens:

A problem occurred configuring project ':shared'.
> Cannot add task 'copyResourcesDebugTestIosArm64' as a task with that name already exists.

**Comment by Alex009** [comment]
maybe some another plugin already create copyResourcesDebugTestIosArm64 task?

**Comment by djordjeh** [comment]
Hi @Alex009 you are right. Any idea how I could keep both plugins?

**Comment by djordjeh** [comment]
I have found a solution, thank you @Alex009. Im closing the ticket.
