### ISSUE TITLE
Can't compile with Kotlin 2.1.0

### ISSUE THREAD

**Issue by griffinsorrentino** [icerockdev/moko-resources#786]
With Kotlin 2.1.0, the new default is to generate non-packed klib files
https://kotlinlang.org/docs/whatsnew21.html#support-for-non-packed-klibs

This is causing a `FileNotFoundException (Is a directory)` error because the klib file attempting to be unzipped is an unpacked klib directory and not a .klib file

```
Caused by: java.io.FileNotFoundException: <module name>/build/classes/kotlin/iosArm64/main/klib/<module name> (Is a directory)
	at dev.icerock.gradle.utils.ZipUtilsKt.unzipTo(ZipUtils.kt:14)
	at dev.icerock.gradle.actions.apple.PackAppleResourcesToKLibAction.execute(PackAppleResourcesToKLibAction.kt:50)
	at dev.icerock.gradle.actions.apple.PackAppleResourcesToKLibAction.execute(PackAppleResourcesToKLibAction.kt:19)
```

The error is linked to this function
https://github.com/icerockdev/moko-resources/blob/2c484808c928a13ab4d0523b82db3b5ab4e90db5/resources-generator/src/main/kotlin/dev/icerock/gradle/utils/ZipUtils.kt#L13-L20

File structure in Kotlin 2.0.21:
![Group 31](https://github.com/user-attachments/assets/4ca475df-aab5-4de3-8f42-bf1fdfae16ef)

File structure in Kotlin 2.1.0:
![Group 30](https://github.com/user-attachments/assets/d6ee2c9c-1695-4d43-8d73-34742b36a9ea)

**Workaround:**
As a temporary workaround, you can change back to packed libs - https://kotlinlang.org/docs/whatsnew21.html#how-to-set-up-your-project
Although using unpacked for the performance improvement (even if very minor) would be the ideal end goal

**Comment by griffinsorrentino** [comment]
> Hi [griffinsorrentino](https://github.com/griffinsorrentino), would you be able to show a simple example of how to force packed libs in a KMM project? I'm trying to apply the configuration without luck.

The configuration I believe is only for plugins, you can add `kotlin.internal.klibs.non-packed=true/false` in your properties file to force Kotlin to use packed libs

**Comment by AndroidPat** [comment]
Thank you. Unfortunately I get the same FileNotFound error with
kotlin.internal.klibs.non-packed=true

and with kotlin.internal.klibs.non-packed=false the whole project falls apart because of broken imports. @Alex009 is there any chance for any work-in-progress snapshot soon that would fix it?

**Comment by Alex009** [comment]
fix will be in 0.24.4

**Comment by griffinsorrentino** [comment]
@Alex009 Thank you for your swift resolution on this!

**Comment by Burtan** [comment]
Could it be possible that this is still bugged for tests?
