### ISSUE TITLE
iOS Extension process using resources will crash because the bundle can't be found

### ISSUE THREAD

**Issue by skytoup** [icerockdev/moko-resources#787]
https://github.com/icerockdev/moko-resources/commit/43c0101ab01bb294b42573311461eeddd29b28bd#diff-74b2961a5d6d48ad53d5ab6e4529f3688bdae02391f7d66628bdb6086a06854eL14

If iOS has App and Extension sharing moko framework, Extension's `NSBundle.mainBundle` and App's `NSBundle.mainBundle` paths are not the same, resulting in the App being able to locate the corresponding bundle, while Extension can't locate it and crashes.

I think we should keep the ID Lookup Bundle as a backup, even though it is a bit slow the first time around!

**Comment by Alex009** [comment]
hi. it will be fixed in #747

**Comment by Alex009** [comment]
fix will be released in 0.24.4
