### ISSUE TITLE
Accessing MR strings from Swift

### ISSUE THREAD

**Issue by franrc** [icerockdev/moko-resources#80]
Hi!

I'm testing this plugin and everything works fine, but, from XCode I'm not able to access to MR.strings.  values

I would like to use them directly to for passing it as parameter to a Shared function. 

Is this possible?

Thanks for your effort!

**Comment by Alex009** [comment]
Hi!
As i know this class should be available from platform code. 

that's example from our project's multiplatform framework:
```
__attribute__((objc_subclassing_restricted))
__attribute__((swift_name("MR.strings")))
@interface MPLMRStrings : MPLBase
+ (instancetype)alloc __attribute__((unavailable));
+ (instancetype)allocWithZone:(struct _NSZone *)zone __attribute__((unavailable));
+ (instancetype)strings __attribute__((swift_name("init()")));
@property (readonly) MPLStringResource *addFunds_available __attribute__((swift_name("addFunds_available")));
@property (readonly) MPLStringResource *addFunds_confirm __attribute__((swift_name("addFunds_confirm")));
@property (readonly) MPLStringResource *addFunds_customAmount __attribute__((swift_name("addFunds_customAmount")));
@property (readonly) MPLStringResource *addFunds_description __attribute__((swift_name("addFunds_description")));
@property (readonly) MPLStringResource *addFunds_title __attribute__((swift_name("addFunds_title")));
@property (readonly) MPLStringResource *add_funds_title __attribute__((swift_name("add_funds_title")));
@end;
```

to use it from Swift side it should be: `MR.strings().addFunds_description` for example.
invocation of constructor for strings is just Kotlin/Native version of singleton getting - https://kotlinlang.org/docs/reference/native/objc_interop.html#kotlin-singletons

**Comment by franrc** [comment]
Thanks for the answer!

My problem really was that my SharedCode framework was added but not checked as Embed&Sign. So swift was not able to find the resources bundle.
