### ISSUE TITLE
Help fix error generateMRiosX64Main

### ISSUE THREAD

**Issue by Diy2210** [icerockdev/moko-resources#96]
In my project use 4 icons. I try generate generateMRiosX64Main, but I get error. 

![Снимок экрана 2020-07-22 в 17 38 02](https://user-images.githubusercontent.com/9552501/88191383-0f9cd400-cc44-11ea-83e5-a79b2ed28201.png)

 
![Снимок экрана 2020-07-22 в 17 38 33](https://user-images.githubusercontent.com/9552501/88191407-14618800-cc44-11ea-9599-c5c5087b30fa.png)

![Снимок экрана 2020-07-22 в 17 37 33](https://user-images.githubusercontent.com/9552501/88191511-2d6a3900-cc44-11ea-8baa-4e02f43d9293.png)

How fix it?

**Comment by Alex009** [comment]
@Diy2210 files should have size qualificator - https://github.com/icerockdev/moko-resources#example-7---pass-image
tick@1x.png, tick@2x.png, tick@3x.png

**Comment by Diy2210** [comment]
> @Diy2210 files should have size qualificator - https://github.com/icerockdev/moko-resources#example-7---pass-image
> [tick@1x.png](mailto:tick@1x.png), [tick@2x.png](mailto:tick@2x.png), [tick@3x.png](mailto:tick@3x.png)

Tnx!
